### ISSUE TITLE
BT-507: Organsiation NUTS Code: automate!

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#10]
If this is really the organistion's physical address code then this could be automated based on postal code and locality. 

Have as few fields to fill in as possible...

**Comment by JachymHercher** [comment]
We agree (see details in #9). This should be done in user interfaces.

Please note that this information must be included in the notices because it is explicitly requested in the annexes to the procurement directives. (In some countries this might even be useful, as postal codes are not freely available in all countries while NUTS codes are.)
