### ISSUE TITLE
BT-135 (Direct Accelerated Justification); description; overloaded semantics

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#101]
While the technician in me rejoices, as accelerated procedures will never be direct awarding procedures, conceptually is seems weird that this field has a different meaning depending on Procedure Type.

**Comment by tinne** [comment]
Did you by the way consider to consolidate Future Notice (BT-127) and Dispatch Invitiation Interest (BT-631) into one field?

The semantics here seems to align quite neatly (”next time you can expect to be hearing from us“).

**Comment by JachymHercher** [comment]
Note: this situation is similar for BT-131 (Deadline Receipt Tenders) (see #173) and potentially also BT-145 (Contract Conclusion Date).

**Comment by paulakeen** [comment]
My opinion is that BT-127 and BT-631 are used for different purposes, contain different data, occur in different transactional moments....(or am I wrong?)....they should be kept separated. 

About renaming BT-127, I don't see the need for the word "Publication"....isn't that the fate of any notice?

**Comment by tinne** [comment]
> My opinion is that BT-127 and BT-631 are used for different purposes, contain different data, occur in different transactional moments....(or am I wrong?)....they should be kept separated.

They are mutually exclusive. Either I will do another publication and people can then participate or bid (Future Notice), or they will have to act now and be put on a list that will later be asked again (as a somewhat closed circle) to confirm they interest (Dispatch Invitation Interest).

> About renaming BT-127, I don't see the need for the word "Publication"....isn't that the fate of any notice?

Guess the trick is that we're announcing a future, separate announcement, so “Publication” is on the other one.

**Comment by JachymHercher** [comment]
We have discussed this also at the [TED eSenders seminar](https://publications.europa.eu/en/web/esenders-seminar-2018/agenda) and all the reactions were in favour of simple semantics, even if the requires a few more BTs. Consequently:

- BT-135 (Direct Accelerated Justification) has been split into BT-135 (Direct Justification Text) and BT-1351 (Procedure Accelerated Justification). The descriptions have been changed accordingly. BT-135 has also been changed to non-repeatable, this was a typo. 
- From BT-145 (Contract Conclusion Date), we split BT-1451 (Winner Decision Date). The descriptions has been changed accordingly. Concerning legal status, BT-1451 is mandatory for CAN VEAT and CAN design and optional otherwise; BT-145 doesn't exist for CAN VEAT, is optional for CAN design and mandatory otherwise. 
- A similar split has also been done for BT-131 (Deadline Receipt Tender), see #173. 

Concerning BT-127 (Future Notice), we rename it to Publication Future Notice to have consistent descriptions and naming with BT-631 (Dispatch Invitation Interest) and other neighbouring BTs. (On one hand, it could also be argued that the fate of any invitation is to be dispatched, on the other hand, that there could be other information than the publication/dispatch. Let's just do it consistently.)
