### ISSUE TITLE
BT-40 seems unrightly placed under the BG-709 and its name is also to be checked

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#107]
As BT-40 is about criteria that are applicable to limit the number of candidates it should be part of the first step of a 2 step procedures, and so also seems unrightly named.

**Comment by JachymHercher** [comment]
That's a question of perspective: you are right in the sense that it is done _in the first stage_, but the definition is also right that it is a qualification _for the second stage_. 

From a practical point of view, I would say that grouping it in under BG-709 (Second Stage Criteria) makes sense, because the whole BG can then be applicable only for two-stage procedures.
