### ISSUE TITLE
BT-1376 definition is not very clear.

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#108]
I cannot understand what it relates to ... :-(

**Comment by tinne** [comment]
Did you understand the general purpose of lot-specific information and its representation? There is some discussion on it in #64.

Once you have defined lots, the other business group reference them by their ID (in database speech: contain a foreign key). Thus, BG-709 refers to the lot or lots given here if and only if BT-1376 contains a non-empty set of keys. Likewise, the other ”XXX Lot Reference“s refer to lots to give other specific information.

**Comment by guascce** [comment]
Thank you . 
Do you think that 'Second lot reference' has a meaning?

 As I understand what you want to express are information that appy to a specific lot in a second stage of a procurement. I would either call the element 'second stage lot reference' or only 'lot reference' as it belong to the Second stage group. 
Then I would also challenge the naming of Second stage but this will be in another issue.

**Comment by JachymHercher** [comment]
You are right, "Second Lot Reference" can be confusing, "Second Stage Lot Reference" is better. We will change it. (We use BT unique names regardless of context, so we'd like to make it more specific than "Lot reference".)

(Background: originally, we were trying to keep the BTs just to three words. This has turned out not to be possible, so going for four words for the sake of clarity is fine, I guess.)
