### ISSUE TITLE
CAN: logical problem with Review Bodies

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#111]
This is an issue I noticed separately from the Excel sheet. In current CAN it is mandatory to insert the name etc. of the Review Body. 

However, CAN is supposed to be filled-in after the contract has been signed. Hence appeals and reviews must have been dealt with already before. filling in CAN. Thus, it is useless to have the review body's data in CAN. It is only relavant in CN and in CAN **if** direct award has been used.

**Comment by tinne** [comment]
Seems to be obligatory due to Annex V Part (16) D 2014/24/EU, Annex XII (13) D 2014/25/EU and Annex VII (13) D 2014/23/EU, respectively (except for social and other special services, that is).

It is not easy to tell, however, why ”precise information concerning the deadline for review procedures“ is not equally mandatory.

**Comment by rantati7** [comment]
Mandatory or not but mistakes and lunacies should be corrected at some point - the sooner the better. I will start sending this information automatically to TED (via eSentool) and not bother the CAs any more with having to fill in this - it does not make any sense. At least in Finland.

**Comment by JachymHercher** [comment]
Prefilling this information automatically is of course the right solution (where possible because there is just one body or it can be figured out from the address/jurisdiction of the buyer). 

In general, the field should be in a CAN because, at least in some countries, complaints can be sent to review bodies also by other parties than just the participants in the procedure (e.g. in Czechia).  Since these parties are officially informed only through the CAN, including this information in the CAN makes sense. However, you are right it shouldn't be mandatory for all countries - we will reflect in the relevant business rules. (For BG-703 (Organisation) and BT-99 (Review Deadline Description.))

**Comment by rantati7** [comment]
Thanks!

Timo

Sent from my iPad

On 27 Jul 2018, at 19.44, JachymHercher <notifications@github.com<mailto:notifications@github.com>> wrote:


Prefilling this information automatically is of course the right solution (where possible because there is just one body or it can be figured out from the address/jurisdiction of the buyer).

In general, the field should be in a CAN because, at least in some countries, complaints can be sent to review bodies also by other parties than just the participants in the procedure (e.g. in Czechia). Since these parties are officially informed only through the CAN, including this information in the CAN makes sense. However, you are right it shouldn't be mandatory for all countries - we will reflect in the relevant business rules. (For BG-703 (Organisation) and BT-99 (Review Deadline Description.))
