### ISSUE TITLE
BT-64 (Subcontracting Percentage); Data type; percentage range? naming?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#117]
This business term is a bit confusing:
- According to the description, it should be called Subcontracting Min Percentage.
- According to Art. 21 (4) D 2009/81/EG, is should be a range of numbers `[ min, max ]`.

Why is it mandatory? Is it only relevant, when BT-65 (Subcontracting Requirements) contains a code w.r.t. this? Do the other codes in BT-65 refer to Art. 21 (2), (3), and (5), respectively?

**Comment by JachymHercher** [comment]
No problem with specifying it from "Subcontracting Percentage" to "Subcontracting Minimum Percentage". 

Article 21(4) doesn't clearly say that both minimum and maximum need to be included in the notice (cf. Annex IV, contract notices, point 9). However, you are right that it is legally cleaner to keep both. We note that in the history of defence contract notices, these fields were used exactly six times, out of which exactly two times the maximum limit was different than the maximum set in the legislation (30%). 

It is mandatory because it can be set to 0% - which means "no mandatory minimum subcontracting". It should not be linked to BT-65.

Yes.  (Roughly corresponding to II.1.7 of the current SF17).

**Comment by JachymHercher** [comment]
Small update: BT-64 as well as the new BT-729 (Subcontracting Obligation Maximum) have been changed from M to CM. The condition is that a certain code must be selected in BT-65 (Subcontracting Requirements). Concerning order, BT-65 has been placed above BT-64 and BT-729. 

In the description of BT-64 and BT-729, “is obliged” was replaced with “must”.
