### ISSUE TITLE
BT-542 (Award Criterion Number Meaning) / BT-543 (Award Criteria Complicated), Description; 

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#119]
Would ”order of provision“ be a sensible code for BT-542?

Reasoning: regarding more complex IT tenders, German public buyers are recommended to apply a two stage award method: first, quality criteria (in fact, non-cost non-price criteria) are used to used to select the best sellers, then in a second stage cost/price criteria are applied to select the most favourable under these best sellers (w.r.t. the selection of the first stage) only.

This method (Erweiterte Richtwertmethode) cannot be easily expressed by the current plain criteria/weight list. The question is whether an appropriate method could be recommended to the buyers using this method which does not involve BT-543's ”it's complicated.“

**Comment by rantati7** [comment]
I recon ypu mean sellers....

Sent from my iPad

On 1 Aug 2018, at 17.22, Karsten Tinnefeld <notifications@github.com<mailto:notifications@github.com>> wrote:


Would ”order of provision“ be a sensible code for BT-542?

Reasoning: regarding more complex IT tenders, German public buyers are recommended to apply a two stage award method: first, quality criteria (in fact, non-cost non-price criteria) are used to used to select the best buyers, then in a second stage cost/price criteria are applied to select the most favourable under these best buyers (w.r.t. the selection of the first stage) only.

This method (Erweiterte Richtwertmethode) cannot be easily expressed by the current plain criteria/weight list. The question is whether an appropriate method could be recommended to the buyers using this method which does not involve BT-543's ”it's complicated.“

**Comment by JachymHercher** [comment]
Just to make sure we understand: 
- Does this approach rely on minimal thresholds for quality criteria, under which a tender will not be taken into account for the whole evaluation? Or is there rather a quota, i.e. "top 3 highest according to quality criteria" are selected?
- Are we talking about a "two stage procedure" or rather a "two stage evaluation"? For a two stage procedure, we'd expect a tenderer to submit some new information in between the stages (like we have it in the restricted or negotiated procedure). For a two stage evaluation, we'd rather think that the buyer first excludes those who are under the minimal quality threshold and then evaluates, for the rest, the price criteria.

**Comment by tinne** [comment]
- The approach relies on a relative a-priori threshold. In the procurement documents, you announce a deviation factor _x_, which is multiplied to the highest quality offer _Z_, and every offer that falls short of that quality (is worse than (1-_x_)_Z_) is dropped. The procurement documents contain another criterion list which is then used to select the best seller, where price or cost must be a major factor component. In consequence, at least one offer will be considered in stage 2, but the exact number cannot be given in advance.

- We are talking about a two stage evaluation. This is independent from a participation competition, which may or may not precede.

To whom it may concern, cf. (in German): UfAB 2018 [Support Documents for Tender and Evaluation of IT Services 2018]. Procurement Agency of the BMI, Bonn, 2018. https://www.cio.bund.de/Web/DE/IT-Beschaffung/UfAB/ufab_node.html.

**Comment by JachymHercher** [comment]
Thank you, that's clear. When you say "The procurement documents contain another criterion list" would that be a "different" list or a "bigger" list?

If we can understand this as a two-stage evaluation with minimal thresholds (even if these thresholds depend on the received bids),  we would be inclined not to include it - simply because we find it too detailed for the notice. The criteria could be given using BG-38 , the fact that there is a threshold could be omitted. Alternatively, BT-543 could be renamed to something like Award Criteria Complicated Additional, so that additional information could be included in this BT as well.

(Alternative approaches could be to include an indicator of "There are some minimum thresholds.", a codelist of "Fixed minimum threshold / Relative minimum thresholds", a value field to give the fixed minum thresholds / text field to describe the relative ones...)

**Comment by tinne** [comment]
Rather a different list, with more focus on cost criteria, but this is buyer-defined.

Typically, the non-cost non-price criteria list is rather complex, while the formula for a ”total cost“ may consists of maybe ten summands only.

The minimum information I would expect to find in the notice would be ”a relative threshold based weighing method is used“ for the extended guideline method, ”a non-price versus price method is used“ (this would apply to the simple guideline method) or ”a pure price-based method is used“ and maybe two lists of non-price-based and cost-based criteria categories.

The threshold could be added, if necessary.

Comparing to your suggestion, I'm more in for the alternative approach.

**Comment by JachymHercher** [comment]
But the results of the first evaluation are still taken into account for the second evaluation, correct? Can't all the criteria then be represented as one "bigger" list? 

(Why I'm digging into this: we should validate whether, for example, the weighing of all criteria adds up to 100%. If there are two separate award criteria lists, this might not work / needs additional modeling. On the other hand, "bigger" is fine as it simply means that a subset of the criteria gets used in the first phase of the evaluation, another subset in the second).

Concerning the big paragraph in the middle, I'm not sure I fully understand, sorry. (I'm not sure what "guidelines" are?) Let's say there was an additional BT at the level of an award criterion, which would be a codelist, and for each criterion you could specify whether:
- "This criterion has a fixed minimum point threshold."
- "This criterion has a relative minimum point threshold. (The minimum depends on the submitted tenders.)"
- "This criterion does not have a minimum point threshold." 

Does that meet your (at least minimal) needs? What more would you consider necessary?

**Comment by tinne** [comment]
These lists are typically disjoint and focus on different points, as in ”prove that you are a valid seller for this subject“ in the first list and ”what exactly would you do to solve our problems at hand“ in the second. Also, they are trees of rather complex criteria than simple lists. Most of the time, they bring their own valuation model ”this answer will bring you a maximum score of 5 points, where you need to provide the following...“ with linear and all-or-nothing criteria ”you need to provide at least three people with the following skills...“

Regarding the big paragraph, ”extended guideline method“ is just the name of the method; translate guideline threshold.

The code list would meet the minimal needs. There should also be an indicator (or likewise) to denote that not every criterion is mentioned but rather a simplified summary list explaining the main criteria subjects.

**Comment by JachymHercher** [comment]
Most of what you write seems to fit within the current approach, correct? Maximum points (whether 1-5 or 0/5) are fine; trees seem quite ok as well - in the sense that just one level of the tree will be given (i.e. either a summary or the full details). 

I'm wondering whether the summary needs to be pointed out. The fact that a criterion may have also "sub-criteria" seems fairly innocent, so I'd be inclined to not go into it in the contract notice? 

(As an extension, we could also allow publishing the whole tree - e.g. by adding a "Parent Criterion" BT. Would you find that useful?)

**Comment by JachymHercher** [comment]
Ok, thanks. Concerning not adding up to a 1/100: that is not a problem, it just means that, using BT-541 (Award Criterion Number) for several criteria, the buyers will submit {50,50,50}. Whoever wants (the reader, potentially even the publishing website) can then do the math to see that this corresponds to 33%, 33%, 33%. Right?

**Comment by StHoh** [comment]
Buyers won't be able to submit concrete numbers at the time of publication. The described method is basically a slight deviation from a 50/50 cost/quality calculation. However, depending on incoming tenders the weight of either cost or cuality criterion can end up anywhere between 50 - ~ 55 percent and it is impossible to correctly calculate beforehand. 
Suggestion above ("as specified in procurement docs") would help solve the problem. 
Apologies for awkward language, this is difficult to explain even in native language.

**Comment by JachymHercher** [comment]
@StHoh No problem, thank you for the comment. From the forms point of view, I'm not sure whether there is a problem, because the criteria are optional in contract notices. So even if they were ocassionally not applicable, they wouldn't have to be filled in. (This is because according to the directives, they may instead be specified in the procurement documents.)

On the other hand, from the practical point of view, the weighing of the criteria should be set already when the call for competition is being published - so that the buyers know how they will be evaluated. (This is also reflected in the directive, see e.g. 2014/24/EU Rec. 90 "Contracting authorities should therefore be obliged to indicate the contract award criteria and the relative weighting given to each of those criteria.") 

I'm not sure I understand the 50/50 situation you are referring to. Is this linked to relative weighing? (E.g. when the real weight of criterion actually depends on the variation between the best and worst score for a given criterion) This is indeed not covered ex-ante - it only turns out when the bids are submitted.

**Comment by tinne** [comment]
> Those weightings may be expressed by providing for a range with an appropriate maximum spread.

The current forms cover this information (of art. 67 (5) sentence 2 of D24 and their like) in form of a range (in the form of two numbers min-max) which may be given instead of a single weight number.

When examining this part of the eForms data model first, I noted ”range dropped, ok.“ Whenever a buyer gave one of these ranges, they were never really precise in the sense of machine processable relations, thus to give BT-541 the meaning minimum relative weight and having the maximum relative weight in the Description (BT-540) would not be a total loss in statistical empowerment, but might make the description text read a bit awkward.

The whole sort of weighting works with both absolute and relative weighing, since absolute weighting is just relative weighing with a total of 1 (or 100%).

**Comment by RolfKewitz** [comment]
Isn’t there a chance to provide a flag indicating that there will be more details in the procurement document concerning the exact methods used and the exact formula?
From my point of view the reader of a contract notice should know if the offered information is only an indication of the criteria that will be used and not the exact award criteria. Therefore I would suggest to provide a flag indicating that there will be more details in the procurement document concerning the exact methods used and the exact formula (if the formula of the award criteria does not fit into the scheme which may happen especially in Gemany).
This seems to be an improvement of transparency within in the contract notice compared to the current situation where there is a flag in the current contract notice saying “_o  Price is not the only award criterion and all criteria are stated only in the procurement documents_” which allows to publish no details at all within the contract notice.

**Comment by JachymHercher** [comment]
@tinne concerning the range, the directive indeed gives this option for the award criteria stated in the procurement documents, but the forms may be simpler. We were considering an approach of BT-542 having a value "middle of a range" (not "minimum of a range"). 

@RolfKewitz we would think that this is the purpose of BT-543 (Award Criteria Complicated) - if it's too complicated for the structured data, then the user can explain it in this field. (In theory, he could also write "The criteria are more complicated than stated above, see procurement documents", but ideally the notice could contain all the relevant information.) Would you say this is enough?

**Comment by RolfKewitz** [comment]
I agree.

**Comment by tinne** [comment]
Summing up, BG-38 Award Criterion should consist of single items
- Award Criterion Type (Code)
- Award Criterion Description (Text)
- Award Criterion Number (Number)
- Award Criterion Number Meaning (Code)
- Award Criterion Significance (Code)
- Aggregate Award Criterion (Indicator)

The description of Aggregate Award Criterion would be “the award criterion summarises several criteria explained in the procurement documents.”

The Award Criterion Number Meaning should also contain the meanings (in addition to the meanings mentioned in the original description):
- Medium Relative Weight (the weight is an interval documented in the procurement documents)
- Exact Relative Weight

The Award Criterion Significance code list would contain
 -This criterion has a fixed minimum point threshold.
- This criterion has a relative minimum point threshold. (The minimum depends on the submitted tenders.)
- This criterion does not have a minimum point threshold.

In evaluation, 
1. the buyer would calculate and aggregate the Aggregate Award Criteria as explained in the procurement documents. 
2., she would first consider all fixed threshold based award criteria and decide whether all fixed threshold criteria are met. 
3. a relative evaluation would be applied to the remaining tenders taking into account all relative minimum point threshold criteria. The best _n_ would be kept (_n_ being documented in the procurement documents).
4. all remaining non-threshold criteria would be applied to select the best offer.

**Comment by JachymHercher** [comment]
@tinne Generally we agree, but a few comments below: 
- Aggregate Award Criterion (Indicator) - as discussed above, we suggest not including this, as the benefit of having this information as structured data is not that clear and similar information can be provided in Award Criteria Complicated.
- Concerning the codelist for Award Criterion Number Meaning, we would suggest the codes of:
    - Weight (exact)
    - Weight (middle of a range) 
  
   Why would you add "relative"?
- Award Criteria Significance we would suggest calling Award Criteria Threshold. 

    However, we're still wondering: wouldn't it be better to change BT-541 (Award Criterion Number) and BT-542 (Award Criterion Number Meaning) to repeatable; add the codes "Minimum point threshold (fixed)" and "Minimum point threshold (relative)" to BT-542 and then declare the thresholds explicitly, including their value? This would be more informative while not requiring an additional BT. 

The evaluation description sounds good.

**Comment by tinne** [comment]
- Aggregate Award Criterion (Indicator) - OK to pass on it in favour of some appropriate Award Criteria Complicated text
- The code list should include
  - Weight (exact) - instead of percentage, which would suggest a fixed weight sum which can be derived for displaying reasons
  - Weight (middle of a range)
  - Weight threshold (exact)
  - Weight threshold (middle of a range)
  - Maximum number of tenders passing (regarding a relative threshold)
- This group would include numbers which order the criteria with regard to others (weight, order) and numbers within the criterion (tender number, weight threshold) where a criterion can have both. As discussed, this could be a proper modelling. If there are only these two relevant numbers, maybe give two numbers and two codes separately. The weight and weight threshold codes, as given above, could then be merged.

With regard to the evaluation description, in step 3 of https://github.com/eForms/eForms/issues/119#issuecomment-425455651 the figure _n_ would be given explicitly in the notice (number with code Maximum number of tenders passing) and no reference to the procurement papers would be necessary.

**Comment by JachymHercher** [comment]
We will prepare the codelist with @muricna. We will open this in a different issue / present it together with the next version of the spreadsheet. 

Concerning the BTs, we put BT-541 and BT-542 into a new repeatable BG-541 called Award Criterion Number.

**Comment by paulakeen** [comment]
The mapping between eForms and ePO, in respect of the Award Criterion Number Meaning (BT-542) and Selection Criterion Stage Number Meaning (BT-753) goes as follows:
-	In the class Criterion the weight is a Numeric data property (attribute). This number is categorised (typified) using the code list “weigh-type” (e.g. weight (percentage exact), weight (percentage middle of a range), etc.). 
-	Complementary to the weight number (as explained above) we have a “threshold value” in the classes “Selection Criterion” and “Award Criterion”, which goes along with a “threshold-type” code that uses the code list “threshold-type”. This “threshold-type” code list is therefore associated to both classes and eForms should consider using this code list. The “Selection Criterion” would this code list for the second stage selection of candidates. 
-	Additionally, for award criteria, we have a data property (attribute) in the class “Award Criterion” named “Threshold Value” cum the attribute “price-threshold-type”. 

To avoid misuse of the of semantics of the codes and to ensure interoperability and reusability, it would be advisable that eForms adopts these code lists rather than amalgamating the three code lists into a single one.

See the ePO diagrams below:
![image](https://user-images.githubusercontent.com/16134316/55015081-79738200-4fec-11e9-9b22-520b81f8f87e.png)

![image](https://user-images.githubusercontent.com/16134316/55015121-9019d900-4fec-11e9-83a9-adb7d3fb09cb.png)

**Comment by JachymHercher** [comment]
Thank you for the overview. Splitting the codelist into three is probably a good idea. Few clarifying questions, though: 

1) Why do you use a separate class for "Award Criterion Evaluation Dimension" (ACED)? Assuming that ACED has 1-1 relationship with Award Criterion (AC), the attributes could simply be in AC. Things would be simpler and in my opinion also clearer. 
2) "Price-cost-threshold-type" is in my opinion not about thresholds, but rather about fixed price (which is something else than a threshold and something else than a weighing). I would suggest renaming it to something like "Fixed" or "Price-Cost-Fixed". (The former sounds more reusable.) 
3) Regardless of 1), "Fixed value" should be in AC, not ACED, no? 
4) Isn't "Threshold" in ACED a duplication of "Threshold value" in AC? 
5) Isn't "Weight" in ACED a duplication of "Weight" in Criterion? 
4) Doesn't "Selection Criterion Type" miss a corresponding "Type" attribute in "Selection Criterion"?

**Comment by paulakeen** [comment]
Please see my comment in the ePO Issues workspace: https://github.com/eprocurementontology/eprocurementontology/issues/203.

**Comment by paulakeen** [comment]
Dear @JachymHercher,

Let me respond to the enumeration of observations in your [comment ](https://github.com/eForms/eForms/issues/119#issuecomment-476758963) above:

1. In the latest version of the ePO we do not have the class "Award Criterion Evaluation Dimension" anymore. This change is aligned with your idea that what we understand as "dimension" is just another criterion (i.e. a kind of super-criterion that is linked to a set of subcriteria that are all related to price, quality or cost). In the new model, the way of specifying that a criterion is  "a dimension of" a set of criteria is the following:

* The criterion that "is a dimension of" is associated to "sub-criteria". Thus, all the criteria that are related to the "price", for example, are sub-criteria of a criterion that is defining our concept of "dimension";
* This criterion (let's call it the "dimension criterion") has also weight, weighting consideration description, formula, etc. , as any other criterion;
* Each subcriterion of the "dimension criterion" must realise (instantiate) the property "subcriterion type" and indicate that it is of type "price" ("quality" or "cost"). For this ePO proposes the code list "award-criterion-type", and it is applied at the level of the class "Criterion", not at the level of the class "Award Criterion". This is so because we considered that other types of subcriteria will need this feature related to the specification of the type of relation between criterion and its subcriteria (e.g. the ESPD needs this to differentiate what is a European Exclusion Criterion from what is a national subcriterion exclusion ground).

This can be seen in the diagram below (which corresponds to the latest ePO analysis):

![image](https://user-images.githubusercontent.com/16134316/59781487-2c860b80-92bc-11e9-921d-519edba81b6b.png)

**Comment by JachymHercher** [comment]
@Paulakeen thank you for the information. As requested in https://github.com/eForms/eForms/issues/119#issuecomment-456823906, the codelist for thresholds has been separated from the rest. Together with the discussion in https://github.com/eprocurementontology/eprocurementontology/issues/203, it seems that we've clarifid all the points on the alignment between the criteria in eForms and in the ePO.
