### ISSUE TITLE
BT-520 (Additional Information Contact); Description; Communication means

### ISSUE THREAD

**Issue by AlesMMR** [eForms/eForms#125]
What kind of contact do you mean? In CZ law is stated that the comunication can be via mail, e-tool, phone etc.
We do not thing we can limit way of communication only for mal and internet address. BG-703 contain of many contact of organisation which can supplier use to send request for additional info. 

Don't you think that BG-703 enough? As general contacts on buyer.

**Comment by JachymHercher** [comment]
You are probably right. We intended BG-703 to be the default way, with BT-08 (Organisational Role) codelist having a role of something like "Contact Point for Additional Information".  

However, BT-520 was intended to be kept for cases such as limiting the means of asking questions (e.g. "Don't use email, only ask questions using our e-tendering platform"). It is true though, that if M is changed to CM for all BTs in BG-703, then this use case could also be met by BG-703. (By submitting BG-703 only with, for example, "Organisation Internet Address" and "Organisation Role".)

I will double-check this during today's webinar (since BT-520 is on the agenda) and if there are no other views, we can remove BT-520 and do the necessary changes in BG-703.

**Comment by JachymHercher** [comment]
As discussed in #159, BG-100 (Communication) can differ per lot. Thus, if the contact point(s) are given via BG-703, as proposed above, then there still needs to be a BT indicating which contact point applies for which lot. 

This can be done by renaming BT-520 to "Additional Information Reference", changing the data type to identifier and the definition to "A reference to the identifier of an organisation (or organisations) for requesting additional information about the procurement procedure." (This definition is phrased similarly to those of BT-1701 (Winner Organisation Reference) and BT-713 (Contract Buyer Reference).)
