### ISSUE TITLE
BT-26 (Classification Type) /BT-262 (Main Classification Code) / BT-263 (Additional Classification Codes); Description; In case of mixed procurement the need to use only CPV codes defined in BT-23

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#136]
I learned about this change in the TED schema today (29.8.2018).

In cases of mixed procurement with the TED schema update that we are implementing in Finland next week it is no longer possible to select CPV codes from other area for BT-263 (Additional Classification Codes). If the CA selects in BT-23 the type (supplies, services or works) the CPV code in the MAIN must be from the same section of CPV codes. This makes sense. BUT now also the additional CPV code (BT-263) must be also from the same section of CPV codes.

I do not think this is a good policy. Nor is this good procurement. Very many procument are nowadays mixed. Particularly supplies include often services but services can also include supplies. It has been a common practice to add e.g. services in BT-263 field when the main CPV code is from supplies. This change also affects the suppliers negatively - they may not find the relevant notices after this change. 

There will be a lot of objections to this in Finland - but only after the change... We have notified the CAs on this but they usually wake up only when the changes have already been done.

**Comment by tinne** [comment]
I learned about the change when I was analysing the schema update to revision 2.0.9.S03 this February. It then came as a bit of surprise when the additional warning (rule R117) was introduced not with the new schema but even for 2.0.9.S02 documents and earlier than the 2.0.9.S03 go live. The support staff was not particularly amused by the unexpected additional amount of warning e-mails they had to handle.

**Comment by maarikatork** [comment]
Sentool validation rules (valid) state the following:
 R117	Warning	Warning	true	Presence of CPV code(s) inconsistent with the contract type: supplies corresponds to CPV code starting from 0 to 44 and with 48, Works with 45, Services from 49 to 98.

In Estonia, however, we recently received such a warning:
[R117] Found incorrect CPV: 2: Presence of CPV code(s) inconsistent with the contract type: supplies corresponds to CPV code starting from 0 to 44, Works with 45, Services from 48 to 98.

We asked about it from TED helpdesk and the answer was they had been told that CPV code 48 was now associated with services. If such an important change in this concept has been made it is not understandable why validation rules or CPV code explanatory notes have not been changed? 

However, the topic raised by Timo about the need of additional codes be the same as the main CPV code we are not aware of.

Could you look into it again. CPV code 48 has alwas been associated with supplies rather than services. At least we have set the automatic controls this way in our system.

**Comment by rantati7** [comment]
@maarikatork  this is what our developers reported to me. I will ask them to review this again. This is not good....

**Comment by maarikatork** [comment]
I asked our developer and yes, @rantati7 is right about mixed procurements. The warning is there. This is definitely something to reconsider..

**Comment by JachymHercher** [comment]
For eForms, our intention is to have a business rule that BT-262 (Main Classification Code) must correspond with BT-23 (Main Nature) and BT-263 (Additional Classification Codes) must correspond with BT-23 (Main Nature) or BT-531 (Additional Nature). (In the current schema, BT-531 does not exist.)

Concerning the current schema, we are very grateful for the feedback, but please note that this GitHub is not the best platform to submit issues on this matter. Nevertheless, I'm sure @annalisavacca can provide some reaction here or point you to the right communication channel. From my side:
- I agree that under the current schema, the CPV-Works/Supplies/Services matching should hold only for the main CPV code, not the additional one.
- I think we've made an error on the CPV validation rules. Indeed, division 48 should fall under supplies (see e.g. point I of the CPV Explanatory Notes available at https://simap.ted.europa.eu/cpv). 
- (Concerning software, I'd say it could be defined as a supply (e.g. a boxed Windows OS) or a service (e.g. developer man-hours) depending on what exactly is being purchased. But this is rather a lawyer's discussion.)

**Comment by Annalisavacca** [comment]
Recently, we have added rule R117, which checks the consistency between the type of contract (works, supplies, services) and the range of CPV codes corresponding to these contract types.
Supplies correspond to CPV code starting from 0 to 44 and with 48, Works with 45, Services from 49 to 98.
The rule is currently with a "warning" weight, so that the notice has not been rejected.
Please note that the rule has been corrected in the new version of schema/rules R2.0.9.S03. 
R2.0.9.S02
RULE="R117" Presence of CPV code(s) inconsistent with the contract type: supplies corresponds to CPV code starting from 0 to 44, Works with 45, Services from 48 to 98.
R2.0.9.S03
RULE="R117" Presence of CPV code(s) inconsistent with the contract type: supplies corresponds to CPV code starting from 0 to 44 and with 48, Works with 45, Services from 49 to 98."
So please remind to upgrade your XML to the latest version R2.0.9.S03 as soon as possible (latest deadline 28/09/2018).
Next week the rule will be again updated and “R117: Presence of CPV code(s) inconsistent with the contract type: supplies corresponds to CPV code starting from 0 to 44 and with 48, Works with 45, Services from 49 to 98” will become “R388: S2-01-02: Main CPV code inconsistent with the type of contract: Supplies corresponds to CPV code starting from 0 to 44 and with 48, Works with 45, Services from 49 to 98”.

**Comment by Annalisavacca** [comment]
****
