### ISSUE TITLE
BG-320 (Winning Tender); Description; Unit price

### ISSUE THREAD

**Issue by AlesMMR** [eForms/eForms#137]
We would like to add the possibility to fill in value of contract in unit price. In CZ there are many contract based on unit price, e.g. labour offices procure almost all contracts based on hourly wage and these offices are not in possition to count total price for 4 years.

**Comment by JachymHercher** [comment]
Unit prices are a complex topic and we've tried approaching it in several ways in eForms. To be sure we understand correctly, we have some clarifying questions:
- as long as some elements are uncertain (e.g. number of hours), then these contracts should qualify as framework agreements. In that case, the buyer would submit only BT-709 (Maximum Value) in the first contract award notice and BT-720 (Winning Tender Value) would be published only in the later contract award notices - once the purchases have been made.
- if the contracts are not framework agreements, i.e. all the factors are known, then the price x hours should be possible to calculate. 

Can your needs be met by one of the two situations above? If not, could you please provide a more detailed example so that we can see how to model it better?
