### ISSUE TITLE
BT-13714 (Winning Lot Reference); Data type / Repeatable / Description; Denote lot group / several lots

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#138]
In today's WebEx, we were discussing whether a BG-320 (Winning Tender) section might also refer to more than one lot by giving more than one Winning Lot Reference or a Group Identifier (cf. BT-330) denoting a Group Award section.

The argument was that a tenderer might have bidden for more than one lot and this bid might have been (in the case of Group Awards) connected to all lots in the bid awarded to this one single seller. Also, in this case, there would be a Winning Tender Value (BT-720) for the lot group only, so a per-lot valuing might be rather synthetical.

It might also provide transparency for losing bidders regarding why they bid would not have been ranked better than the winning bid. @JachymHercher argued that this might a subject to a future extension which allows Contract Award Notices to be used as seller selection reports sent to all participants of a tender upon closure.

**Comment by JachymHercher** [comment]
You are right: when BG-330 (Group Award) is used, in some cases, there might not be any explicit lot value. This is likely to happen very rarely, but still, if we can model it (reasonably simply) we should try. It seems we could cover it by adding "or a group of lots" to the definition of BT-13714 

> A reference to an identifier of a lot **or a group of lots** within the procedure.

This means there are currently four types of lot references (also interesting for @muricna):

a. Repeatable lot references (all except those below)
b. Unrepeatable lot reference (BT-13713 Lot Reference)
c. Repeatable lot or group reference (BT-13710 Award Criteria Lot Reference)
d. Unrepeatable lot or group reference (BT-13714 Winning Lot Reference) 

In my opinion, in case d), "group of lots" could be replaced by repeatable lots and, with the help of business rules (taking in account BG-330), this wouldn't cause any problems. However, for c), the reference actually needs to be to a BT-330 (Group Identifier), because otherwise an ambiguity could occur: if there was a group of five lots, then there could be two BG-38 (Award Criteria) referring to five lots and it wouldn't be clear which one sets the award criteria for each individual lot and which one for the group of five lots. Would you agree?

**Comment by tinne** [comment]
Maybe it may help to ease data modeling by generally refer to single lots or single lot groups as follows:
- rename BG-330 Lot Groups
- add an non-repeatable indicator Group Award Allowed to BG-330

A group award lot group is a BG-330 section with Group Award Allowed true. Any other grouping of lots has Group Award Allowed set to false.

Now, turn both BT-13710 and BT-13714 into non-repeatable Identifiers referencing either a lot or a group. The ambiguity stays away.

Did I missing anything?

Note: for the sake of disambiguation, BT-13713 should perhaps be renamed Result Lot Reference.

**Comment by JachymHercher** [comment]
Renaming BG-330 could be useful. However, I'm not sure "Lot Groups" is sufficient, because that could in theory also refer to the other lot groups - BG-556 (Group Maximum Value) and BG-557 (Group Estimated Maximum Value). "Grow Award" was chosen so that the name also reflects the purpose.

I'm sorry, I'm not sure whether I understand the proposal. Could you perhaps add an example? Do you suggest that "several" lots could be referred to in three ways (listed below), or just two (the second item replaces the first item) - in which case BG-330 would define groups to be used all over the notice? 
- listing three lots (e.g. in BT-1372 (Place Lot Reference))
- referring to a lot group with Group Award Allowed = false. 
- referring to a lot group with Group Award Allowed = true.

**Comment by tinne** [comment]
The proposal was towards in case there is any section regarding lots 1,4, and 9, give them a name Group Identifier theSquareLots and handle them by that name whenever they are used. Set Place Lot Reference theSquareLots to describe the public square where 1, 4, and 9 shall be performed. Set Duration Lot Reference to theSquareLots to tell people these three lots will last a quarter year each. Set Funds Lot Reference to it to tell they all go under the Public Square Dance Funds.

Now, if you accept special prizes if a single seller offers you all squares in a piece, set Group Award Allowed to true. Set Winning Lot Reference to theSquareLots to tell the public that they probably gave us a special prize for the bundle. Set it to another Lot Groups group identifier with 1, 4, 9 being members to denote that they just won the three lots (and you put them in one contract) without any bundling considered.

**Comment by JachymHercher** [comment]
Now I think I understand, thank you. Allow me to summarize: 

Identifiers of lots and their groups are "created" in two places: BT-137 (Purpose Lot Identifier; e.g. "L1") and BT-330 (Group Identifier, e.g. "G1"). Business rules assure that all of these identifiers are unique. 

Aiming for good technical implementation and simplicity, we have two options:
1. By default, refer to one or more lot identifiers. For BT-13710 (Award Criteria Lot Reference) and BT-13714 (Winning Lot Reference), also allow referring to group identifiers. 
2. By default, refer to one lot or group identifier. Whenever multiple lots are to be referred to, they should have a Group Identifier. Additionally, there should be a new BT "Group Award Allowed" which specifies that this group can have their own award criteria and may be bid on. 

Both options seem workable, but I must say option 1. seems simpler to me. Mainly for two reasons: explicitly declaring any repetable lot identifiers as a group sounds heavy (esp. since they do not have to be linked in substance such as a square would, but can just happen to have some similar attributes such as being paid from EU funds or have the same duration); being able to refer to groups is relevant only in one/two places (award criteria/winning tender).  

(A point could also be made that this is mainly too technical to be dealt with in the regulation, but I'm not sure how to formulate it more generally.)
