### ISSUE TITLE
BT-411: Purpose Procedure Reference: the same a procudure identifier?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#14]
Isn't this the same number as "procedure identifier" in BT-04?

**Comment by JachymHercher** [comment]
Essentially yes - it's a reference to the identifier in BT-04. These references are included at the beginning of every BG that can apply to different procedures within a single notice (only a PIN only can inform about multiple procedures). This is necessary so that it is clear which procedure the BGs/BTs apply to. Besides BT-411, these references are also BT-412 (Techniques Procedure Reference), BT-413 (Communication Procedure Reference) and BT-714 (Additional Information Procedure Reference). 

We seem to have a mistake concerning BT-411: the same ID is accidentally used for several business terms ("Place Procedure Reference", "Duration Procedure Reference", and "Selection Procedure Reference"). We will correct this.

**Comment by JachymHercher** [comment]
Following the discussion in #55, we have decided to remove multiple-procedure PINs. As a result, we have removed also the BTs mentioned above, because they are no longer necessary.
