### ISSUE TITLE
BT-115 (GPA usage); New field; procedure level

### ISSUE THREAD

**Issue by manevmi** [eForms/eForms#140]
The GPA usage/coverage must be at procedure, not lot level.

This follows the principle laid down in Article 5 of the Public Procurement Directive that the Directive (with which the EU transposes its obligations under the WTO GPA) applies to each lot where the aggregate value of the lots equals to or exceeds the Directive thresholds. 

A different interpretation, i.e. where it is the value of the individual lot to be taken into account for the GPA coverage, would create a risk of contracting authorities dividing the procurement into lots with the intention of totally or partially excluding it from the application of the GPA – something which is prohibited under Article II(6) of the GPA agreement . The latter states explicitly that to establish whether a procurement is covered by the GPA or not, the contracting authority must include the estimated maximum total value of the procurement over its entire duration, whether awarded to one or more suppliers.

As pointed out by prof . Sanchez-Graells in his book "Reformation or deformation of EU Public Procurement Rules" the EU policy of promoting lot splitting to facilitate SMEs participation would contravene the EU obligations under Article II(6) GPA agreement if there would be no rule for aggregating the value of the split lots for the purposes of the applicability of the Directive and the GPA.

**Comment by JachymHercher** [comment]
@manevmi, we agree with your point on the value - it is indeed the value of the whole procedure that is important from the point of view of the applicability of the EU Directives and the GPA, not the value of the lots.

At the same time, GPA coverage does not depend only on the value, but also on who buys and what is being bought (see e.g. [here](https://e-gpa.wto.org/en/Annex/Details?Agreement=GPA113&Party=EuropeanUnion&AnnexNo=4&ContentCulture=en&AdvancedSearch=False)). Since what is being bought can differ from lot to lot, we find it more accurate to include the indicator at the lot level. Does this make sense? 

(Just to make sure we understand each other: for example, if a procedure is above-threshold but a lot itself would be below-threshold, the lot should of course still be marked as applicable under the GPA - as long as it is the right type of purchase by the right type of buyer.)

@tinne, this is not necessarily over-interpretation, we do try to use the word "procedure" only when it is about the procedure.
- You are right concerning BT-715, BT-725, BT-716 (the BTs on vehicles). We will remove "in this procedure". 
- BT-115 (GPA Usage) seems ok the way it is - it refers to the neutral "procurement". 
- We will review BT-116 (Outsourced Procedure), also in the context of #42 and #85. 
- The same problem seems to exist also with BT-06 (Strategic Procurement). We will change "procedure" to "procurement".

The analogy with BG-02 is correct, but we would be inclined to think that all of the BTs in the group are relevant at the lot level.

**Comment by JachymHercher** [comment]
No problem, happy to! 

The spreadsheet does not really set that in stone (same situation as in #141). However, if it is given at lot level it is probably not necessary to specify it at the procedure level. Instead, when judging whether the lot is covered by the GPA, the buyer must take into account all three factors: whether the procedure is above threshold, what category of buyer he falls into, what he is buying.
