### ISSUE TITLE
BT-710 (Tender Value Lowest); Description; Definition

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#145]
If a tender is excluded due to abnormally low price or cost, will it still be reported as the lowest value of tender? Or is it the lowest value of tender given it is not excluded and it fulfills all conditions to participate in the procurement procedure?

**Comment by JachymHercher** [comment]
Good point. Since the goal of BT-710 (Tender Value Lowest) and BT-711 (Tender Value Highest) is to offer an approximation of the contract value, we would be inclined to use the second approach. 

This could be solved by changing the definition of both fields by replacing "tender" with "non-excluded tender". Would you agree?

**Comment by manevmi** [comment]
I agree it should be the second interpretation.

Why not use the term "admissible tender"? After all, this is the term used in the PP Directive to grant requests for information to unsuccessful tenderers.

**Comment by tinne** [comment]
If the law is clear, why not use the term used there, “highest tender and lowest tender taken into consideration.” (An. V P. D (13) D24) If that is unclear, maybe this should be corrected as well.

**Comment by JachymHercher** [comment]
Both "admissible tender" and "taken into consideration" are used in the directives, but neither is used too frequently and in our opinion we need more to ensure that they are understood the same way everywhere. After some discussions with colleagues, we would suggest adding:   

"taken into consideration (i.e. not excluded because of technical reasons, exclusion grounds, selection criteria, an abnormally low price)". 

(For the purposes of BT-710, I would interpret the line above literally, i.e. if some tenders were not checked for exclusion, they were "taken into consideration".) 

(This discussion is closely linked to #146.)

**Comment by ognyami** [comment]
The above description "taken into consideration (i.e. not excluded because of technical reasons, exclusion grounds, selection criteria, an abnormally low price)" still does not capture several situations in which offers will not be ranked:
- tenders submitted after the deadline;
- tenders not meeting minimum requirements;
- in case of award based on best price/quality ratio - tenders not passing the quality threshold set (if any) (or maybe this will be covered by the phrase "exclused because of technical reasons" - the phrase is however very ambiguous).
Wouldn't the following definition be more comprehensive: ""taken into consideration (i.e. admissible tender - tender that has been submitted by a tenderer, who has not been excluded and who meets the selection criteria, and whose tender is in conformity with the technical specifications without being irregular or unacceptable or unsuitable)"?

**Comment by JachymHercher** [comment]
@ognyami, good point. Also, what we wrote in https://github.com/eForms/eForms/issues/145#issuecomment-424996925 was probably not the best solution. Indeed, as @manevmi writes, using "admissible" is the best approach, because it is explained in the directives in some detail (2014/24/EU Art. 35(5), subparagraphs 2,3,4) while "taken into consideration" is not. We thus suggest the following definition: 

"Value of the admissible tender with the _lowest/highest_ value. A tender shall be considered admissible where it has been submitted by a tenderer, who has not been excluded and who meets the selection criteria, and when it is in conformity with the technical specifications without being irregular (e.g. received late) or unacceptable or unsuitable." 

("Admissible" is used also in #146.)
