### ISSUE TITLE
BG-137 (Procedure Lot Result); New field; Suggested additional information: Number of tenders received that were excluded and the reason for exclusion

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#146]
Submitting deliberately erroneous bids is a widely used indication of bid rigging. Therefore we suggest that data on the number of tenders that are excluded and the firms that have submitted such bids is collected.

**Comment by JachymHercher** [comment]
This could be valuable also from the point of administrative burden and difficulty to pass the formal requirements of procurement. Anecdotally, we are aware that companies are excluded from procurement for incorrectly filling in the administrative information. It is a question whether it should be a mandatory or optional field. 

May I ask how are erroneous bids used in bid rigging?

**Comment by karinmorild** [comment]
A widely used collusion technique in public procurement is that firms mimic competition by submitting non-competitive bids (a competing firm agrees to submit a bid that is too high or contains terms that are unacceptable to the buyer). 

Collecting such data enables us to calculate the prevalence of faulty bids: the ratio of faulty bids to total submitted bids. On markets where the prevalence of faulty bids suddenly increases, it can be suspected that companies concluded a collusive deal.

**Comment by manevmi** [comment]
If we are to collect the number of excluded tenders, it must be clear that this concerns only the exclusion grounds under Art. 57 PP Directive. Submitting deliberately erroneous bids can be reported as exclusion ground if the contracting authorities have sufficient indications that this  is part of anti-competitive agreements (Art.57 (4) (d)). In this case we will collect directly (with the contract award notice) data on collusive practices per procedure.

From a practical perspective it is not realistic that such data will be reliable:
- deliberately erroneous bids are difficult to identify (how can you be sure that it is not really a clerical error?) and given the uncertainties, the adm. burden (exclusion on this ground requires a contradictory procedure) and risk of legal challenge, contracting authorities will try to avoid excluding a tender on this ground, especially if they would have obligation to report such an exclusion in contract award notice.
- if the contracting authority checks first the selection or award criteria and the deliberately erroneous tender fails there, the tender will be rejected from the procedure but not excluded for anti-competitive behaviour and, therefore, not to be reported in the contract notice as excluded. So the ratio "faulty to submitted bids" will not be reliable.

**Comment by JachymHercher** [comment]
@manevmi, I would agree that collecting data directly about collusive practices is not realistic. However, @karinmorild original proposal of counting all excluded tenders (for any reason, or at least that's the way I understood it), sounds possible. 

The field could be called "Received Tenders Excluded" with a definition of "Number of tenders received that were excluded (e.g. because of technical requirements, exclusion grounds, selection criteria, abnormally low price or cost)."

Is this what you had in mind?

**Comment by manevmi** [comment]
We might be talking about different things. 

Under "excluded" I understand only those in an exclusion situation under Art. 57PP Directive, not any tender that has been discarded on any other reason (e.g. technical non-compliance, selection criteria). If we include also these in the "excluded", then this will cover almost all unsuccessful tenderers (probably the only unsuccessful tenderers not "excluded" will be those not ranked first based on the award criteria).

What would be the reason for collecting data on such a broad range of exclusions? It will hardly be useful to detect anti-competitive behaviour...

It might be useful to see if there is real competition for a contract - something which cannot be concluded from the number of submitted tenders: if we receive 10 tenders but 9 of them are excluded/rejected/discarded on exclusion/selection/technical compliance, we have no competition in practice.

**Comment by ognyami** [comment]
With the new PP Directives the exclusion, selection and award criteria may be evaluated in any order. If we apply the lowest price as an award method (used in a very high proportion of all procedures), we will check the compliance with the exclusion and selection criteria and with the minimum requirements only of the offer with the lowest price. If there is no ground to exclude/reject it - we will award the contract to the lowest bid, without checking the other tenders for exclusion/non-selection/non-compliance. If there was bid-rigging, it will be reflected in the prices (the other bidders submitting artificially high prices), but we will not capture this by simply putting a zero in the field showing the number of "excluded" tenders. 
As a conclusion - given the possibility for the contracting authority to evaluate different types of criteria in any order, I do not see the added value in the extra field.

**Comment by JachymHercher** [comment]
Very good point @ognyami about not all tenders being necessarily checked for exclusion. I'm not sure that abandoning the field is the only / best solution though. There are several others options: 

1. If not everything was checked, leave the field empty. 
2. Assume that what was not checked was valid. (That's the approach suggested in the related case of #145.)
3. Add another BT on "Number of tenders which were not checked for exclusion"

The last option requires extra input, but is the most precise. The other two may introduce bias when using the field for measuring collusion or administrative burden stemming from frequent exclusions, because a part of the results would be missing. It's also worth keeping in mind that these proportions would be very different country to country and sector to sector, depending on how often award criteria are evaluated before other criteria and the only criterion is the price.

What do you think?

**Comment by ognyami** [comment]
My first choice is still to omit the field, but if it is to be kept I would suggest the following title/description:
The field could be called "Received Tenders Non-admissible" with a definition _"Number of tenders received in accordance with the submission modalities that are non-admissible - i.e. tenders **for which it has been verified** that: they are submitted by a tenderer, who has been excluded or who doesn't meet the selection criteria, they are not in conformity with the technical specifications or they are irregular or unacceptable or unsuitable."_
If when evaluating the criteria in any order we skipped a check (if the tenderer must be excluded, non-selected etc.), we will not know if the tender is non-admissible (i.e. this has not been verified) and we will put a zero in the number cell.

**Comment by JachymHercher** [comment]
Thank you for the comment. After some further reflections, we will suggest:
- A new field called "Received Tenders Inadmissible" with a definition of "Number of tenders received that were found inadmissible. A tender is found inadmissible where it has been verified that it has been submitted by a tenderer who has been excluded or who did not meet the selection criteria, or when it is not in conformity with the technical specifications, or is irregular (e.g. it was received late), unacceptable or unsuitable."
- A new field called "Received Tenders Unverified" with a definition of "Number of tenders received for which it has not been verififed if they are admissible or inadmisisble (e.g. because award criteria have been evaluated for all tenders and admissibility is checked only for the winning tender)." 

("Admissible" is discussed also in https://github.com/eForms/eForms/issues/145#issuecomment-436934876.)
