### ISSUE TITLE
BG-180 (Subcontracting); New field; Suggested additional information in CAN: Subcontractor and subcontractor’s share of contract

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#148]
Subcontracting is a commonly used instrument for rent sharing among colluding firms. An increased share or amount of subcontracts can reveal a structural change of a given market that can be connected to collusive schemes. We therefore suggest that data on the firm name and ID of subcontractors are collected as well as the share of the project that they are contracted for.

**Comment by JachymHercher** [comment]
We agree that this information could be relevant (from both a collusion discovery point of view and for adding more transparency on potential conflict of interest). 

However, subcontracts are often not yet known when the procurement contracts are awarded. Since the information is incomplete, we are wondering whether the contract award notice is a good place to include this information?
