### ISSUE TITLE
BG-77 (Modification); New field; when the fields are used

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#150]
Changes to contracts should be announced in some cases (additional purchases and unforeseen events). As the variables in this section are formulated, and with all variables marked "m", it appears that it applies to all changes. Would it not be more accurate if the fields are marked "CM", ie mandatory when the prerequisites for the obligation to announce changes are fulfilled?

**Comment by JachymHercher** [comment]
We would be inclined to leave it as "M", because we consider the question of whether a notice should be published or not as out of scope. eForms describes how notices are published - not if. 

To answer with an analogy: some contracts require the publication of a contract award notice, some do not. This is not dealt with in eForms (not via CMs, not in another way), but by the directives. Similarly, some contract modifications require the publication of a contract modification notice and some do not, but eForms rules deal only with those notices that are published.
