### ISSUE TITLE
General: Why some variables are "conditionally mandatory" and not "mandatory"

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#152]
Providing information about deadline for tenders (BT-131), the main nature of the procurement (BT-23), the organisation NUTS code (BT-507), the purpose lot identifier (BT-137) and the estimated start and end date (BT-536 and 537) is marked as "conditionally mandatory variables". 

My question: Why are these variables not mandatory? Are not these variables always important/central to the procurement? Maybe if you can give some examples of certain conditions when those variables are mandatory and when they are not it will be easier to understand why they are marked "CM".

**Comment by JachymHercher** [comment]
Concerning BT-131, this is a mistake - please see https://github.com/eForms/eForms/issues/31#issuecomment-414250918. 

Concerning BT-23 and BT-137, this is because BG-02 (Purpose) can be used to inform both about a whole procedure (a "summary" type information) and about individual lots. The fields would not be mandatory when the BG is used for lots. See also the explanation in #64. 

Concerning BT-507, this is because some (not many) buyers may come from countries which do not have a NUTS code (e.g. embassies of EU countries abroad).

Concerning BT-536 and BT-537, this is because instead of using these BTs, the information could also be given only through BT-36 (Duration Period). (#98 and #106 provide some more background on this topic.)
