### ISSUE TITLE
BT-06 (Strategic Procurement); U-AP; Sense of being mandatory

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#156]
Combining the information from #93 and #40, one gets the impression that the following lists are valid data for BT-06:

- { environment-friendly: true, socially-engaged: false, innovative: false }
- { environment-friendly: false, innovative: true }
- { socially-engaged: true }
- {} _(empty map)_

What I do not understand is what the field being mandatory for CNs, CANs, and VEATs does mean. just that the fourth line above is disallowed? Or does each of these procurement notices have to have at least on strategic aspect ”checked“ (the indicator being true)?
`
Also, if it's mandatory, doesn't it belong to BG-02 (Purpose)? (This part of the question applies to BT-116 (Outsourced Procedure) as well.)

**Comment by JachymHercher** [comment]
Good point, thanks. Mandatory means that there must be a value. Thus, in #93, there is indeed a value missing - something like "no other values apply" (I will add a suggestion there).

We didn't put it in BG-02, or any other preceding business group, because the definition refers to concepts spread across many different BGs - technical specification (BG-02), award criterion (BG-707 Award Criteria) and performance conditions (BG-705 Other Terms Requirements).

**Comment by tinne** [comment]
All right, but would you suggest that these values are different:?
- { environment-friendly: false, socially-engaged: false, innovative: false }
- { no: true }

If I understand you correctly `{ environment-friendly: false, socially-engaged: false }`, would mean ”no to these two but I would not tell about innovations,“ right?
