### ISSUE TITLE
BT-13712 (Communication Lot Reference); Description; Why does this field exist?

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#159]
Why does BG-100 have a lot reference (BT-13712), whereas this part of the standard forms isn't lot-dependent?

It adds complexity to have different contact points, submission details, etc. for different lots, especially in cases where a supplier can bid on multiple lots. The benefit should outweigh this increase in complexity, but I'm not clear on whether the benefit is significant (or in demand by CAs or CEs).

**Comment by JachymHercher** [comment]
A few general principles to keep in mind: 
- Putting "related" purchases into one procedure is an obligation under EU law, acting differently might be interpreted as circumventing publication obligations. At the same time, splitting procedures into lots is encouraged by the directives (you should justify if you don't do it). As a result, even quite different purchases may be in a single procedure under different lots. 
- One of eForms' goals is to be flexible - to meet all user needs and to avoid having to change the standard in the future. A lot identifier in the Communication BG doesn't mean that information _must_ be split at lot level, but rather that it may. This can be allowed/forbidden per each implementer or country. 
- All first level BGs (except BG-6 Procedure) can be different lot by lot. We're not sure how much additional complexity is caused by keeping this option open also for BG-100 (Communication). 

That being said, here is where we think BG-100 (Communication) could be useful per-lot:
- Submission deadlines and related fields (BT-131 Deadline Receipt Tenders, BT-13 Additional Information Deadline, BT-98 Tender Validity Deadline, BT-132 Open Conditions Date). 
**Use case:** There is no inherent reason why bids for all lots should be submitted at the same time. It is good practice to give companies as much time for the preparation of bids as possible. Different deadlines per lot can lead to more time for companies. For example, they can reflect technical limitations (simplistic example: "we need to know the contractor for the roof only two months after we know the contractor for the walls") or procedural limitations (simplistic example: "we're guessing that it will take us two weeks to evaluate lot 1 anyway, so we can leave submissions for lot 2 open for an additional two weeks, because we wouldn't have looked at these bids by then even if we had them"). 
- Fields linked to procurement documents (BT-724 Access Tool, BT-15 Documents URL, BT-708 Documents Restricted, BT-520 Additional Information Contact, BT-18 Submission URL). 
**Use case:** In particular for joint procurement with multiple buyers, where different lots could be managed by different buyers, this information could be different lot by lot.

**Comment by tinne** [comment]
Maybe split the business group as suggested for BG-02 in #64?

**Comment by JachymHercher** [comment]
For documentation purposes we can add this split (we will consider it once we publish the business rules - they may be enough to make things clear), for the annex itself we would be inclined not to change it, because being more general in the act leaves more flexibility for technical implementation.

**Comment by tinne** [comment]
To generally follow this aim, may I suggest to add a documentary column “level” which may carry the values procedure/lot/both (and be clearer than formulation fiddling in the documentation column)?
