### ISSUE TITLE
BT-165 (Winner size); Description; Company Information

### ISSUE THREAD

**Issue by UHMYND** [eForms/eForms#162]
Information on companies that are involved in procurement, such as company size and legal form, is policy-relevant. In principle the EU SME definition is useful. It is also fairly complicated and not easily applied by users. Information on the number of employees and the economic parameters needed are often accessible and can be used to define company size. It is more difficult and time-consuming to consider direct and indirect partner and linked enterprises, which is often required to establish the real economic capacity of a company according to the definition. It is doubtful that the definition is correctly applied by users. More guidance is likely needed in relation to the SME fields. In general, information on company size could be added ex-post by matching the organizational identifier for a company to information available in business registries based on e.g. annual accounts. This would eliminate the need for a specific field for company size in the standard forms. It would lower the administrative burden on buyers and it would likely improve accuracy in availaible data on SME:s participation in procurement.

**Comment by JachymHercher** [comment]
We agree that the information should ideally come from source data in business registries, less ideally from the company itself (e.g. via the ESPD), least usefully from the public authority itself (because it has the lowest amount of information about the company and the lowest legal sanction for providing incorrect information). 

We are not quite sure why this would imply that the information should not be in the standard forms. From a legal point of view, the directives still state that this information must be provided by buyers themselves - they carry the legal responsibility for verifying that the sent information is correct. From a technical point of view, it seems more realistic to have interconnections between national systems suited to national needs rather than TED being connected with all the systems in the EU. 

Concerning the definition of the SME, please note that its revision is [currently being discussed](http://ec.europa.eu/growth/smes/business-friendly-environment/sme-definition_en).

We agree that guidance on various elements of standard forms (and procurement in general) is useful. Asking stakeholders about their needs in this area is planned after the work on the implementing regulation is done. 

(This issue is related to #163.)

**Comment by LodewijkIgnatiusTenderNed** [comment]
In the Netherlands the Chamber of Commerce does not deliver this information, because the EU has set no directives for this yet.

**Comment by JachymHercher** [comment]
@LodewijkIgnatiusTenderNed Would you have some additional information on that please? Many business registries around the EU provide various information over APIs (both publicly and not publicly), so it would be good to know how the EU can support the Dutch Chamber of Commerce.

**Comment by LodewijkIgnatiusTenderNed** [comment]
@JachymHercher I just discovered the recommendation on SME http://ec.europa.eu/growth/smes/business-friendly-environment/sme-definition_en . We use the indicator mentioned of <250 personnel means SME (MKB in Dutch) as well, but in TenderNed the indicator SME true/false is set manually by the Economic Operato. In reality the organisation of an EO can be more complex, and the indicator has proved to unreliable. The Dutch Chamber of Commerce https://www.kvk.nl/english/ is governed by the Ministry of Economic Affairs and Climate (our Ministry). Our expertise centre PIANOo on e-Procurement works on an operational level, and has no direct influence on this matter. Thank you for your offer, but for now we leave it as it is, as we have other priorities.

**Comment by GReaadhsy** [comment]
We propose field BT-165 to be optional, as far as it seems to be an additional administrative burden for CAs/CEs. Furthermore, it should be taken into account the fact that the indicators for SMEs are difficult to be correctly implemented in all cases, often leading to non-trustworthy data. It would be a good idea that data in that field could be linked with business registries across EU countries, if available.

**Comment by JachymHercher** [comment]
Information about SMEs seems to be a high political priority (and is also explicitly requested by the directives), so we are inclined to keep it. As discussed above though, implementing it via a connection to the ESPD or national registries is a very good idea.
