### ISSUE TITLE
General; (voluntary) publication of below-threshold notices

### ISSUE THREAD

**Issue by LodewijkIgnatiusTenderNed** [eForms/eForms#169]
One of the improvements according to the introduction document is:
"Supporting the (voluntary) publication of below-threshold notices in the TED format by including fields relevant for below-threshold procurement"
However, a lot of information such as Exclusion Grounds (BG-701) etc is not mandatory to publish. Does the Commission consider to treat this kind of information as CM in such case. That means: NOT Mandatory in case of tender below threshold?

**Comment by JachymHercher** [comment]
Good point, thank you. While it can be argued that the limitations in the annex would not be applicable to below-threshold notices, we will still clarify it and make sure to introduce business rules that give the necessary flexibility to below-threshold notices.

If it is easy for you, we would be thankful for examples of others fields which are "M" in the implementing regulation but which would not be mandatory for below-threshold in the Netherlands.

**Comment by JachymHercher** [comment]
@tinne thank you for the review. I've skimmed the spreadsheet and it seems that there are a lot of fields which are "M" for TED forms and empty in (some of) the German forms. 

For the implementing regulation, the main takeway is that we will include an open-ended rule on below-threshold notices, explaining that they can contain less information. For the technical implementation itself, at a later stage, we will propose a below-threshold "core" set of BTs that we think should be mandatory for notices (to ensure basic functionality) and ask you for a revision here.

@LodewijkIgnatiusTenderNed Given the flexible approach explained above, it isn't that necessary to have the concrete examples of fields that aren't M at national level. We take it that there are plenty.

**Comment by LodewijkIgnatiusTenderNed** [comment]
@JachymHercher just had a short consult with one of our juridical advisors. She marked the following Business Groups as Optional in case of a below threshold notice: BG-6 Procedure, BG-701 Exclusion Grounds, BG-702 Selection Criteria, BG-706 Techniques, BG-7 Procedure Result, BG-77 Modification. Given this indication + the sheet I guess the commission has enough "food" for a proposal.
Thank you @tinne for your addition. I propose to close the subject for now.

**Comment by JachymHercher** [comment]
Since we are currently waiting for the final opinions from Member States, we have come back to the topic of below-threshold notices. These notices can be published voluntarily by Member States. Using them at the national level would spare Member States to have a separate set of forms for below-threshold and for above-threshold forms. 

Based on the feedback above, we plan to take a minimalist approach to the notices, marking as mandatory for publication on TED essentially only the information about "who" (buyer, winner), "what" (title, description) and the structured data allowing to actually find the notice (nature, CPV). At national level, more fields can be made mandatory, as considered appropriate. 

We have uploaded the eForms spreadsheet with the three additional notices [here](https://github.com/eForms/eForms/files/3406752/_4_eForms_ACPC_Annex_Table2_spreadsheet_EN_below_threshold.xlsx). The forms are marked E2, E3 and E4 and correspond to a PIN, CN, and CAN.

We would very much welcome any comments.

**Comment by ColinMaudry** [comment]
During the past months the Direction of Legal Affairs of the French Ministry of Finances have led a workshop to co-construct the below threshold contract notices with representatives of legal notice publishers and other government bodies (I represented @etalab in this working group). I asked if I could share the draft version of this notice with you.
