### ISSUE TITLE
BG-557 (Group Estimated Maximum Value) / BT-557 (Group Estimated Maximum Value Lot Reference) / BT-157 (Group Estimated Maximum Value); All notices; Mandatory use

### ISSUE THREAD

**Issue by jurakova** [eForms/eForms#174]
BG-557 is marked as O (optional), but BT-557 and BT-157 are M (mandatory). If group is only optional, BT under the same BG can´t be M, only CM.

**Comment by tinne** [comment]
As I understand you read this like “for every Group Estimated Maximum Value record given (and there may be 0 to _n_ business group instances), you must give both Group Estimated Maximum Value Lot Reference and Group Estimated Maximum Value).”

**Comment by jurakova** [comment]
Thank you for your response, but if its true, than in spreadsheet it could be only M and O symbols for legal status. If this type of BTs are M and not CM, but they are under BG which is O, we lack purpouse of CMs.

Example: We understand legal status as follows: 
M as it must be filled in the eForm in every case.
CM should be filled only under certain conditions
O is optional

So if we have BG which is only optional, if we do not fill it, then BTs under mentioned BG are not needed if are CM, but if they are M, we have to fill them even if we do not fill BG which is O.. If we fill optional BG, then BTs under mentioned BG fulfill "under certain conditions" status, so we have to    
fill them too, if they are CM.  

@JachymHercher please, can you clarify use of M, O and CMs, because they seems to be used "randomly" sometimes in spreadsheet. 

See also #182[](https://github.com/eForms/eForms/issues/182)

**Comment by tinne** [comment]
There are lots of other conditions, e.g., if the Organisation is a Winner, Winner Size (BT-165) and Winner Parent Country (BT-706) must be given in the BG-703 instance denoting it. Do not give it in the Organisation instance about the buyer(s). See also many of the other issues.

**Comment by JachymHercher** [comment]
@jurakova you are right, this is somewhat unclear/ambiguous. The reason why we did not use CM in BG-557 (and other cases with mandatory BTs within optional BGs), is because we interpret CM as "conditional on other BTs". Since BG-557 is not a BT (i.e. it does not directly contain any informationm only other BTs), we didn't take it as a "trigger" for a condition. Instead, when a mandatory BT is within an optional BG, we explained that the optionality stays (see https://github.com/eForms/eForms/issues/2#issuecomment-396220770). 

Nevertheless, changing these BTs to "CM" might be more intuitive (see https://github.com/eForms/eForms/issues/176#issuecomment-425054423). We will see how to communicate this more clearly in the version sent for the legal adoption.
