### ISSUE TITLE
BT-25 (Quantity) / BT-625 (Unit); Description; The number of units required

### ISSUE THREAD

**Issue by jurakova** [eForms/eForms#175]
Does this BTs mean, that every item procured under one procurement (one eForm) need to be specified in separate lot? 

I.E.: If we need to buy office supplies (print paper, scissors, pens), we can not fill only one lot with CPV for office supplies, but we need to make 3 separate lots with 3 iype of items with its own quantity and unit?

**Comment by JachymHercher** [comment]
Both of the BTs you mention are optional, so they will not create a new obligation to split a procedure into lots. However, taking your example, you are right that if different items are mixed in one lot, then the quantity and unit will be hard to use. 

We see two solutions:
- Since the field is optional (and splitting into lots a good practice), the information should be filled in only when it makes sense at the lot level. (Using your example, if you have countable items such as scissors and pens in separate lots, then you would use the field; if in a single lot, you wouldn't.)
- Allow a repeatable BG, with BTs covering, at least, classifications, descriptions, units and items, to be linked with a single lot. This could be similar to the way the open contracting data standard treats [items](http://standard.open-contracting.org/latest/en/schema/reference/#item) and [lots](http://standard.open-contracting.org/latest/en/extensions/lots/). 

Would you have any opinions on this? (also @jpmckinney, @tinne?)

**Comment by tinne** [comment]
Thanks for asking, in my understanding they are just a means to put some in principle statistically classifiable information into this rather general section (not that all information until BT-95 (Recurrency Description) need not even be lot-specific. You may also want to read the discussion in #137.

As of office supplies, I would expect most buyers to draw up a framework agreement specifying some example basket detailed in the procurement documents.

**Comment by jpmckinney** [comment]
I imagine that adding a breakdown of items is not a small change to eForms. If the goal is to move toward a full breakdown of items, your second option is needed. If the goal is to collect statistical information (assuming the bias due to data gaps is acceptable), then your first option is fine.

I'm not familiar with the costs/benefits of having fewer lots with mixed items versus more lots with distinct items. If having more lots has significant costs or disadvantages, it may be preferred to take the second option. If not, and if the first option is taken, then procedures can still be broken into lots to be able to declare items.

**Comment by JachymHercher** [comment]
Thank you for the opinions. Indeed, the goal of the BT-25 and BT-625 is to allow further specifications of what is being bought in a machine readable format, which can then be relevant for companies as well as to compare unit prices. However, if the items do not correspond to lots (i.e. it is not possible submit tenders for them) then the relevance for companies is minimal. 

As such, we will suggest going for option 1: using the field there where it makes sense. (If there is demand in the future on more wide use of these BTs, this can be reviewed in a future version of eForms.)
