### ISSUE TITLE
BT-01 (Procedure Legal Basis); Description; adding the Financial Regulation in the list

### ISSUE THREAD

**Issue by ognyami** [eForms/eForms#177]
In BT-01 (Procedure Legal Basis) the text in bold should be added: “Legal basis (e.g. a European directive, **regulation**, national law) under which the procurement procedure takes place." Indeed, the legal basis acts listing is not exhaustive, but since thousands of notices are published every year under the EU Financial Regulation (which explicitly refers to all the information set out in the relevant standard forms referred to in Directive 2014/24/EU), it is better to add it to the list (thus also making sure that the Financial Regulation of the EU will be included in the predefined list of character strings that will be used for this field).

**Comment by tinne** [comment]
Suggest to enhance it even further, “a European directive, regulation, national **or regional** law” as with some countries like Germany also subnational legislation applies (e.g. federal state budget law).

**Comment by JachymHercher** [comment]
Hm, I'm not too convinced. These are really just non-exhaustive examples. We would be inclined to leave it the way it is - "Legal basis" covers everything.  

> "better to add it to the list (thus also making sure that the Financial Regulation of the EU will be included in the predefined list of character strings that will be used for this field)."

On one hand I understand the fear, but on the other hand including this in legislation just as a "reminder" doesn't seem as a good drafting practice. We assure you it won't be forgotten - e.g. because it's in the legislative codelist already and because @muricna knows about it.
