### ISSUE TITLE
BT-87 (Selection Other); Description; Wrong legal status

### ISSUE THREAD

**Issue by jurakova** [eForms/eForms#183]
As it is mentioned in the description in BT-87, it is a Brief description of other requirements and criteria for participation. All such criteria must be listed.

While it is only for other requirements if they exists, than this BT should be O for all relevant eForms, but now it is M for some PINs and CNs (D25 and D81).

How it can be M if other requirements do not exist?

**Comment by JachymHercher** [comment]
The approach is the same as for other selection criteria (which, in a given procurement procedure, also might not exist) - the fields are mandatory so that at least there must be a text information that no such criteria are used.

This approach reacts to a problem in the current forms, where fields are often left empty and to readers it is not clear whether the field has been ignored/forgotten, or there simply isn't anything to inform about. For this reason, in eForms we usually suggest to require an explicit confirmation, even if just takes the form of a text saying "None".

**Comment by tinne** [comment]
From a data modelling point of view this seems quite weird as people will come up with lots of ways to say none (no computer could say whether they gave a non-none answer). 

As we not discussing input technology although it has been marked out of scope by the explanations in the consultation text? Anyway, when it comes to input technology, you could model

> Brief description of other requirements and criteria for participation. All such criteria must be listed.
> [  ]  Criteria exist: __________________
> [  ]  There are none such criteria.
> (check at least one line)

Regarding data type, this could introduce a data type TextOrNone, which is
- either a Text,
- or “None”
- or not given,

where a business rule (or an M or CM field) could rule out the third case.

**Comment by JachymHercher** [comment]
This approach is used consistently, but practically concerns (almost) only BG-702. However, this section has a good alternative - using the ESPD (see #87). That's why we are not really proposing some "semi-structured" approach here. Instead, there is fully structured - the ESPD; and fully unstructured (=same as now, minimal switching costs) - the text fields in the forms.

(We did consider semi-structured, but the best approach would probably be to have an indicator for each text field on "Criteria X exist", which didn't seem worth it. We're not sure the TextOrNone data type would solve it, because, depending on input form, people could just write "No" instead of "None" and it wouldn't be machine processable anyway.)

**Comment by tinne** [comment]
> people could just write "No" instead of "None" and it wouldn't be machine processable anyway.
This was the “flaw” I was talking about. Hence I updated https://github.com/eForms/eForms/issues/183#issuecomment-425419896 to explicit that the text would necessary give a non-void criteria list.

**Comment by JachymHercher** [comment]
I'm not sure I understand, I apologize. When you talk about a "non-void criteria list" (="positive list of criteria"?) isn't that the same as changing BT-87's data type to Code and specifying all possible "other" criteria?

**Comment by tinne** [comment]
Maybe I'd apologise. I understood it the other way round, MANY different sorts of text (all meaning “there are some criteria” and ONE code, meaning no criteria whatever.

**Comment by JachymHercher** [comment]
Sure, but how does the machine know that the "different sorts of text" mean "there are some criteria"? Even if we say that just one code ("None") is allowed, the "No" can still sneak through as a text, no? (Which then means that the added code hasn't resolved our problem...)

**Comment by tinne** [comment]
No, but this is a problem to be solved in front of the computer. When you order people explicitly not to use any circumscription of “no” when they mean no, and they ignore this, it is at least a data entry error which can be found and marked by an (procurement ignorant MS language savvy) editor.

We have buyers writing the procurement subject in the organisation name field. My parser will not detect. But since the structuring of organisation addresses, its harder to write “see above” in the review body fields.

**Comment by tinne** [comment]
From the previous discussion I had understand that you are eager to know (in a machine understandable way) whether the answer is ”There are no other requirements and criteria for participation” or different. If this is not required and the information need not be available, a single text field is OK (leaving statistic availability to notices using the ESPD extension).

**Comment by JachymHercher** [comment]
@tinne indeed, we do not need to know this difference in a machine understandable way, human readable is enough. Machine readability, for those interested, can be achieved by using the ESPD. 

This topics was also discussed at the [last eSenders seminar](https://publications.europa.eu/en/web/esenders-seminar-2018/home). The participants were also in favour of the current approach (as opposed to indicator BTs before each text field and a CM text field), so we suggest to leave it as it is.
