### ISSUE TITLE
BG-707 - Award Criteria (Mandatory only for CAN general); purpose or mistake? 

### ISSUE THREAD

**Issue by jurakova** [eForms/eForms#187]
According to directive 2014/24/EU ANNEX V - PART C point 18, it seems that information about Award Criteria have to be included in the eForms (CN also), so it should be marked as mandatory, not optional as it is now.  

For all users it should be clear from eForm where Award Criteria are mentioned, if they are in eForm or in other procurement documents (as it is in curent Forms). Isn´t it?

**Comment by JachymHercher** [comment]
The point you refer to includes the formulation "criteria [...] shall be indicated where they do not appear in the specifications or [...] the descriptive document". Since there is the condition that if the criteria are in the technical specifications they do not need to be in notice, the mark "optional" in eForms seems correct. 

(At national level, the rules can of course be more strict, so award criteria may be made mandatory also in contract notices.)

We agree, but that is a question for notice display rather that the standard itself. If the criteria are not in the notice, the system can display a message emphasizing that the criteria are elsewhere.
