### ISSUE TITLE
BG-320 Winning Tender and "reference" to BG-310 Contract 

### ISSUE THREAD

**Issue by MBucek88** [eForms/eForms#189]
From our point of view this BGs make sense while the contract is not divided into lots. 

But if procedure will be divided into many lots (e.g. more then 100) with many winnig tenders contracted under the Framework Agreement (it could be also for more than one buyer in case of framework agreement), BG-320 and its reference to BG-310 could be problematic, hard to read and confusing either for buyer who is filling eForm and for whoever else who reads this eForm.

**Comment by JachymHercher** [comment]
Thank you for the comment. We agree that with large numbers of lots, contracts, and winning tenders, notices can easily get very complex. However, we still believe that under these conditions this approach is the simplest. In particular, this is because it avoids any data duplication, so the overall amount of data is smaller than it would have otherwise been. Would you have a suggestion for a simpler approach?

Also, as discussed in https://github.com/eForms/eForms/issues/180#issuecomment-425958273, please note that eForms are about data storage, not how forms are filled in or displayed to users. The most user-friendly way of presenting information may quite likely be different than the one for storing information, e.g. depending on what is available automatically from the submission and evaluation phases.
