### ISSUE TITLE
BT-148 recieved tenders SME and BT-165 winner size

### ISSUE THREAD

**Issue by MBucek88** [eForms/eForms#190]
In case of BT-148 recieved tenders SME we don´t have such a problem, it looks like a field matching existing one in current Forms. Where buyer in the "CAN" have to mark how many tenders were recieved from SMEs. 

Problem is in BT-165 winner size, which is matching section V. if winner is SME. But in new eForms it is more precise and ask if winner is Micro, Small or Medium enterprise, not if it is just SME (i. at least one of these three). In our case companies (tenderers) have very big problem to classify themself even as SMEs, neither which one of them (micro, small, medium). And if tenderer himself has problem to identify as Micro, Small or Medium enterprise, how buyer could classify them in BT-165 properly?

**Comment by JachymHercher** [comment]
The reason for changing this classification from SME to the individual sub-types is because SME is still a very broad category, covering the majority of economic activity. At the same time, the measures needed to support the interest of companies in public procurement depend on the more detailed size - companies with 5 employees are very different from companies with 230 (both being SMEs). 

Concerning BT-165, we see several ways how this information can be gathered:
- It can be taken from the ESPD (in the current/next version, this information is/will be included). 
- Companies/buyers should have some [simple background](http://ec.europa.eu/growth/smes/business-friendly-environment/sme-definition_en) information on how to decide. This can be included together with the procurement documents, in the form filling tool, etc. With this definition, establishing the size shouldn't take too long? (Essentially headcount + turnover).  
- Ideally, the information can be taken automatically from business registries and filled in automatically in the e-tendering tool. 

Additionally, please note that the EU SME definition is currently undergoing a review, so it should be simpler by the time eForms are in force. Furthermore, we are aware that there will be some errors (e.g. people deciding just on the basis of the number of employees). Even in that case, the information is valuable for policy makers.

**Comment by GReaadhsy** [comment]
We propose this field to be optional, as far as it seems to be an additional administrative burden for CAs/CEs. Furthermore, it should be taken into account the fact that the indicators for SMEs are difficult to be correctly implemented in all cases, often leading to non-trustworthy data. It would be a good idea that data in that field could be linked with business registries across EU countries, if available (see also comment on BT-165).

**Comment by JachymHercher** [comment]
@GReaadhsy Information about SMEs seems to be a high political priority (and is also explicitly requested by the directives), so we are inclined to keep it. As discussed above though, implementing it via a connection to the ESPD or national registries is a very good idea.
