### ISSUE TITLE
BT-76/ Tenderer Legal Form

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#193]
This field should be changed from optional to CM, depending on the conditions required by the procurement documents (e.g. when a CA/CE demands a certain legal form to be taken by a group of tenderers that is awarded a contract).

**Comment by tinne** [comment]
As I understand CM would mean that you could tell from other BTs or from the notice type whether it is mandatory, i.e., CM = mandatory on technically verifiable conditions.  There can always be external technical reasons in practise that information is more mandatory than given, most prominent example being national law.

**Comment by JachymHercher** [comment]
As @tinne said. Just one thing to add: at national level / in national solutions, you can of course make more fields mandatory. So, for example, if you will have machine processable procurement documents, then in your e-tendering system, the field could be (conditionally) mandatory. However, this is a question of implementation rather than eForms per se.
