### ISSUE TITLE
Need for aligned business terms

### ISSUE THREAD

**Issue by VibekeE** [eForms/eForms#201]
The use of ICT tools, including electronic exchange of structured information, in the full end-to-end e-procurement process will result in a more open and effective procurement process for the contracting authorities as well as private businesses. Efficient development and use of the required ICT tools does however require a holistic view on the end-to-end e-procurement process and a coordinated development of the supporting standards.

Key to such coordinated development is the use of a common vocabulary of business terms as this will secure common understanding of the different information elements needed throughout the process. The ongoing eProcurement Ontology project of the EC Publication Office represents, in our opinion, a focal point for developing the required business term vocabulary. The work of the Ontology project is also making use of the already approved ISA Core Vocabularies. The eForms, as well as the ESPD, are important documents used in the end-to-end e-procurement process and their content should be well aligned to that of the Ontology project. We therefor recommend that:
 1) the business terms and semantic definition for information elements in the eForms use the Ontology project as its base, and 
2) that data structures developed by the Ontology project are re-used to the extent possible.

**Comment by paulakeen** [comment]
For you to know, the  ePO (eProcurement Ontology) being developed by the Publications Office reuses the ESPD Criterion and Evidence sub-model. The definitions worked out by the ePO Working Group in relation to criterion, criterion property, etc. are feeding back the ESPD-EDM and documentation.

The works developed in the ePO and the ePO Glossary are also being taken as input for the revision/evolution of (1) the UBL data model (towards the UBL-2.3, revision should start by January 2019); (2) the ISA2 Core Criterion and Evidence Vocabulary; (iii) the future versions of ESPD based on UBL-2.x. The ideal consequence of this is that ESPD and ePO criteria are identical (which right now is quite close to be) and that the generic (domain-agnostic) criteria vocabulary is the one published by the ISA2 programme in Joinup.

**Comment by JachymHercher** [comment]
Thank you for the comments. We fully agree on the importance of the ontology project, which is also why we are taking great care that the ontology and eForms are aligned. A few more detailed thoughts on the interaction between eForms and the ontology are below. 
 
- While definitions need to be aligned, this does not mean they should be identical. In particular because: 
    - eForms are an implementing regulation, i.e. they exist within the specific context of the directives. As such, from a purely drafting point of view, they do not need to re-state the definitions and principles of the directives - these clearly apply. In the case of the ontology, these need repeating.
  - The ontology is descriptive, while the eForms are prescriptive. Being an implementing regulation, eForms can - and should - be used to narrow down meaning of some BTs for better comparability and data quality.    
   - The ontology is at the level of concepts, while eForms is at the level of business terms. Multiple eForms business terms may correspond to a single ontology concept, just in a different context. 
- While data structures need to be aligned (e.g. easily mapped one to another), they do not need to be identical. In particular, this is given by technology: the eForms will be implemented as XML, so we are trying to keep the structure as close to XML as possible for easier conversion. The ontology will (besides serving as a reference point) live as an OWL file. As far as I've understood, XML and OWL may express the same things in different ways. 

It is also worth noting that while in principle it might have been ideal to have the ontology as a basis for all other work, in practice it is most useful if the alignment happens in both directions, as is currently the case. This is the case particularly because the legally binding nature of eForms leads to significantly stronger stakeholder engagement than in the case of the ontology, which does not have legal power. This way, eForms essentially functions as an efficient source of input for the ontology.
