### ISSUE TITLE
BT-26  Classification Type

### ISSUE THREAD

**Issue by MaKilbane** [eForms/eForms#208]
Classifications types, in addition to the mandatory CPV codes, may be used. Are these classification systems standalone i.e. no mapping or conversion to CPV. The business alerting of public procurement opportunities will be critical for increasing engagement by businesses (and SMEs).

**Comment by JachymHercher** [comment]
The list of other classifications systems is not yet established. We leave this flexibility in the eForms so that we can flexibly respond to user's eventual requests. (We assume this could be used for example for more detailed sectoral classifications, e.g. in the medical sector, in which case these wouldn't be mapped to CPV, because there isn't an equivalent.)
