### ISSUE TITLE
BT-123 (Electronic Auction URL); Location of BT in the form

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#218]
We suggest that Technique Url is used afetr selected technique in order to provide a generic and scalable form.

**Comment by JachymHercher** [comment]
This sounds appropriate for a general data model. In the case of eForms, the BT was specified more narrowly, because the only technique with a proposed URL was the electronic auction. 

In any case, as it seems that even the electronic auction is not really relevant (see #222), then perhaps this issue is no longer relevant.
