### ISSUE TITLE
BT-11 (Buyer Legal Type); Allocating entities inside other entities in code list; [CODELIST]

### ISSUE THREAD

**Issue by jadelanava** [eForms/eForms#220]
Checking the codes referred to this rubric in the spreadsheet "5_eForms_feedback_codelists_draft" we note that among the available options are the following:

• Central government authority
• Regional authority
• Local authority
• Body governed by public law
• Public undertaking
• Entity with special rights
• Organization awarding a contract subsidized by a contracting authority
• Defense Contractor
• International organization

Given the decentralized structure of the administrations in Spain, we would like to propose, in order to allocate the entities within the State, Regional or Local sector, that the rest of the entities (Body governed by public law, Public undertaking, Entity with special rights, Organization awarding a contract subsidized by a contracting authority ) will be able to adhere to one of the three previous ones (Central government authority, Regional authority or Local authority). This would greatly facilitate data collection. (i.e. a local public undertaking could be directly allocated in the local sector) 

Previously we were warned that this division could be carried out through the NUTS, but we have observed that they are commonly used as the place of execution of the contract instead of the origin of the CAE.

**Comment by JachymHercher** [comment]
Thank you for the comment. To be sure we are on the same page, we would like to start by making sure that we correctly understand what you are interested in. 

In the current eForms draft, there are two fields involving NUTS code. One is Organisation Country Subdivision (BT-507), the other is Place Country Subdivision (BT-5141). The former includes the NUTS based on the address of the buyer, the later is the NUTS of the place of execution/performance/delivery. So under the current eForms proposal, the geographical NUTS of the organisation should already be clear.

If we understand correctly your request, the NUTS code does not solve the problem, because it does not indicate which level of government is "responsible" for the buyer. For example, there might be a body governed by public law (e.g. hospital, school) which is located in Salamanca, so BT-507 would be "ES415". Nevertheless, from the data, it would still not be clear whether it is the central government that is "responsible" for it, or whether it is the Castile-Leon autonomous community, or the Salamanca province or even one of the municipalities. This is the information you would like to know, correct? 

If yes, could you please help us define the relationship between the "state/regional/local sector" and the "buyer"? Does it means that the relevant government sector "is responsible" for the buyer, "set it up", has some other type of power over it?

There are several ways you could collect this information:
1. Not in notices, but rather in a register of information about public authorities. The organisations in this register could be linked to organisations in notices using the Organisation Identifier (BT-501). 
2. Add a new BT in the Organisation (BG-703) section, where buyers would indicate what type of authority is responsible for them. (Options could be: central, regional, local, lower than local.) 
3. Add a code to Organisation Role (BT-08) which would allow submitting information about the responsible government organisation (e.g. a ministry of health that is responsible for a hospital).  

Which approach is the best depends on the definition of the relationship between the two organisations and consideration of how interesting this is for procurement stakeholders in general; how reliably public authorities will be able to fill this in; etc. We would be happy for your further thoughts on the matter.

**Comment by jadelanava** [comment]
Dear Colleagues

we would like to share with the group the conversation that we have maintained with Jachym regarding the BT-11, as we agreed with him. 

Thank you very much in advance. 




Jachym question:

"Adding a BT into the Organization (BG-703) section should be possible. 

We would still need to clarify a few things.

1.	In eForms, "Buyer" is an “umbrella” word that covers any organisation that may be conducting public procurement. This means contracting authorities, contracting entities, defence contractors, international organisations, or organisations awarding contracts subsidized by a contracting authority.” 

You would like Spanish authorities to submit this information only for contracting authorities, or for any type of buyer? "

Reply from Spain:

"We believe that only the contracting authorities that belong to the public sector will need an additional field in which they can report their dependence to a certain  territorial level, excluding from this definition companies with special or exclusive rights as defined under Art. 5.10 and 5.11 of Directive 2014/23 / UE on the award of concessions contract and under Article 4.3 Directive 2014/25/UE on procurement by entities operating in the water, energy, transport and postal services sectors and repealing Directive 2004/17/EC.

Therefore, under “buyer” two options should be given:

(i)	“Buyers” belonging to the public sector and
(ii)	“Buyers” not belonging to the public sector

Only for (i) the additional field should be shown"




Jachym question:

"2.	Even if every contracting authority in Spain knows which territorial level is belongs to, we still need a definition of a field that could be useful also in other EU countries, i.e. we need to have some kind of more universal description. 

Could I ask you to explain better what belonging to a territorial level means in Spain (i.e. is it “controlled by”, “funded by”, “set up by”, etc.?) "

Reply from Spain: 

"Generally speaking, the Contracting Authority shall belong to a certain territorial level if it is controlled by the said level."

**Comment by JachymHercher** [comment]
@jadelanava, thank you for the summary. In the end, we found as the simplest approach to expand the BT-11 (Buyer Legal Type) codelist. These are the values in the updated proposal: 

- Central government authority
- Regional authority
- Local authority
- Body governed by public law
    - *Body governed by public law,   controlled by a central government authority*
    - *Body governed by public law,   controlled by a regional government authority*
    - *Body governed by public law,   controlled by a local government authority*
- Public undertaking
    - *Public undertaking, controlled   by a central government authority*
    - *Public undertaking, controlled   by a regional government authority*
    - *Public undertaking, controlled   by a local government authority*
- Entity with special or   exclusive rights
    - *Organisation awarding a   contract subsidised by a contracting authority*
    - *Organisation awarding a   contract subsidised by a central government authority*
    - *Organisation awarding a   contract subsidised by a regional authority*
    - *Organisation awarding a   contract subsidised by a local authority*
- Defense contractor
- International organisation

From a data modelling point of view, we realize that "controlled by XYZ" might have also been put into a separate codelist, which would reduce duplication. On the other hand, it would require business rules to specify which combinations of "Buyer Legal Type" can be combined with which values of the new business rules. 

Does this work for you?

**Comment by paulakeen** [comment]
Thnak you for this taxonomy...nice input for the ePO, too.

**Comment by jadelanava** [comment]
Thank you very much for the proposed modification of the Business Term BT-11 (Legal type of buyer). I would like to make a couple of considerations;

- 1. The BT-11 is available as mandatory for all types of notification, regardless of the European directive 
     to refer to, and, as a result of the proposed coding, this could mislead the Contracting Authorities. 
     (For example, a security agency that will publish an announcement under EU / 2014/24 directive 
      could mark the option of Defense Contractor).

      Would it not be more appropriate that, for each type of notice, depending on the EU Directive 
      concerned, the fields available will be only those that are affected by that applicable Directive?

- 2. Within the Entity field with special or exclusive rights:

             I. It would be clearer if insteado of refering to "Organization awarding a contract subsidised by a 
            contracting authority” text is substituted by " Organization awarding a contract subsidised by 
             another contracting authority "

            II. We prefer that the proposed option" Organization awarding a contract subsidised by another 
            contracting authority ", instead of being the first option “a)” is phrased under option “d)”. Only to 
            avoid mistakes.

Once again, thank you for your time and effort in this matter.

**Comment by JachymHercher** [comment]
Thank you very much for the input. 

1. We agree with the principle. Concerning the technical solution, this will be covered by the eForms business rules ("If the Directive is not 2009/81/EC, then BT-11 cannot be 'Defence Contractor'"). We will add such a rule to the list of changes for the [preliminary draft](https://github.com/eForms/eForms/raw/master/6_eForms_feedback_rules_preliminary_draft.xlsx) of the business rules.

    How the user interacts with this depends on how you implement the rule in the national/regional/local IT system. For example, the option may not even be available to the user, or it may be available, but if the user chooses it, the system informs him that the choice he made is not compatible with the directive he has already selected. 

2. i. A priori, in our opinion, the organisation awarding the contract subsidised by a contracting authority does not need to be a contracting authority itself. It is another type of buyer. (See Art. 13 of Directive 2014/24/EU, which sets that the Directive applies to the contracts themselves, but does not mention anything about the status of the organisations/entities which award them.) Consequently, it is probably better not to say that it would be "another contracting authority". (Even though it sometimes may be the case.)

    ii. In the codelists, the "by a contracting authority" code is listed as the first one because it is the most general one. This is the same approach as for the other codes, where for example "public undertaking" is a general code and the more more detailed codes are listed below.

    Please note that your national/regional/local systems do not need to show the codes in the same order as the codes spreadsheet. Furthermore, at national/regional/local level, you could even introduce additional business rules, which would forbid the use of certain codes. (For example, many countries are likely to not use the more detailed codes given in the codelist. Spain, by contrast, could choose to not use the general codes and only allow the use of the detailed codes.)

**Comment by jadelanava** [comment]
Thank you for your quick response

1)  We agree with the decision taken in point one, adding this rule in the list of changes for the preliminary draft of the business rules. Thanks for that.

2) Regarding the second point, we are agree with you in the clarification of Art. 13 Directive 2014/24 / EU.

Kind Regards
