### ISSUE TITLE
BT-123 (Electronic Auction URL); CN general, CN social; Need for having BT-123 in CN questioned

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#222]
There is no need to have eAuction URL in contract notice. eAuctions are always preceded by submission of tender and eAuctions takes place always in second stage of which a contract notice is not published in TED (URL is send to tenderers that are "admissible")

This is conditionally mandatory field implying that if eAuctions is used then this URL must be provided.

**Comment by rantati7** [comment]
This is conditionally mandatory field implying that if eAuctions is used then this USL must be provided.

**Comment by JachymHercher** [comment]
We agree. Unless we receive any other comments to the contrary, we will remove the field.

**Comment by jpmckinney** [comment]
@myroslav In ProZorro, are auctions only performed in a second stage, as described in this issue? Is there a use case for having the auction URL publicly available?

**Comment by JachymHercher** [comment]
Offline, @Jurakova and @MBucek88 raised the point that informing about the eAuction website already in a notice may be important in cases where the eAuction platform registration takes some time (esp. for foreign companies). This could be especially important for below-threshold procedures, where the burden linked to registering on the platform could even influence whether companies decide to participate. 

This information could also be included in BT-122 (Electronic Auction Description), but having it separately may allow some additional features such as searching for procedures where a certain eAuction platform is used. Consequently, we are more inclined to include the BT as optional rather than removing it.

**Comment by rantati7** [comment]
Well... then the start of the actual eAuction can be prolonged until all tenderers have registered.

Make this field optional, please! - then the MS can decide at what level this info is to be provided mandatorily.

**Comment by myroslav** [comment]
@jpmckinney, sorry I missed your request for more information.

Can you clarify, what is 2nd stage? In ProZorro, after Contract notice is placed in the system, Private Procurement platforms are submitting Bids (Tenders) into CDB. When Auction is due to hapen, Auction URL (public information) and Participation URLs (private information) are added to Contract Notice record and to respective Bids (Tenders). The very same mechanism is working both in Procurement Procedures with prequalification and postqualification, the only difference is that after prequalification only qualified bidders are getting Participation URLs, and in postqalification all bidders are getting Participation URLs.

Public Auction URL is there for transparency, since any auction can be visited by obserers without participation.

**Comment by rantati7** [comment]
Sorry to add this comment: I think this is too much tranparency. Sometimes one needs to sacrifice tranparency for other things incliding suppliers business secrets. If the eAuction is on specific supplies (say medicine) everyone gets to see the detailled prices or quality which may prevent suppliers from iparticipating in public procurement completely. 

I still think making this field optional is the way to go forward: those countries that need to have this may make it mandatory when eAuctions is used. Majority of platforms (those that I have researched) do not work in the same way Prozorro does. eAuction is generated only after the initial bids are received. From initial bids the CA needs to generate the eAuction. Prices and quality items that will be eAuctioned are imported / inputted (depending on how structured the system is / how structured the CA has configured the procurement procedure to be) to the eAuction module. At this stage the URL is generated and sent to qualifying suppliers. 

I do not think it is in line with the current practice / legal president to add anything to the contract notice after it has been published, at least in Finland the court is checking that the contract notice published in TED has exactly the same information as in our national tnotification service / platform. If the data is different there is notification error and the country annuls the procedure.

**Comment by JachymHercher** [comment]
Thank you for the comments. Concerning the eForms approach, having the field as optional at EU level is indeed what we will go for - whether it needs to be published or not depends on the country/system and the field can be set as mandatory at the country/system level. 

@rantati7, concerning transparency, please note that there are at least two recent and very interesting publications which make the case that commercial confidentiality is, in practice, often interpreted too broadly. One is by the [Center for Global Development](https://www.cgdev.org/publication/principles-commercial-transparency-public-contracts) (I've contributed to it), the other comes from the [Open Contracting Partnership](https://www.open-contracting.org/resources/mythbusting-confidentiality-public-contracting/).
