### ISSUE TITLE
BT-17 (Submission Electronic); Repeatable; Codes are disjoint

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#223]
BT-17 (Submission Electronic) has a data type of "Code" and is repeatable. The available codes are:

1. Tenders must be submitted electronically.
1. Tenders may be submitted electronically.
1. Tenders cannot be submitted electronically.

These codes have disjoint semantics, i.e. it can't be true that tenders both "must" and "cannot" be submitted electronically.

The quickest solution is to make the field non-repeatable.

Another solution is to change the codes to "Tenders may be submitted electronically." and "Tenders may be submitted non-electronically." That way, if only one code is selected, it implies that there is only one way to submit (corresponding to the first and last of the original codes).

**Comment by JachymHercher** [comment]
You are right. 

The first option (making the field non-repeatable) sounds better. Having three options rather than two options sounds clearer. A user seeing only "Tenders may be submitted electronically" may wonder whether it really means "Tenders cannot be submitted non-electronically."

However, the current codelist could perhaps be improved (all sentences would be instructions) to say:
1. Tenders must be submitted electronically.
2. Tenders may be submitted electronically or non-electronically.
3. Tenders must be submitted non-electronically.

**Comment by jpmckinney** [comment]
I agree that the new codelist values are clearer.

**Comment by JachymHercher** [comment]
Based on the discussion above, we will suggest to change BT-17 to non-repeatable. The discussion about the codelists is no longer relevant, given #300.
