### ISSUE TITLE
BG-557 (Group Framework Estimated Maximum Value); Level; Level should be +

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#224]
This group's level is "++", but it has a Lot Identifier field, so it seems to me its level should be "+", like all other groups with Lot Identifier fields. (The fields within the group should also have their levels lowered, if so.)

**Comment by jpmckinney** [comment]
The same might apply to:

* BG-330 (Group Award)
* BG-709 (Second Stage)

**Comment by JachymHercher** [comment]
The "++" is intentional - the BGs are nested within other BGs. (The reason why it is nested is different case by case, happy to clarify, if useful.)

**Comment by jpmckinney** [comment]
I would appreciate an explanation for at least one of the BGs, as it is unclear to me in which cases a dependent BG is nested or not.

**Comment by JachymHercher** [comment]
There's a common pattern here - all the BGs are nested within BGs that don't specify lot identifiers. Consequently, the nesting shouldn't have any impact from a technical point of view. The reason for the nesting is just "semantic", see examples below. Perhaps we're nesting a bit too liberally, happy for your views. 

- BG-709 (Second Stage) is nested in BG-6 (Procedure), because it is about the second stage of the procedure. Similarly for BG-330.

- BG-137 (Procedure Lot Result) and BG-556 (Group Framework Maximum Value) are nested within BG-7 (Notice Result), because they are about the result of the notice. 

- BG-557 (Group Framework Estimated Maximum Value) is nested within the Purpose (BG-02), but is intended to be used only when BT-137 (Purpose Lot Identifier) is empty*, i.e. BG-02 is used as a summary of the whole procedure. Having BG-557 nested should have no impact beyond allowing BG-557 to be next to BT-27 (Estimated Value), which we liked because the two fields are semantically close. 


*That's a missing business rule, we'll add it.

**Comment by jpmckinney** [comment]
My confusion then is that many top-level ("+") BGs are about the procedure. So, why are BG-709 and BG-330 "++" but the following are "+": BG-02 (Purpose), BG-701 (Exclusion Grounds), BG-7 (Notice Result), BG-710 (Additional Information).

I agree that there's no technical impact, but it seems to be inconsistent, which might impact correct understanding of relationships between BGs.

**Comment by tinne** [comment]
BG-330 and BG-709 are in fact nested not inside the notice envelope, but in BG-6 (Purpose).

A notice has a procedure has a (potentially empty) set of Group Award data records. The procedure also has a (potentially empty) set of Second Stage information.

So, read every plus more as in the line above as "nests within" - this is always connected with a BT inside a BG. Same number of plus signs - same level. Less plus signs but more than one - level with some higher level information nearer to the top of the sheet. Back to one plus sign - new top level group. See also #2.

**Comment by jpmckinney** [comment]
To clarify, my question/confusion is about why some groups are considered top-level. From one perspective, only the Notice is top-level. From another perspective, anything that uses identifier fields to indicate its nesting doesn't need to use hierarchy (+ signs) to indicate its nesting. Right now, we're in between. Some groups have M/CM identifier fields that fully indicate their nesting, yet they also use hierarchy to indicate that nesting. This is a bit of a "belts and suspenders" approach.

**Comment by JachymHercher** [comment]
> From one perspective, only the Notice is top-level.

Yes, if we mean the document as a whole. We don't model this, it is kind of implicit. It's worth noting, that BG-01 is called "Notice" a bit inaccurately, it is rather something like "Notice Metadata" or "Notice Basics". Would that be less confusing? 

> From another perspective, anything that uses identifier fields to indicate its nesting doesn't need to use hierarchy (+ signs) to indicate its nesting, and is therefore top-level.

I'm not sure I understand. The lot identifiers are not intended to indicate nesting (they exist with different numbers of "+"). Nesting is indicated only by "+", and as mentioned by @tinne, a higher number of "+" means they are within another BG (ignoring the implicit whole document, whole notice).

Concerning BG-330 and BG-709, they are nested within the _nearest BG above them with a lower number of "+"_, i.e. BG-6 (Procedure). Just because of semantics. Even though it's worth mentioning that BG-709 is also conditional on the value of a BT within BG-6. BG-330 is semantically close to the two BTs just above it, so that's why it's in BG-6. 

(To explicitly answer "Why are some groups considered top-level" - just because they are not in any other BG, nothing more... but that's probably not helping much.)

**Comment by jpmckinney** [comment]
Okay, so while, from a technical perspective, it's not required for e.g. Group Award to be nested under Procedure (as there is only ever one Procedure it can be about), it is nested for semantic reasons.

That being the case, as mentioned in an earlier comment, it seems like some BGs, semantically, further specify the procedure, like BG-02 (Purpose) ("Information about the purpose of the procurement procedure"), BG-704 (Reward and Jury), BG-701 (Exclusion Grounds), etc. yet they are not nested.

----

On the name of BG-01 (Notice), "Notice Metadata" would be clearer, but then others might feel that all the BGs are, in a sense, metadata. The description makes it more clear, so perhaps it stays as-is.

**Comment by JachymHercher** [comment]
There isn't a clear answer here. Procedures have notices, so everything in a notice is also implicitly about a procedure, in one sense or another. The idea is that BG-330 and BG-709 are semantically _closer_ than let's say BG-02 (Purpose), because of the reasons in https://github.com/eForms/eForms/issues/224#issuecomment-468766013.

**Comment by jpmckinney** [comment]
I'm satisfied with the levels as-is.

There are cases where a change in level would cause a loss of information (e.g. if BG-4 (Winner) were changed to "+", you would lose the link to the organization it details), and cases where a change in level would cause no loss of information (BG-330, etc.). An eventual implementation might want to distinguish between the two cases, but I think the current levels are good for understanding the relationships between BGs.

**Comment by JachymHercher** [comment]
Ok. To summarize, on the basis of this discussion, it's only necessary to add the business rule mentioned in https://github.com/eForms/eForms/issues/224#issuecomment-466481241.
