### ISSUE TITLE
BG-137 MULTIPLE; New business group instead of individual statistic fields

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#227]
There are presently 11 fields for tender statistics:

* BT-152 (Received Participation Requests)
* BT-146 (Received Tenders)
* BT-148 (Received Tenders SME)
* BT-1481 (Received Tenders Micro)
* BT-1482 (Received Tenders Small)
* BT-1483 (Received Tenders Medium)
* BT-147 (Received Tenders EU)
* BT-723 (Received Tenders Non EU)
* BT-741 (Received Tenders Inadmissible)
* BT-194 (Received Tenders Abnormally Low)
* BT-742 (Received Tenders Unverified)

These might be better represented as a new business group with:

* lot identifier (identifier, repeatable)
* statistic type (code)
* statistic value (number)

That is how tender statistics are modelled in OCDS: https://extensions.open-contracting.org/en/extensions/bids/master/

This makes it more flexible to add/remove statistics in the future, by simply changing the codes in the codelist.

----

The following might also be considered as a type of tender statistic, though they are used differently (e.g. in analyzing the price competitiveness of the winning tender):

* BT-710 (Tender Value Lowest)
* BT-711 (Tender Value Highest)

(There is one other statistical field, BT-712 (Review Requests), though it would require a different business group with a tender identifier.)

**Comment by jpmckinney** [comment]
One advantage of the current approach is that it makes it easier to specify statistics as mandatory; the same can be accomplished with the proposed approach using business rules, though I recognize that solution as being more complicated.

**Comment by JachymHercher** [comment]
What you propose would indeed make the standard shorter and more flexible. There will be some added complexity because of business rules, but overall your proposal probably makes things simpler. (Nb. this approach is somewhat similar to the BG-541 (Award Criterion Number)). 

Our first reflex would be to go for something like: 
- a repeatable mandatory BG "Received", containing: 
- a non-repeatable CM BT "Received Count" 
- a non-repeatable CM BT "Received Type" 

This BG would be nested within BG-137 (Procedure Lot Result), so it would not need a lot identifier of its own. Comparing this to the OCDS terminology, "count" seems more specific than "value"; "type" perhaps clearer (and more common in eForms) than "measure" or "statistic"? 

Concerning BT-710 and BT-711, we would have a tendency not to include them in the same batch, as they reflect a rather specific concept of "semi-anonymising" value by giving the values of extreme bids, which is a bit different. 

Concerning setting them as mandatory, this should not be a major issue. It is a legal obligation from the Directives and, for clarity, can be repeated in the description of the Implementing Regulation. Technically  it can indeed be done in the business rules.

**Comment by jpmckinney** [comment]
I think the proposed model is good. "Count" is more appropriate as these are all counts (whereas in OCDS the value of a statistic can be a percentage). "Type" is more appropriate as it is internally consistent with other BTs in eForms.

**Comment by paulakeen** [comment]
I would name the new BG "Received Tenders" and rename the inner property "Received Tenders" as "Received Tenders Total".

**Comment by jpmckinney** [comment]
@paulakeen I like the more specific terms, but they seem inappropriate for BT-152 (Received Participation Requests).

**Comment by JachymHercher** [comment]
"Received Tenders" is indeed inaccurate, but "Received" is too general. "Received Tenders Requests." would perhaps work better. ("Received Submissions" is another option.)

Based on the discussion above, we suggest the following: 


BG-712 | Received Tenders Requests | - | Yes | Information about the types of tenders or requests to participate received.
-- | -- | -- | -- | --
BT-759 | Received Tenders Requests Count | Number | No | Number of   tenders of requests to participate received.
BT-760 | Received Tenders Requests Type | Code | No | The type of   tenders or requests to participate received. A notice must inform at least   about the number of tenders received. A notice which is not about social or   other specific services must also inform at least about the number of tenders   received from small and medium enterprises, number of tenders received from   tenderers registered in other European Economic Area countries and the number   of tenders received from tenderers registered in countries outside of the   European Economic Area.

**Comment by jpmckinney** [comment]
I prefer "Received Submissions" as "Tenders Requests" is just a concatenation of nouns that is confusing.

**Comment by JachymHercher** [comment]
Ok, if there are no other opinions, we can suggest "Received Submissions". 

Based on #261, we will add "Tenders including variants or multiple tenders submitted (for one lot) by the same economic operator should be counted as one tender." to the end of the description of BT-759.
