### ISSUE TITLE
BT-555 (Subcontracting Proportion); Description; What is the number range?

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#228]
This might be the successor to BT-64 (Subcontracting Percentage). A percentage is typically expressed as a number between 0 and 100. A proportion, on the other hand, has many ways of being expressed, e.g. as a fraction "1/4", a ratio "1:3", a decimal "0.25" or a percentage "25%".

The Data type is Number, so the options are down to a decimal or a percentage. Can the description be updated to indicate which of the two is expected, to avoid e.g. "0.25" being interpreted as "0.25%" instead of "25%"?

**Comment by JachymHercher** [comment]
Saying "percentage" directly is indeed clearer.

Also, the description could perhaps do without "of the part", i.e. 

Estimated ~~proportion~~ _percentage_ ~~of the part~~ of the contract that the contractor will subcontract to third parties compared to the whole contract.

(Comparing BT-555 to BT-553 Subcontracting Value, "value of the part" is an equivalent to "percentage").

**Comment by tinne** [comment]
Let me suggest to instead use the neutral term “Subcontracting Ratio”.

Rationale: percentage is a simple mathematical notion to express ratios by the result of a division by 100. In practice, this is also used by fractional percentages, which is, ratios of that do not divide by 100 without remainder. Ratio is expression neutral and may be expressed by "0.25", "25%", or "250‰", likewise, so conceptionally, this is just a Number.

**Comment by jpmckinney** [comment]
My concern with a "neutral" term is that if different people put "0.25" or "25" or "250" in the same box, then it becomes a challenge to interpret the number. Did they mean 0.25%, 2.5% or 25%? "Percentage" makes interpretation unambiguous.

**Comment by JachymHercher** [comment]
We definitely need to be able to unambiguously specify what the value means. 

One option is to restrict the meaning to a single value - e.g. a percentage. Another is to allow multiple options and let the users specify what the number means (this is the approach taken for BT-542 (Award Criterion Number Meaning). 

For BT-542 we allow multiple options, because different buyers seem to have strongly established traditions on what number format to use. For BT-555, I don't think there's an established practice, so I would tend to agree with @jpmckinney and restrict it just to one option, a percentage. (This will also probably require a business rule.)
