### ISSUE TITLE
BT-195 (Unpublished Identifier); Description; Semantics of the field

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#231]
Does this identify the field (e.g. BT-720) or a specific instance of the field? For example, perhaps all but one lot's winning tender value can be disclosed, and the last lot's winning tender value can't yet be disclosed due to some issue raised by the winner.

If the former, then I imagine something like the BT-### identifiers can be used to identify fields.

If the latter, then it's not clear how the instances of fields will be identified. This is perhaps an implementation detail, but the spreadsheet should at least clarify whether it's fields that are unpublished, or specific instances of fields.

**Comment by jpmckinney** [comment]
Looking at the codelist clarifies that the former (identifying the field) is intended.

However, going back to my example, would it be possible for a notice to publish the winning tender values where possible, omit the winning tender value for one lot, and then use this BG to justify why that one instance of the field is not published?

**Comment by tinne** [comment]
Going back to the discussions in #70, it can indeed be the case that information is partially hidden.

With the simple example of https://github.com/eForms/eForms/issues/70#issuecomment-403518662 one would say that the BG-8 obviously belongs to the hidden winner. In a more complex case of two hidden winners for different reasons (does this really happen?) the modeling would jump too short. BG-8 would need to be added optional Lot Identifiers, Group Maximum Value Lot Identifiers, Winning Tender Identifiers, Award Criteria Identifiers (not yet existant), and Award Criteria Number identifiers (dito).

Oops. Hope I was missing something.

**Comment by JachymHercher** [comment]
Thanks for spotting. The non-publication was indeed supposed to refer to individual instances of fields, not all instances of a given BT. 

For the legal text, the solution is to revert the data type for BT-195 (Unpublished Identifier) from Code back to Identifier. Since identifiers can be complex and quite technical, the draft act defines them as a "set of information allowing unique identification", so the required details can be defined later. This  allows sufficient technical precision while not burdening the legal text with technical details.

For the technical implementation (eventually for @yvesjo), this set could consist of, as mandatory, the current codelist and then the identifiers mentioned by @tinne, which will need be mandatory if a relevant code is used and the field exists in multiple instances (to be covered by business rules).

**Comment by JachymHercher** [comment]
Note on implementation: The new BG-712 (Received Submissions) established in https://github.com/eForms/eForms/issues/227#issuecomment-475174175 also needs to have identifiable instances that will not be immediately published (e.g. when BT-760 (Received Submissions Type) = "Received Tenders Abnormally Low".)
