### ISSUE TITLE
BG-77 (Modification); Repeatable; Should be changed to "Yes"

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#232]
BG-9 (Change) is repeatable; I don't see why this BG (which is very similar semantically) isn't repeatable.

**Comment by tinne** [comment]
BG-9 was made repeatable in order to be able to give information about lot specific / and or independent updates - since BG-77 does not depend on lots, this information was understand to be regarding the notice as a whole (and thus non-repeatable).

cf. https://github.com/eForms/eForms/issues/72#issuecomment-431840567.

**Comment by jpmckinney** [comment]
Modification is with respect to contracts (which are in many cases related to specific lots). Contracts can be modified in different ways. I would expect one modification group per changed contract. It therefore should be repeatable.

**Comment by tinne** [comment]
I can only guess that is was modelled as a direct successor of form F20, which is lot- and contract-specific.

**Comment by jpmckinney** [comment]
If that's still the case, then this issue can be closed.

**Comment by JachymHercher** [comment]
Indeed, @jpmckinney has a point - this wasn't intentional, there isn't a reason to treat BG-9 and and BG-77 differently. 

Please note that both notices will rely on re-publishing the notices they change/modify. The purpose of the BGs above is to provide additional information (e.g. a reason for the change/modification). These reasons may be different per lot or contract, so they should both be repeatable.

**Comment by tinne** [comment]
@JachymHercher just to understand you correctly, did you just introduce a Modification Previous Lot Identifier?

**Comment by JachymHercher** [comment]
I don't think so, it was rather an ambiguous formulation, sorry. Change can be per lot and so has BT-13716 (Change Previous Lot Identifier), Modification can be per contract and so has BT-1501 (Modification Previous Contract Identifier).

**Comment by Rakwaak-FilipSvoboda** [comment]
Just to clarify, does repeatability of BG-77 mean that I would by able to inform about two or more time related modifications (with different BT-202 (Modification Description), BT-200 (Modification Reason Code) and BT-201 (Modification Reason Description)) in one form? Tha would be great.

**Comment by JachymHercher** [comment]
Yes, that is possible. 

We note that while the procurement directives do not give any explicit time limit for publishing the notice once the contract is modified, this time limit must still respect the principle of transparency. Unless specified otherwise in national legislation, we would recommend publishing them within 30 days (by analogy with the deadlines for publishing a contract award notice established by Art. 50(1) of Directive 2014/24/EU) and definitely in time to allow review within the six month time limit mentioned in Art. 2f paragraph 2 of Directive 89/665/EEC.
