### ISSUE TITLE
BG-9 (Change); No "Change Reason Description"?

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#233]
BG-77 (Modification) has BT-201 (Modification Reason Description). I'm wondering whether a corresponding field belongs in BG-9 (Change).

**Comment by tinne** [comment]
As far as I remember from the discussion (#47, #72), the change reason code list was considered exhaustive.

Do you see one or many codes where additional info would be needed or any “other” cases than those given in the code list?

**Comment by jpmckinney** [comment]
My question is why was BT-141 (Change Description) removed? I can't find the reason in those linked discussions.

**Comment by tinne** [comment]
Still do not understand, sorry. BT-141 exists (row 281), corresponds to BT-202, and answers the question, **what** was changed. BT-200/BT-201 in Modification and BT-140 in Change address the question, **why** it was changed.

**Comment by jpmckinney** [comment]
Sorry, I confused "Change Description" with "Change Reason Description" when trying to explain.

I would expect "The original notice is cancelled" to at least sometimes have a reason why.

**Comment by JachymHercher** [comment]
@jpmckinney, you ask for an equivalent to BT-201, i.e. Change Reason Description. The reason why it wasn't put there was because for a "prototypical" change (e.g. "Correction of one or more mistakes" and "Updated or additional information"), we didn't really see a reason. 

However, you are right that e.g. for "The original notice is cancelled" (and perhaps for other cases as well) this could be useful. Happy for more opinions, but in principle we could add it as an optional field.
