### ISSUE TITLE
Procedure Legal Basis; Missing codes from TED XML schema [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#234]
`t_legal-basis_PublicProcurement.xsd` has 33 codes. Are the additional codes no longer valid?

**Comment by JachymHercher** [comment]
Some will no longer be valid for eForms (e.g. the 2004 procurement directives), some are not included in the spreadsheet because they are not, strictly speaking, relevant in the legal context of eForms (e.g. Regulation 1370/2007 uses the same XSD as the current standard forms, but is not linked to the eForms Implementing Regulation and thus not included in the spreadsheets we share for the public feedback).

**Comment by jpmckinney** [comment]
Sounds good – closing if the proposed codelist isn't missing anything.
