### ISSUE TITLE
BT-10 (Activity Authority) / BT-610 (Activity Entity): No "Other" value [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#241]
The standard forms allow an "Other activity" value to be entered. There is no field in eForms to enter such a value.

**Comment by JachymHercher** [comment]
This is intentional. After some analysis, we concluded that these codelists are collectively exhaustive, i.e. there shouldn't be an "other" category. 

This holds also when looking at the data which people have submitted over the years under the text field linked to the "Other" category in the current forms. In essentially all cases, this was misclassification, because their subject fit in one of the other categories (most often "General Public Services", but there are also many case-by-case errors such as forestry not being put under environment, etc.)

**Comment by jpmckinney** [comment]
Sounds good to me! Is guidance anticipated to help avoid those errors?

**Comment by JachymHercher** [comment]
Hopefully yes.
