### ISSUE TITLE
Code Lists; Define code list name; [CODELIST]

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#244]
Taking a step back from tab “eFormsCodeLists” of `5_eForms_feedback_codelists_draft.xlsx`, I was somehow irritated by the non-uniformity of the  code list names. The original second consultation round is only a few month past, and I forgot, hence other might be confused as well.

In fact, there currently is no code list **name** list, only a list of business terms using the code data type. Let me suggest to derive and document code list names in order to ease discussions, make transparent (without Excel hyperlink analysis) that several business terms simply use the same code list as with country codes, and prepare for the technical implementation.

1. Make them all singular or all plural. My suggestion would be plural, so that the name defines the set as a whole.
2. Add or remove “Code” from the name in a uniform way. With plural chosen above, there should not be many reasons for confusion between codelist name and business term name, so maybe removal is more concise. Code list names ending in Type taste OK to me.
3. Disambiguate simple names where BT names are explained by hierarchical positioning, as with Technique (better: Procurement Techniques) or Unit (Physical Unit _or_ Unit of Measurement).

**Comment by JachymHercher** [comment]
Indeed, there are no code list names in the consultation. This was intentional, because we tried to keep only the necessary information and we considered code list name as somewhat secondary technical information, which can be discussed later. 

If you insist that it would make it easier to navigate the document, we can add it in a column in the first sheet with "Code list names". But please confirm. (Currently, you know which codelist is used where by going to the specific codelist sheet.) Alternatively, it will be possible to comment on the codelist names within the ontology discussions. 

1. @muricna
2. For codelist names, @muricna. (I would assume "code" would not need to be included.) 
For BT names, "code" is included only when it has some purpose. Specifically, for BT-514 (Organisation Country Code) and BT-5141 (Place Country Code) it's included for consistency with eInvoicing (see #50), in other cases it is to distinguish similar BTs where one is a "text"/"description"/"type" and another is a "code". 
3. I'm not sure I understand, I apologize. Is this linked to #236?

**Comment by tinne** [comment]
They exist implicitly as sheet tab names, so maybe better make them explicit.

Yes, this is partially a technical implementation issue, as it defines more vocabulary for it.

No. 3 is not linked to #236. I was just suggesting to make the code list names to be comprehensive enough (in an ontological sense) to make the names widely self-explanatory.

**Comment by muricna** [comment]
We will be using code lists published on EU vocabularies see https://publications.europa.eu/en/web/eu-vocabularies/authority-tables.  Therefore we do not have a choice on the names on the code list for example the code list for Country is Country as defined in the above link.  For new code lists in the domain of public procurement the name of the code lists is defined as lc-lc where lc is lower case in singualr format.

**Comment by JachymHercher** [comment]
@tinne - currently the sheet names are just the name of the first BT in which the codelist appears. We understand why they could be useful, but wouldn't say it's top priority. Consequently, we will include them in the next version of the spreadsheet - if time allows / if we have them ready by that time.
