### ISSUE TITLE
BG-703 (Organisation); Planning - Result; New Conditional Mandatory Field Rules

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#248]
The original annex 2 draft `20180604_eForms_consultation.xls` had mandatory Organisations fields (irrespective of the notice type and subtype)
- BT-500 Organisation Name
- BT-501 Organisation Identifier
- BT-513 Organisation Locality
- BT-514 Organisation Country
- BT-506 Organisation Contact Email Address
- BT-08 Organisation Role

Of these six, only the last one has retained being mandatory in the latest draft `4_eForms_feedback_Annex_Table_2_spreadsheet_draft.xlsx`, the other five have become CM.

What has changed? What are the business rules attached?

**Comment by JachymHercher** [comment]
As mentioned in https://github.com/eForms/eForms/issues/125#issuecomment-413482941, this was done because "Contact point" was added as a value to BT-08 (Organisation Role) and BG-703 (Organisation) with BT-08 equal to "Contact Point" was intended to be acceptable even when containing only a single mean of communication (only name, only address, only email, etc.) 

In the draft business rules, this is reflected in particular in BR-25: 

BR-25 | BT-08 | Organisation   Role | For each   Organisation (BG-703) where Organisation Role (BT-08) value is equal to "Contact point", Organisation (BG-703) must include Organisation   Contact Email Address (BT-506) or Organisation Contact Telephone Number   (BT-503) or Organisation Contact Fax (BT-739) or Organisation Internet   Address (BT-505) or (Organisation Name (BT-500) and Organisation Street Name   (BT-510) and Organisation Street Number (BT-511) and Organisation City   (BT-513) and Organisation Post Code (BT-512)).
-- | -- | -- | --

The logic is the same in the latest version of the proposal. Given the updates in BT-08 and BT-770 (Organisation Subrole) codelists discussed in https://github.com/eForms/eForms/issues/85#issuecomment-475609662, there should be some change to the business rules though. At least, "BT-08 is equal to 'Contact Point'" should be replaced by "BT-770 is equal to 'Organisation providing additional information about the procurement procedure'". Additionally, other values from BT-770 should also be included (e.g. "Organisation receiving tenders"). 

Since many of the sub-roles mentioned in #83 came from you, would you have any opinion/experience with that?

**Comment by tinne** [comment]
Thanks for the explanation. This certainly makes sense. Especially, I was missing BR-24. Still, both these have become optional, right?:
* BT-514 Organisation Country
* BT-506 Organisation Contact Email Address

By #83, you mean #85 as well?

**Comment by JachymHercher** [comment]
Both BT-514 and BT-506 are CM in the latest version of the proposal. (In the case of BT-506 it is, at least, because of BR-25; in case of BT-514 it is, at least, because the country could either be given directly or as part of BT-507 (Organisation Country Subdivision) ). 

No, just #85 :-). Corrected, thank you.
