### ISSUE TITLE
Technique; Mix of techniques, qualifiers, instructions [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#251]
The current codelist seems to mix a few different concepts.

I see a family resemblance between the following:

* Framework agreement
* Dynamic purchasing system
* Electronic auction

And it's possible to combine them ("Contract(s) awarded within a framework agreement or a dynamic purchasing system"). The e-Procurement Ontology also considers these three to be techniques.

The framework agreement and dynamic purchasing system can be further qualified as:

* open ("with reopening of competition", "also usable by buyers not listed in this notice")
* closed ("without reopening of competition", "only usable by buyers listed in this notice")
* both ("without reopening and partly with reopening of competition")

Meanwhile, there are also the instructions that:

* Electronic catalogue must be submitted with the tender
* Electronic catalogue may be submitted with the tender

While the current codelist is functional, it might be conceptually more appropriate to separate into different fields:

* the techniques (which I think are only the first three items I list)
* any qualifiers or modalities on those techniques (the second list)
* any instructions (the third list, which seems to be more like submission terms)

**Comment by JachymHercher** [comment]
Indeed, Technique is one of the larger codelists and perhaps there is a better way of structuring it. 

"Electronic catalogues" are essentially a "format of a tender" (Rec. 68 / 55 of 2014/24/EU), so you are right that it could be taken as a type of submission terms. However, our general approach to the Techniques concept has been to simply stick to what is listed in Chapter II* of Directive 2014/24/EU. In this case, we believe that following the Directive's terminology will lead to less confusion than taking another approach, even if it was slightly more intuitive. 

Concerning your proposal of "open" and "closed", I don't think the grouping under "open" and "closed" makes things clearer. 
- "Reopening of competition" means that the framework (as all frameworks) is closed to new companies, but that the companies which have signed the framework agreement will have a second round of competition. 
- The qualifiers for DPS and Framework agreements have different subjects - in the first case it is openness for new buyers; in the latter an extra procedural step (mainly for new companies). 

Concerning your general point on whether this should be split into two-three separate codelists, I'm also not sure whether it would really make things simpler. For example, if we had a "technique" codelist and then a "modalities" codelist (per each modality, i.e. not grouping them into "open" and "closed" for the reasons mentioned above), each modality would be usable only with one type of technique, which would need to be specified by several business rules. Isn't it simpler to just see them as sub-types of techniques and have one larger classification? 

___

*Chapter II includes "techniques and instruments" but uses the terms rather unclearly/interchangeably, see e.g. Rec 60 which says that "The instrument of framework agreements [...] is considered as an efficient procurement technique".

**Comment by jpmckinney** [comment]
I agree that splitting out a modality that only modifies one technique is unnecessarily complicated. We might instead focus on tidying the codes to be more comparable. I might suggest:

* Framework agreement, without reopening of competition
* Framework agreement, with reopening of competition
* Framework agreement, partly without reopening and partly with reopening of competition
* Dynamic purchasing system, only usable by buyers listed in this notice
* Dynamic purchasing system, also usable by buyers not listed in this notice
* Framework agreement or dynamic purchasing system
* Electronic catalogue, which must be submitted with the tender
* Electronic catalogue, which may be submitted with the tender

For the first five, I simply applied consistent punctuation.

I was confused by the sixth code "Contract(s) awarded within a framework agreement or a dynamic purchasing system." I assume that "Contract(s) awarded within a" could have been prefixed to the first five codes without a change in meaning. If so, then we can omit it from the sixth code.

The original "Electronic catalogue must be submitted with the tender" reads like a submission terms. My proposal reads more as a technique. For example,

> CAs have many techniques available, including: framework agreements without reopening of competition; electronic auctions; and electronic catalogues, which must be submitted with the tender.

makes more sense than:

> CAs have many techniques available, including: framework agreements without reopening of competition; electronic auctions; and electronic catalogue must be submitted with the tender.

All that said, Chapter II seems to cover joint procurement and central purchasing bodies, each of which are handled separately from the other techniques in eForms (and in the current standard forms), so I think there is flexibility to handle electronic catalogues separately, i.e. as a submission term.

**Comment by rantati7** [comment]
This gets even a bit more complicated after this comment:

First, this is a code list and within it there are "must publish a notice" and "may publish a notice" items. There is a must to publish a notice after awarding a contract within a DPS. This does not exit in FAs. 

Second, these "techniques" and "instruments" is a new categorisation that is not know to "general procurement public" and there may be some confusion in general wit all this.
- I can establish a FA by using an eAuction at the establishing stage. In could also (in addition to eAuction) request the tenderer to submit an eCatalogue. I think this is indeed what often happens. Buyer asks initial prices for the items to be eAuctioned in an Excel sheet (= a catalogues).
- After the FA has been established I can do the second stage by requestion the suppliers within the FA to submit me an eCatalogue and based on it I can start eAuction. 
- In DPS I do not see that eCatalogues would be used often (or at all) in establishing stage. Only ESPD questions are and can be used. So I do not request anything about products or services. Well I may have some minimum requirements but those are not vetted at this stage. However on second stage I may use eCatalogues and I could do eAuction as well.
- the directive includes this option of "picking from eCatalogue" which I do not think anyone understands fully. Is it a technique, Instrument or something completely different from how eCats are understood and used. I do not know... .

**My point:** eCats, DPS and FAs are not items that are on same level and I can use eCats within DPS or FA at first and also on second stage. Sixt code is indeed confusing also because it includes must publish a notice and may publish a notice options. I do not see how this would work on practical level

**Comment by tinne** [comment]
Regarding dynamic purchasing systems,
- in addition to the fact that there is not code for partial reopening competition, with DAP / result notices, it ultimately does no longer matter whether reopening competition had been reopened or not
- it matters whether the DPS is being terminated or not, so maybe the separate DPS Termination (BT-119) flag should be added to the information set under discussion.

**Comment by JachymHercher** [comment]
@jpmckinney 
- Drafting changes - generally better, except those below. 
- Concerning "Contract(s) awarded within a framework agreement or a dynamic purchasing system.", this is a very important distinction vis-à-vis the other codes. We distinguish between "setting up a FA/DPS" (in which case no contracts involving money are yet being signed) and "awarding contracts within these FA/DPS" (awarding contracts on basis of already established FA/DPS). 
- Concerning joint procurement and CPBs, rather than being modeled elsewhere than Techniques, they are not modeled explicitly at all. (Instead, they are covered implicitly, i.e. if there are multiple buyers, then the procedure is joint procurement/CPB, depending on whether there is also an organisation with an organisation role (BT-08) equal to CPB.) So so far, all the explicitly modeled Techniques are in one place. 
- (Your list omitted eAuction).

@rantati7 
Concerning the terminology, that's easily possible. However, the labels (nor the user interface) needs to use the eForms terminology, so an end user doesn't really need to ever see the word technique, if it's not a commonly used term for him. Instead, he could just respond to questions on FA/DPS/eAuctions.  
- You are of course right, but we're not sure if that's a problem. The decision of which notice must/may be published needs to be taken by the buyer; afterwards, he can mark the relevant notice from the point of view of its relationship with a given technique.  
- Similar to above - you are correct, but we're not sure it's a problem from an eNotification point of view. Essentially, all techniques can be combined in some way (e.g. FA within DPS), but BT-107 can have several values and there is no need to indicate their hierarchy/nesting/relationship...  

@tinne
- That's an interesting point. In the current proposal, we assume that a Result form would only contain the value "Contract(s) awarded within...", wtihout specifying the type of FA/DPS. If relevant for some type of re-use, the type could be taken from the previous notice. However, from an ease-of-use point of view, things may actually be easier for users if together with "Contract(s) awarded within...", the notices based on the Result form would also repeat the code of the technique which is being used, e.g. "FA without reopening". Would you agree? It might also be a bit more consistent. 
- BT-119 (DPS Termination) exists as a BT and not as a code just to be treated the same way as BT-756 (PIN Competition Termination).

**Comment by tinne** [comment]
Agree (two times).

**Comment by jpmckinney** [comment]
@JachymHercher Thanks for the clarifications.

So the first five codes are, implicitly, about setting up a FA/DPS, and the sixth code is about awarding contracts through a FA/DPS. Switching from a noun ("framework agreement") to a predicate ("setting up a framework agreement") suggests that this BT is less about referring to a technique (noun) and more about the particular stage of the application of the technique (besides mixing in a lot of other concepts as already discussed).

I note that at the March 5 eProcurement Ontology meeting, this Technique codelist / term was considered unnecessary. Instead, the outcomes from that meeting included:

1. A codelist for framework agreement type, to describe the framework as "with reopening of competition", etc.
1. A codelist for electronic catalogue usage, to communicate whether they are required, allowed, or not allowed.
1. A similar discussion as from @rantati7 about eAuctions and DPS. It seems like a couple indicator fields with loose semantics might be preferable to express the use of eAuctions (whether to set up an FA or award contracts in an FA) and DPS (whether used inside an FA or not).

For eForms, I think it makes sense to:

1. Have a BT about eCatalogue usage, likely in the Submission Terms BG, using a codelist like "Required", "Allowed", "Not allowed".
    * This information seems to be clearly relevant to the terms of submission.
1. Have a BT about the stage of the FA/DPS, likely in the Purpose BG, using a codelist like "This procedure or lot relates to establishing a new framework agreement or dynamic purchasing system.", "This procedure or lot relates to using an existing framework agreement or dynamic purchasing system."
    * This information seems to be clearly relevant to the purpose of the procedure or lot.
    * This can perhaps be more usefully modelled as a field that identifies the FA/DPS, in the case where an existing one is being used to award contracts.
    * I would find it surprising that a procedure would mix setting up FAs/DPSs and using FAs/DPSs in different lots; if that never happens, then this BT can instead go on the Procedure BG.
1. Have a BT about the framework agreement type, still in the Techniques BG, with the same three codes as in the current Technique codelist, 
1. Have a BT to indicate the use of electronic auctions, still in the Techniques BG.
1. Have a BT to indicate the use of dynamic purchasing systems, still in the Techniques BG.
    * Is it necessary to communicate whether unlisted buyers can use the DPS or not? The ePO meeting asked whether it was even possible for unlisted buyers to use the DPS.
1. Eliminate BT-107 (Technique) and the Technique codelist, as these are satisfied more clearly by the above.

**Comment by JachymHercher** [comment]
@jpmckinney Thank you, and thank you to all the participants in the relevant eProcurement ontology meeting, for the clarification and contribution.

We take note that the techniques codelist causes confusion and the recommendations should make things clearer. Concerning the individual proposals: 
1. Sounds good.
2. This does not seem as a good approach. 
    - "Purpose" is about what is being bought (CPV, description, value, etc.) The type of contract/technique used doesn't fit with this. 
    - I'm not sure I understand, sorry. May I ask you to perhaps reword it? 
    - It is quite unlikely, but one of the principles of eForms is to avoid being more restrictive than the directives. So as long as it is hypothetically possible, we would like to be able to model it. 

    Consequently, I would rather keep a value within the codelists mentioned under point 3 (e.g. "Contract awarded within an existing framework agreement."). In principle, no dedicated value is needed for contracts within DPS, because any Result form about a DPS will be about awarding a contract (or terminating the DPS, which is marked in BT-119 DPS Termination). 

3. Sounds good.  
4. Sounds good. 
5. Sounds good. 
    - Yes, it is possible, but only for CPBs. (This already exists in the current forms in field IV.1.3) of e.g. SF2 and is based on Art. 37(1) subparagraph 2 of Directive 2014/24/EU:

> "Where a dynamic purchasing system which is operated by a central purchasing body may be used by other contracting authorities, this shall be mentioned in the call for competition setting up that dynamic purchasing system."

6. Sounds good.

**Comment by jpmckinney** [comment]
Great! So for (2), I was trying to integrate the distinction between setting up a FA/DPS and using a FA/DPS to award contracts (viz. the old code "Contract(s) awarded within a framework agreement or a dynamic purchasing system.").

I assume this distinction needs to be preserved. I proposed a BT, but I understand that it is not the right approach. I'd be keen to hear other proposed approaches to communicate this distinction.

> This can perhaps be more usefully modelled as a field that identifies the FA/DPS, in the case where an existing one is being used to award contracts.

I am just suggesting that, if a procedure/lot is using an FA/DPS to award contracts, it might be useful to somehow identify that FA/DPS, or refer to the procedure/lot that established it.

**Comment by JachymHercher** [comment]
Concerning (2), we would suggest including this in the codelist (3), used for framework agreements. The description of the BT could be something like "Use of a framework agreement", the codes could be the following: 

- Framework  agreement without reopening of competition
- Framework agreement with reopening of competition
- Framework agreement partly without reopening and partly with reopening of competition
- Contract(s) within an existing framework agreement

(To ease re-use, the last code would have to be used together with one of the previous ones.)

Alternatively, if we wanted the codelist to be a bit more precise, it could be something like the below, but a priori, I'd say it's less readable and doesn't add much compared to the one above:

- Establishing or using a framework agreement without reopening of competition.
- Establishing or using a framework agreement with reopening of competition.
- Establishing or using a framework agreement partly without reopening and partly with reopening of competition.
- Awarding a contract within an already established framework agreement.

___

In eForms, the procedure/lot that "uses" a framework is the same one that "establishes" it (only at a different time, i.e. in a later notice). That is there is a direct link (they have the same procedure ID and lot ID), there isn't really a need for anything more. But maybe I've misunderstood your question.

**Comment by jpmckinney** [comment]
Thanks for the clarification – I didn't know the IDs would be the same.

I think it is simpler to have two BTs (one to indicate the type of the framework, and one to indicate whether an FA is being set up or is being used to award a contract), than to have one BT with more complex logic due to trying to express two concepts instead of one. This same reason is how we arrived at splitting BT-107 (Technique) into multiple BTs.

The only advantage I see to having one BT instead of two is that 1 is less than 2 – but having one more BT is not a big deal…

**Comment by JachymHercher** [comment]
Indeed, it can be done using an indicator (in the technique section?). This seems to be the approach in the ontology (as well as, by the way, the [initial eForms proposal](http://ec.europa.eu/growth/content/targeted-consultation-eforms-next-generation-public-procurement-standard-forms-0_en), back in 2016). 

For the record, declaring this explicitly actually isn't necessary, at least as long as there are clear business rules and documentation establishing the order in which notices should be published (1) "competition form", 2) "result form announcing the conclusion of a framework agreement", 3) "result form form announcing contracts within a framework agreement", 4) "same as 3", 5) "same as 3", etc. However, to make sure no problems arise (currently there are plenty) and to simplify re-use, I would say it's still useful to declare it explicitly.

**Comment by JachymHercher** [comment]
One more thing: one of the approaches in eForms is to require explicit declarations when certain things are not done (e.g. there is no strategic procurement). The reason is to avoid the current ambiguity when missing data is sometimes taken to mean "no/none" and sometimes is simply missing data. Consequently, in the above-mentioned codelist on techniques and DPS, we will also suggest the codes "No framework agreement" and "No dynamic purchasing system". 

(Note: forgetting to mark a framework agreement is a common mistake in the current forms.)

**Comment by JachymHercher** [comment]
In line with the discussion above, we will suggest the following changes to the proposal.

In BG-102 (Submission Terms)

BT-764 | Submission Electronic Catalogue | Code | No | Whether tenderers are required,   allowed or not allowed to submit (parts of) tenders as electonic catalogues.
-- | -- | -- | -- | --

In BG-706 (Techniques)


BT-765 | Framework Agreement | Code | No | Whether a framework agreement   with, without, or with and without the reopening of competition is involved.
-- | -- | -- | -- | --
BT-766 | Dynamic Purchasing System | Code | No | Whether a   dynamic purchasing system is involved and, in case of central purchasing   bodies, whether it can be used by buyers not listed in this notice.
BT-767 | Electronic Auction | Indicator | No | An electronic   auction is used.

In BG-310 (Contract)

BT-768 | Contract Framework Agreement | Indicator | No | The contract is awarded within a   framework agreement.
-- | -- | -- | -- | --
