### ISSUE TITLE
BG-702 (Selection Criteria); ANY; Criteria information structure

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#256]
Compared to the 2018 release, the data structure used to specify Selection Criteria has become more structured and farther aligned with the Award Criteria information set.

In comparing BG-702 and BG-707, I am wondering

- Why is there no such thing as an Selection Criterion BG (in analogy to BG-38)?
- If there are to be several (per-lot(-set)) selection criteria, are they to be given separately (with the same lot set)?

(Also, BR-151 has a Selection Criteria Used value of "Yes", which must be "Used", and BR-392 is missing the eForms BT ID (BT-40).)

**Comment by JachymHercher** [comment]
First off, please note that the best solution for informing about selection criteria in notices is to include/attach for publication the ESPD to a Competition form. In this case, BG-702 and other fields will not need to be filled in (see BR-373). Consequently, the selection criteria BG does not have the ambition to be a precise modelling of the selection criteria (systems which want to do that should use the ESPD), but rather a "minimalist" approach to be in line with the requirements in the Annexes of the Directives.  

- Concerning an analogy to BG-38, in essence, it is there. BT-747 (Selection Criteria Type) is analogous to BT-539 (Award Criterion Type), BT-749 (Selection Criteria Name) to BT-734 (Award Criterion Name), BT-750 (Selection Criteria Description) to BT-540 (Award Criteria Description), etc. 

    The only difference is that the selection criteria BTs can also be used to summarize several selection criteria at the same time. This is because the legal obligation is to provide information at the level of selection criteria "families" (e.g. "economic and financial standing"). 

    (Note: If a user _did_ want to provide information about every single selection criterion, and for some reason did not want to do it through the ESPD, then this would still be possible, because the codelist for BT-747 would also accept any value from the ESPD CriterionTaxonomy codelist.)  
- Concerning several BG-702 per lot, the answer is yes. In fact, every lot needs to have at least three BG-702 associated with it, one for each value of the BT-747. (See BR-405, which needs to be slightly reworded to make it clear that it is about an association per lot.) 
- Indeed, we will correct BR-151. 

There's at least one more note-worthy difference between award and selection criteria. For selection criteria, each "family"/criterion can be linked to one or more specific lots. In the case of award criteria, because of the repeatable BG-38, individual award criteria function as a set that needs to be linked to one or more lots as a whole. This is because we assume that individual award criteria need to be together (e.g. because of complementary weighting).
