### ISSUE TITLE
BT-06 (Strategic procurement); ANY; More information on strategic procurement needed

### ISSUE THREAD

**Issue by johannsenlars** [eForms/eForms#259]
Monitoring Strategic- as well as Green- Public Procurement (GPP) is a huge challenge for member states and of high importance for the collection of data as a basis for further efforts and a better regulation of GPP. 

So far, data on GPP is hardly available or only in a rudimentary state. For member states a good data basis on GPP is key to analyze the progress and to decide which further steps are necessary to improve efforts in GPP. The current procurement law allows procurers in several articles of the Public Procurement Directive to purchase products and services in a sustainable way. However, the EU and its member states do not know, if procurers act accordingly. Without data, the impact of GPP on the market cannot be estimated. The Federal German Ministry for the Environment, Nature Conservation and Nuclear Safety as well as the Germany Environment Agency would like to emphasize the opportunity to enhance the monitoring system under the current revision of the TED forms.

If the Commission asked procurers for GPP information through the TED, member states would be assisted enormously and also the EU could work with a first data basis. In addition, the questions would raise awareness for GPP in the procurement process. 

We are aware of the bureaucratic burden the electronic procurement may cause for procurers, which is why questions concerning GPP are to be designed as easy and in number as minimized as possible. Therefore we agree with the given multiple choice question regarding strategic procurement. However, if the answer is positive, there should be more options in order to increase the depth of the information gathered:
 

### 1)	BT 06 “Strategic Procurement”:
A technical specification, selection criteria, award criterion, or contract performance condition aims to reduce the environmental impacts of the procurement, fulfill social objectives and/or buy an innovative work, supply or service. (Y/N)

### 2)	Specification of the criteria (multiple choice)
a.	social criteria
b.	ecological criteria
c.	innovation criteria

### 3)	Stage of tendering procedure

**a.	Technical Specification**
i.	Did you ask for a Type 1 ecolabel or the corresponding criteria? Answer options: Yes [List of Type I Ecolabels]; No.
ii.	Did you consider the highest energy efficiency grade according to the EU energy efficiency label? Answer options: Yes; No.
iii.	Other (free text field)

**b.	Selection Criteria (Y/N)**
i.	Did you ask the buyer to comply with environmental management systems? Answer options: EMAS; ISO 14001; Other; No.
ii.	Other (free text field)

**c.	Award Criteria (Y/N)**
i.	1. Did you ask for the compliance with Type 1 ecolabels or the corresponding criteria? Answer options: Yes [List of Type I Ecolabels]; No
ii.	2. Did you consider life cycle costs? Answer options: Yes; No
iii.	3. Did you consider the energy efficiency performance of the product? Answer options: Yes; No
iv.	Other (free text field)

**d.	Contract Performance Condition** 
i.	Did you ask for a Type 1 ecolabel or the corresponding criteria? Answer options: Yes [List of Type I Ecolabels]; No.
ii.	Other (free text field)

**Comment by SellittoGiampaolo** [comment]
I completely agree 
monitoring GPP or strategic or innovative procuremnt over the years implied the necessity for additional questionnaries and campaigns.
The inclusion of at least some indicators in the notices would streamline the monitoring of these emerging sectors

**Comment by JachymHercher** [comment]
In the current proposal, 1) & 2) is covered by BT-06 (Strategic Procurement). 

``3)`` is not, mainly because of fear of administrative burden (and the resulting unreliability of data) - as discussed in https://github.com/eForms/eForms/issues/93#issuecomment-423913345. In other words, the question is not whether green, social and innovative procurement are important (they clearly are), but rather whether reliable data can be expected from users in these cases. @johannsenlars, @SellittoGiampaolo, could you perhaps share the experience you have had with the surveys? Were the submissions you have received reliable?  

On our side, we are not opposed to adding such fields as optional (optional at EU level; these can then be made mandatory at national/regional/buyer level), as long as at least one EU country brings up this requirement during the official procedure in the advisory committee on public procurement. 

From a technical point of view, there are several ways of modelling your requirements. For example, it could be something like the below, in which case it would require four new BTs:
- ``++`` repeatable BG on strategic procurement
- +++ BT-06  
- ++++ repeatable BG on "where and what"  
-  +++++ BT on the "where" (technical specifications, selection criteria, etc.)
-  +++++ BT with structured data on the environmental standards used (ISO 14024- Type 1 ecolabels;  EMAS; ISO 14001, etc.) 
- +++++ BT on what elements of green were considered ("highest energy efficiency grade according to the EU energy efficiency label"; "life cycle costs"; "energy efficiency performance of the product"). 
- +++++ BT for further textual information.

**Comment by maarikatork** [comment]
In Estonia we have been struggling with the same issue. We have actually collected the information whether green, innovative or social aspects have been ued in a procurement since September 2017. Buyers have to list whether any are used when starting a procedure in our central procurement register.

 With respect to innovative aspects we have introduced a short questionnaire to buyers. It consists of 5 simple yes/no answer questions : 
•	Did you acquire research and development activity in the scope of this procurement?
•	Was the object of the procurement novel for the contracting authority as well as for the whole market in general?
•	Was the solution procured in the scope of this procurement novel for the contracting authority?
•	Did the procured solution make the work processes at the facilities of the contracting authority more effective?

With regard to green aspects we have added to the system sample criteria by product groups. Criteria are based on EU green criteria which are adapted to local requirements. The plan is to make a regulation and obligation to government authorities to include at least 60% of criteria foreseen for certain product group. If selected the pocurement would receive a green procurement label in the e-procurement system.

At the moment we obviously cannot add these to the notice (they are listed in our system)  but it would useful if we could.

**Comment by johannsenlars** [comment]
@JachymHercher , thank you for your statement.

As I wrote, the additional questions in part 3) are being brought up because we were asking ourselves the question of what can be monitored by having only the questions 1) and 2).
Without further knowledge about what procurers perceive as social, ecological or innovative criteria and what is being implemented into the tenders, lots of questionmarks remain.
Having a reliable data basis helps to identify where gaps need to be closed and where work towards strategic procurement needs to be directed to.

For the implementation into the eforms, we can think of several ways.The approach you mentioned seems suitable for us as it clusters strategic procurement at one spot of the eforms.

Also, the questions could be categorized directly into the respective groups if this approach is better suited:

BG 44 Price
BG-702 Selection Criteria
BG-711 Contract Terms
BG-38 Award Criterion
[...]

**Comment by JachymHercher** [comment]
@maarikatork thank you for the examples, very interesting. Few questions:
1. Did you consider something like "Was the solution procured in the scope of this procurement novel for the contractor"? Wouldn't this also be relevant for measuring innovation?
2. Did you consider something like "Was the solution procured in the scope of this procurement novel world-wide?" Wouldn't this also be relevant for measuring innovation? (Or is it too rare?) 
3. Did you consider something like "The technical specifications were primarily based on functional and performance requirements, not on describing the technical solution." Wouldn't this also be relevant for measuring innovation?

We note you collect this data already at national level, so it would be useful to be able to include it also in TED notices. Concerning the environmental criteria, if we understood it correctly, your system suggests the sample green criteria to the users. If they then decide to use them, they would include them in a notice the same way as any other criteria. That means no additional field is needed in eForms for this purpose. Is that correct?

**Comment by maarikatork** [comment]
The questions on innovation were worked out by the Ministry of Econimic Affairs who is responsible for promoting innovation in the country. No 1 question you suggest it interesting but difficult for the Buyer to answer. No 2 question is even more difficult to answer - who knows waht is going on in the whole world? No 3 question might be useful.

Concerning GPP, the sample criteria concern the object of the procurement, i.e. techical specification. These criteria are not included in the notice. Selecting the sample criteria help Buyers with the notion of GPP and enable us to highlight such procurements in our register.

**Comment by JachymHercher** [comment]
Based on the discussion above, we have added several (optional), more detailed fields to the draft eForms. They are not as detailed as what was requested above, but still go into more detail than the original proposal. Because of time constraints, we were regrettably not able to discuss them here in more detail before adding them in to the proposal, sorry for that. 

We welcome any clarifications/comments in this thread, but please note that they are purely for information. If you would like them to be reflected in the proposal, please communicate them to your representative in the advisory committee on public contracts.  

BT-774 (Green Procurement)
"An   approach (e.g. referring to an environmental label) to reducing the   environmental impacts of the work, supply or service used in the technical   specifications, award criteria, selection criteria or contract performance   conditions."

Codelist: 
    - Referring to an environmental label
    - Referring to an environmental   management system
    - Considering the environmental   impact during the whole life-cycle
    - Considering energy efficiency
    - None

BT-775 (Social Procurement)
"Any social objectives (e.g. fair working conditions,   professional integration of the long-term unemployed) promoted by the   technical specifications, award criteria, selection criteria or contract   performance conditions."

Codelist: 
    - Professional integration of the long-term unemployed, disadvantaged and/or of persons with   disabilities
    - Accessibility for all
    - Fair working conditions
    - Human rights protection in value chains
    - Gender and ethnic equality
    - None

BT-776 (Innovative Procurement)
"An indication that innovative works, supplies or services are   being bought (e.g. the procured works, supplies or services being novel for   the whole market; the technical specifications being primarily based on   functional and performance requirements)."

Codelist: 
    - The buyer intends to procure works, supplies or services that are novel for him.
    - The buyer intends to procure   works, supplies or services that are novel for the whole market.
    - The technical specifications   are primarily based on functional and performance requirements, not on describing the technical solution.
    - The procured works, supplies   or services involve research and development activities.
    - The procured works, supplies   or services are likely to make the work of the buyer more effective.
    - The procured works, supplies   or services are novel for the buyer.
    - The procured works, supplies   or services are novel for the whole market.
    - None
