### ISSUE TITLE
BT-63 (Variants); Description; Allowance of multiple main offers

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#261]
Recent changes in German below-threshold construction notice jurisdiction (VOB/A 2019) demand that buyers can in the procurement documents declare that one seller cannot submit more than one main offer to a procedure.

This seems to have been a popular method to circumvent situations where buyer forbade to send variants (according to German law, variants are only variants when they are declared as such and use a special “procument documents attachment“), so popular that notice specialists decided to add the information to the VOB forms (121 and 122) themselves:

“More than one main offer
- [ ] allowed
- [ ] forbidden”

To support this offer, kindly consider extending the the variant code list or add a second indicator business terms accordingly.

Cf., [“Numerous offers of the same buyer: risks and chances (in German: Mehrere Hauptangebote desselben Bieters: Chancen und Risiken”, VDNW Vergabeblog](https://www.vergabeblog.de/2013-12-01/mehrere-hauptangebote-desselben-bieters-chancen-und-risiken-olg-muenchen-beschluss-v-29-10-2013-verg-1113/)

**Comment by JachymHercher** [comment]
Thank you for bringing this up. Indeed, we knew about this possibility, but we were not aware that it is anything more than marginal.

Adding a new BT seems to be the best approach. Should this be an indicator ("A tenderer may submit more than one tender (for a given a lot).") or is there any chance that there could be a specific number of maximum tenders ("Maximum number of tenders which a tenderer can submit (for a given lot)."? 

Given it's similarity to BT-63 (Variants), the new BT could go into Purpose (BG-02). However, since it is about submission, we suggest putting it in Submission Terms (BG-102). (It could not go to into BG-6 (Procedure), because the new BT could hypothetically be different per lot.)

**Comment by tinne** [comment]
Introducing an _indicator_ into BG-102 (Submission Terms) is fine for me.

Did you consider moving BT-63 (Variants) to BG-102 as well, as I can well image that variant offers might only be desirable to some lots as well?

Received Tenders - OK, although I seem to remember you introduced a new Received-BG for it. (The sentence would then go to the Received Type code list, would it not?)

**Comment by paulakeen** [comment]
Right now, in the ontology the variants are modelled like this:

![Variant](https://user-images.githubusercontent.com/16134316/54590542-a0e4b080-4a28-11e9-8272-d15ccda576dd.png)

However, during the last F2F in Luxembourg, when analysing the eSubmission we raised the question of whether the Variants should not be represented with a class that keeps links to lots and has its own attributes. This discussion was opend just before ending the F2F Workshop, so it will be continued when starting the analysis about the eSubmission with the WG.

**Comment by paulakeen** [comment]
About my last comment: as I explain this subject is still under discussion, but I clearly see that the "Variants Permission" or a possible future class "Variants" is a "Submission Terms" as it is obviously related to what the tenderer may or may not submit.

In the ePO, both if we end up having a class "Variant" or not this concept will be always linked to Lot, which is noticeable in this diagram, where the "Variants Permission" attribute has been moved into the class "Submission Terms" (which maps the eForms BG-102 and which would be my suggestion for the ePO, btw):

![image](https://user-images.githubusercontent.com/16134316/54810532-a17a8280-4c86-11e9-85a4-477b6f96bf2b.png)

**Comment by JachymHercher** [comment]
Based on the above, we will propose:
- Moving BT-63 Variants into BG-102 Submission Terms. (I'm not 100% satisfied with this approach, because for me variants are more important in describing "what to deliver" rather than "how to submit", but there is a bit of both and probably there isn't a perfect solution.) 
- Creating a new BT-769 (Multiple Tenders) with a description of "Tenderers may submit more than one tender (for a given lot).", also in BG-102.

**Comment by AHenselCsx** [comment]
Found this discussion when researching the juridical meaning of BT-769. 
If this discussion is the origin, BT-769 should state "Tenderers may submit more than one non-variant tender (for a given lot). ..". 
Usually when variants are allowed, there is no limit of the number of variant tenders.  


Or are there better english terms to differ between
- the envelope with the tenders (including zero, one or many non-variant tenders and zero, one or many variants)
- a (specific) tender not regarding if that is a variant or not
- a (specific) variant tender (German: "Nebenangebot"; )
- a (specific) non-variant tender (German: "Hauptangebot")
