### ISSUE TITLE
eForms code lists contain different values than the ones in the ontology [CODELIST]

### ISSUE THREAD

**Issue by VibekeE** [eForms/eForms#263]
An example is “Procurement procedure type” where the code list in eForms differs from the ontology BT 105. Another example is “Selection criteria  type” where the code list in eForms opens for using more detailed values from the taxonomi that what is given in the four defined codes. The ontology on the other hand, is more detailed (BT 747). It is needed with a systematic and authorised mapping on to which each code can be mapped.

**Comment by paulakeen** [comment]
Dear all,

What I do not understand is why eForms does not use the codes being maintained by OP, some of are supposedly aligned to the ones defined in [ESPD](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.0.2.xlsx)(see tab CriteriaTaxonomy). This should be the case for both the procedure type and the criteria type. In case of discrepancy we should see why there's such discrepancy and make an agreement. Should we not?

**Comment by JachymHercher** [comment]
Concerning Procedure Type (BT-105), it seems the codelist in the ontology has not been updated yet. (TBC by @muricna) 

Concerning Selection Criteria Type (BT-747), this is a bit of a special case (as indicated in the "additional information column" of the codelist). We are, in principle, re-using the CriteriaTaxonomy codelist. However, there is a business rule (BR-405) which sets that three values are more important than others. Since eForms needs to cater also for non-technical readers, and since we assume that 98% of users will _not_ use anything more than this subset, in the draft codelist document, we have presented this by listing only the relevant three criteria (+ "other"). We will think on how to also present this more clearly in the future. 

Concerning the general approach, eForms' codelists are indeed created together with OP. Discrepancies may occur e.g. because the OP's codelists reflect the previous forms, but not the eForms' proposal. Discussion and agreement is indeed on the order of the day - that is exactly the purpose of this public feedback and the GitHub issues.
