### ISSUE TITLE
General; eForms challenges for  nation-wide CPBs

### ISSUE THREAD

**Issue by AnnaLarssonSKI** [eForms/eForms#266]
Initially we would like to say thank you for providing the possibility for us to review and comment on the proposal. We generally agree with several of the issues previously expressed by the users @karinmorild, @rantati7 and @UHMYND, however we would also like to add the following.

The requirement to submit information regarding e.g.:

- purpose lot identifier (BT-137), 
- received tenders SME (BT-148)
- organisation (BG-703 and BT-08), specifically with regards to winners
- contract terms (BG-711 and specifically BT-70)

constitutes a significant administrative burden, at least for nation-wide CPBs. It is not uncommon for a nation-wide CPB to award framework agreements to more than 300 suppliers/contractors or to divide a framework agreement into thousands of lots. For example, in Sweden one procurement procedure could be divided into several different categories and additionally into lots depending on geographic location. For example, Sweden has 290 municipalities. A procurement procedure that has 10 categories (of services or goods) multiplied by 290 (municipalities) adds up to 2.900 lots. The administrative burden that comes with the eForms in this regard might cause nation-wide CPBs to refrain entirely from using lots, or to decrease the number of lots used in each procurement procedure. This might have a negative effect on the possibility for SMEs to participate in procurement procedures conducted by nation-wide CPBs.

**Comment by SellittoGiampaolo** [comment]
Here the transition towards eProcurement (and eForms) should help CPBs in streamlining the overall process and in the management of such a multiplicity of suppliers and offers.
In the case of framework agreements we (in Italy) have the CPB define the Framework agreement as such (and it may be comprised of macro-lots, corresponding to categories or to geographical areas), while the information about the lots is inserted by the municipalities that use the framework agreement when they order goods or services.

**Comment by JachymHercher** [comment]
@AnnaLarssonSKI, thank you for your comments. We are aware of the scale of the procedures run by large CPBs and we understand the significant challenges this brings. At the same time, as far as the procurement directives are concerned, the same standard of transparency must be respected regardless of whether a procedure is big or small, done by a CPB or another buyer, etc. 

Generally speaking, the most important step in solving this problem is to recognize it as mainly a technological question, not a question of human effort. In other words, to easily publish notices for such large procedures, it is necessary to have integrated e-tendering systems. These systems copy information between different stages of the procurement procedure, allow submitting information about several lots at the same time, etc. At the end of the day, running such large procurement procedures by itself requires a lot of information management, and the publication of notices is just a question of how to take the existing information, process it and copy it into a notice.  

(In this context, it is worth emphasizing that eForms are simply a data storage structure - they are not a paper form to fill, they are not a description of how the form-filling interface should look nor how the information should be presented to companies and citizens.) 

To use the examples you give, it is not technologically complex for an e-procurement system to have functionalities such as adding hundreds of buyers with a single click. These could be based on information in the system (e.g. a predefined list of all municipalities / all hospitals  / all buyers in a given region, etc.), taken from previous procedures, or uploaded ad-hoc (e.g. as a spreadsheet). Similarly, making 10 categories and then selecting "make a copy of each category per each item on a list of NUTS codes / municipalities / XYZ" is also not hard. The only requirement is for end-users to be in contact with the system's designers and ensure it does what they need.

Concerning the requirements you mention, we are not quite sure why eForms would make the situation more problematic than it is now (on the contrary, their better technology should make it easier to have good IT solutions). Specifically, all of the fields you mention are already legally mandatory in the current standard forms...
- Purpose Lot Identifier (BT-137) is the same as the Object "Lot No" (see section II.2. of the contract notice)
- Received tenders SME (BT-148) is the same as the "Number of tenders received from SMEs" (see V.2.2 of the contract award notice)
- Organisation (BG-703 and BT-08), specifically with regards to winners, is the same as "Name and address of the contractor" (see V.2.3 of the contract award notice) 
- Contract terms (BG-711) and specifically Terms Performance (BT-70) is the same as "Contract performance conditions" (see III.2.2 of the contract notice).
