### ISSUE TITLE
BG-102 (Submission Terms); ANY; Incomplete submission reaction

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#267]
Recent changes in German below-threshold construction notice jurisdiction (VOB/A 2019) demand that buyers must preliminarily accept incomplete submissions provided it has not declared otherwise and must explicitly request the bidder to provide them later.

This regards “missing, incomplete and erroneous bidder-related documents, especially declarations, information and records of evidence”. Our construction notice specialists thus added the topic to the VOB forms (121 and 122) as follows:

#### “Additional Demand
Missing documents that had to be submitted with the offer will
- [ ] be demanded later
- [ ] not be demanded later
- [ ] partially demanded later - the following documents: (provide list)”

To support this, kindly consider adding appropriate business terms to the Submission Terms section.

**Comment by SellittoGiampaolo** [comment]
The possibility to amend missing incomplete and erroneous bidder related document is admitted also in Italy

**Comment by JachymHercher** [comment]
Two clarification questions: 
1. The quotation and @SellittoGiampaolo only regard bid**der**-related documents, while the suggested field seems to cover the whole bid (?). Is the scope only about bidder-related documents?
2. Does this field have any use if the ESPD is used? (At first sight, I would assume that all bidder-related documents would fall under exclusion grounds or selection criteria, so they would be covered by the ESPD. Or could this also apply to other purely administrative information such as bank account etc.?)

The need you mentioned could be resolved by adding a BT with data type code, with a codelist along the lines of 
- "all missing documents will be requested later"
- "some missing documents will be requested later", 
- "no missing documents will be requested later". 

If "some" is selected, then there could be a free-text BT on "Additional information about requesting missing documents." Theoretically, this could perhaps be a codelist of types of different documents. However, I'm doubtful such a classification is easy to make, especially across borders. Furthermore, I'm guessing more detailed explanations than just a classification may be necessary?

These BTs should probably go into BG-102 (Submission Terms)? (The more general BG-100 Communication would be another option.)

**Comment by SellittoGiampaolo** [comment]
"bidder related document"  means that amendments can only be accepted or requested for  “missing, incomplete and erroneous bidder-related documents, especially declarations, information and records of evidence” but not for other parts of the bid, e.g. if the bidder does not report the vaue of his bid, this cannot be amended later, after the evaluators open the offer.
So the scope is the whole bid but only in  the parts that regard qualities of the bidder or payments (the insurance) and the like but not for the part qualifying the bid. 
This field is useful even in the case an ESPD is used, since the offer is not composed only of the ESPD.
Moreover, the evaluators can ask to submit an ESPD in the  case it is not present in the offer.  however it depends on the evaluating commission.... usually they give a sharp deadline to amend any inconsistency in the ESPD or in other documents. One error in the ESPD that happens rather frequently is the declaration of absence of ground for exclusion related to other subjects that have power to represent the OE (not only to the legal representative).

**Comment by tinne** [comment]
The documents referred to by §16a VOB/A 2019 indeed refer to documents in direct connection with requests for participation and offers.

ESPD is not currently being used but anyway this might include certifications by third parties (e.g., of compliance or regarding a not-yet-integrated national ESPD equivalent).

The code list field and an explanatory text (if the answer is some) seems appropriate, where the explanatory text normally names specific documents but might also give further reasoning. A cross-border document qualification and enumeration system seems too far-fetched.

The law states that prices may never been requested later, but allows the buyer to explain on it or not. Request deadlines are strict as well and might well been added as another BT (they are not currently foreseen, but this seems plausible from the text).

**Comment by JachymHercher** [comment]
Based on the discussion above, we suggest the following. Happy for feedback on whether the wording is ok (in particular "possibility to submit" vs. "obligation to request"). 

BT-771 | Late Tenderer Information | Code | No | Whether tenderer-related   information can be supplemented even after the submission deadline.
-- | -- | -- | -- | --
BT-772 | Late Tenderer Information Description | Text | No | Description of   the tenderer-related information which can be supplemented even after the   submission deadline.

The codes for BT-771 should be: 
- "All missing tenderer-related documents can be submitted later."
- "Some missing tenderer-related documents can be requested later",
- "No documents can be submitted later."

**Comment by paulakeen** [comment]
@muricna new input for the ePO, too. Thanks!

**Comment by tinne** [comment]
Thanks for the addition.

Does the ticket need to be added to the Spreadsheet Update milestone?
