### ISSUE TITLE
BT-several; ANY; Comments on several BTs

### ISSUE THREAD

**Issue by kozbeszerzes** [eForms/eForms#268]
1. Physical availability of the contracting authority as an optional item in the draft - we propose to make it compulsory in the light of the directives’ regulatory requirements.

2.	 In the new notices, the Internet address is optional only, however, according to the directives, these are mandatory, so we recommend that the optional condition be changed to mandatory.

3.	"Winning tender": we recommend that provide the tax number / tax ID in the mandatory field for winning bidder.

4.	We suggest that the "Unit" field should not be a "Code" type, in which case it is possible to choose only the predefined types and the unit of measurement not included in it can not be provided by the contracting authority - the code list would remain independent, but it should be possible including fixing units not included in the list by the contracting authority.

5.	”Modification": we suggest that the original and modified contractual values be included as mandatory.

6.	"Change": Totally missing the correctional modification (the notice was published differently in TED as it was sent), so we recommend adding the correction data content.

**Comment by paulakeen** [comment]
Some comments:

**About point #2**: I guess you refer to the "Winner Organisation Identifier". Person Identifiers (natural or legal) should not be reduced to only one, especially if they are relevant parties as it is the case. And that is what the eForms suggest in column "E" (Repeatable = "YES"). This catters to specify any kind of identifier you need, included the VAT number where that is possible (I imagine that AT, and maybe SE, are two of those MS where this could be a problem). Technical implementations such as the ISO 15000-5 CCS (ebXML Core Component Specification) are used precisely to provide basic component (i.e. IdentifierType) with a rich set of attributes (schemeID, schemeAgencyID, schemeVersionID, etc.). This cum a consistent identification policy should do the work (e.g. [PEPPOL](https://peppol.eu/wp-content/uploads/2017/12/PEPPOL_Policy-for-use-of-identifiers-300-11_certificates.pdf), [eIDAS](https://ec.europa.eu/digital-single-market/en/trust-services-and-eid), other).

**Comment by JachymHercher** [comment]
1. I apologize, I'm not sure I understand which BTs you mean. Is it BT-510 (Street Name) etc.? 

2. There can be buyers and companies which do not have a webpage (similarly to not having a fax number), which raises questions about whether these should be mandatory. If you think this isn't a problem, could you please mention it in the link given in https://github.com/eForms/eForms/issues/200, point 2? 

3. This is already the case - the information is mandatory in BT-501 (Organisation Identifier). 

4. Please see https://github.com/eForms/eForms/issues/200, point 16. May we ask you what types of values you believe wouldn't be covered by the codelist but would be important for the authorities?

5. Both the original and modified values will be available, because the notice will essentially be republished. Please see https://github.com/eForms/eForms/issues/200, point 17.

6. This is covered by BT-140 (Change Reason Code), please see https://github.com/eForms/eForms/issues/200, point 18. Also, please see the slight changes to the code suggested in https://github.com/eForms/eForms/issues/247#issuecomment-470954681.
