### ISSUE TITLE
BT-1251 (Previous Planning Part Identifier); Description; How are parts identified?

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#269]
The description is:

> Identifier of a part of a prior information notice, a periodic indicative notice or another similar notice related to this notice.

1. I can't find a corresponding BT that can be used on a PIN to identify its parts. How do the later notices identify the different parts of a PIN?
1. The BG has level "+", i.e. only the notice as a whole can refer to PINs. However, would it be useful for individual lots on a CN to be able to refer to different parts of a PIN?

**Comment by jpmckinney** [comment]
By 'tenders', do you mean 'procedures'? At any rate, it's not clear what 'part' means in the description for this BT ("Identifier of a part of a prior information notice …").

**Comment by tinne** [comment]
By tenders, I mean tendered ‘objects’ in the sense of the full current form section II), yes.
In #7 it was discussed that part is a stand-in for both a single PIN object (regarding a pre-eForms procedure, as they will stop to exist) or a PIN lot, as the PIN lot set might be subset or rearranged prior to creating the CN.

**Comment by JachymHercher** [comment]
1) As mentioned in #7 and #55, a "part" is indeed "something that may become a procedure or a lot in a procedure". We need this because when the "PIN only" is being published, it may not yet be known which it will be. However, it's true that this needs to be clarified. We suggest using the term "part" and changing the definition of all the lot identifiers along these lines:

    > "The identifier of one or more lots within the procedure _or, in case of PINs used only for information, of one or more parts of the notice, which may later become lots of a procedure or a self-standing procedure._"

    We considered also two other alternatives, but rejected both: 
- Do not use the word "part", just the word "lot" and add an explanation that "In case of PINs used only for information, a lot may become a self-standing procedure". After consultation with some of our lawyers, this seemed more confusing. 
- Instead of the word "part" use the generic word "procurement". "Procurement" is already now sometimes used in the meaning of "lot or procedure", so this would add some consistency. However, the explicit meaning of "part" would be lost and "procurement" may also mean plenty of other things, so this also seemed more confusing in the end. 

2) You're right, it is better to be able to link individual lots to individual PINs, not just the whole procedure. We will add a lot identifier and clarify BG-125  

> Information about a prior information notice, a periodic indicative notice or another similar notice related to this ~notice~ _procurement_.
