### ISSUE TITLE
BT-70 (Terms Performance) and BT-77 (Terms Financial); description; what is to be provided here?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#27]
Both seem to be text fields. These are provided in terms and conditions hence is there a need to duplicate the information here?

**Comment by JachymHercher** [comment]
Just to be sure: by "terms and conditions" you mean a part of the procurement documents or a draft contract, i.e. outside of the notice, correct?

This information must be in the notice according to e.g. 2014/24/EU Annex V Part C Point 17; 2014/25/EU Annex XI Section A Point 14 & 18. 

Arguably, summarizing this information in the notice (instead of having it only in the procurement documents or a draft contract) is useful, because it can be crucial for economic operators to quickly decide whether to investigate the procurement procedure further or not. For example, unfriendly financing conditions can right away signal to a small company that participating in this procedure wouldn't make sense.
