### ISSUE TITLE
BT-142 (Awarded); Data type; Single CN resulting in multiple CANs

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#270]
My understanding is that multiple CANs can follow a single CN, if, for example, different lots are awarded along different schedules. I am unclear, however, about whether/how results should be repeated across CANs.

For example, let's say I have three lots; the award of the first lot is announced in a first CAN, the award of the second lot is announced in a second CAN, and the third will not be awarded.

1. In my **second** CAN, do I need to include a BG-137 (Procedure Lot Result) for the first (already awarded) lot? If so, then repeating the values from the first CAN might introduce accidental discrepancies and might confuse analysts, e.g., in terms of determining the date of the award. It might be preferable, in this scenario, to instead only identify the lot with BT-13713 (Result Lot Identifier) and use a code in BT-142 (Awarded) to express "The winner was announced in a previous notice." Data users would then know to refer to an earlier CAN for full details.

1. In my **first** CAN, do I need to include a BG-137 (Procedure Lot Result) for the second (not yet awarded) lot? If so, as above, BT-142 (Awarded) might need to be a codelist rather than a boolean indicator, as I need to be able to express "An award decision has not yet been made."

The other codes in the codelist might be: "The winner is announced in this notice." (used in my first CAN for my first lot) and "No award will be made." (used for my third lot).

Another option (assuming it is legal) is to not include a result for a lot in a CAN if it either hasn't yet been decided or has previously been decided. In that case, the BT can remain as-is.

**Comment by tinne** [comment]
This is not a new subject in eForms, but is also not cleanly documented with the current forms (which you might not be using in Toronto, might you?). We currently operate this in aggregative form, adding information from CAN to CAN, until the last declares information about every lot involved. Issue 1 (accidental discrepancies) could in my humble opinion be addressed by automatic data take-over. (Regarding 2., a not-yet-decided-on lot is simply left out.) Also, larger corrections are currently being done not by means of a correction form but by issuing a new CAN notice, thus it could include implicit corrections on earlier awarded lots (with eForms, a BG-9 Change section could provide more info).

However, I'd love @eForms to clear this up and find means of documenting the issue.

**Comment by JachymHercher** [comment]
Multiple CANs can follow a single CN (even if it is not a framework agreement, DPS, etc.). Typically, a CN would lead to multiple CANs if different lots are awarded more than 30 days apart (which is the deadline established in Art. 50(1) of Directive 2014/24/EU). This can happen, for example, if the lots are very different (e.g. evaluated and signed by different buyers), if one of the lots is appealed, etc.

The current approach is that a CAN is published only for the lot where a positive or a negative decision has been made. In TED, these CANs do not "cumulate" lots (even though some version of that could be done by using corrigenda*). (@tinne - when you said "we", you meant certain German national notices?) 

There are two problems with the current approach: 
- People forget to publish notices about the lots they have not awarded (and there are no business rules to solve this, because it is not possible to declare the difference between "not awarded - ever" and "not awarded - yet"). 
- There is a missed opportunity to be more transparent, because even though a notice is published, it does not say anything about the status of the other lots. 

Consequently, changing BT-142 (Awarded) to a code seems like a good idea. The codes could be:
- The winner is announced in this notice.
- The winner was announced in a previous notice.
- The winner was not yet chosen, but the competition is still ongoing.  
- No winner was chosen and the competition is closed. 

The description of BT-142 should probably also be changed, to something like "Whether the winner has (already) been chosen." 

We should also add a business rule that each CAN must inform about the status of all lots. 
___

\*It would perhaps be possible to enforce that every CN must result in only one CAN, in which case lots to be awarded later would be published through the "Change" notice. However, I'm not sure this would greatly improve anything and publishing a "change notice" when I have signed a new contract might rather be somewhat confusing. Also, the law says "publish a CAN", not "publish a change notice of a CAN".

**Comment by tinne** [comment]
@JachymHercher Take the example of three lots, no 1 and 2 have already been decided an, no 3 is still open due to an appeal. At the latest after the time mentioned the buyer publishes a CAN with info on lots 1 and 2. Now different things can happen, a huge change for some reason on an already published lot, or info on the result of the appeal on lot 3. When I was writing we, I was discussing software based guidance. Currently buyers are offered a correction on the first CAN (creating a F14 notice), and creation of a new CAN on the same procedure. Now, the software prefills all information regarding the result on the first two lots suggesting that whatever the reason for the new CAN, information on lots 1 and 2 should be included. It is most easy for the buyer to correct small errors regarding the award on lot 1 or add info in lot 3 award and harder to remove information an lots 1 and 2 to just publish information on lot 3. In effect, buyers tend to send cumulative notices (repeating already published information on lots awarded early in the process), having results on all lots in the temporally last CAN of a procedure.

**Comment by JachymHercher** [comment]
@tinne very interesting. In https://github.com/eForms/eForms/issues/270#issuecomment-474030101, we are not specific on whether, if you give a code of "The winner was announced in a previous notice.", the new CAN should be cumulative or not. I assumed that not, but I guess you would prefer the cumulation? In fact, both options could hypothetically be allowed, but maybe allowing only one would cause less confusion.

**Comment by tinne** [comment]
Mostly I would prefer clear rules. Especially what do you expect to happen when you need to publish a correction on the award of lot 1 and a non-award on lot 3 - does this result in a correction and a new CAN, and can they be submitted simultaneously? The main benefit of the cumulative publication might be that for each instance of time you publish the whole known information _true_ on that moment in time, and no partial truths.

**Comment by JachymHercher** [comment]
We would expect to have a correction and a new CAN. These would be two notices. However, this is the case regardless of whether the CANs are cumulative or not - corrections must be made with corrections; information on the result of the procedure with a CAN. 

Concerning truth at the moment in time, this would again be the case regardless of whether information is cumulated or not. The main difference that cumulation requires certain effort on the side of the IT implementers, while non-cumulation on the side of the users.

**Comment by tinne** [comment]
In this case it should me made clear that a change of policy is being made as currently only small changes to CANs can be published via F14.

One could also say that a CAN is final to a set of lots (in the sense of everything announced later must be a correction). Then any non-change successor would have to be based on the set of non-final lots or any subset. Does such a rule make sense?

**Comment by JachymHercher** [comment]
Just to make sure we understand each other correctly, which change of policy do you mean? Above, I just meant to say that if you correct a notice, you should use the correction notice. (We're setting aside the legal question of when should notices be changed and when, instead, a procedure should be relaunched.)

Here is the way we propose it works. Does this correspond to what you were saying?
1. Every CAN must give a BT-142 per each lot that existed in the CN. 

    Let's assume that a CAN was published and for one BT-13713 (Result Lot Identifier), BT-142 (Awarded) was equal to "The winner is announced in this notice." In that case: 

1. any future change to this lot must be done via a corrigenda. 
2. any future CAN for the same procedure must include this lot with BT-142 equal to "The winner was announced in a previous notice." (As discussed above, we could also consider requiring that the notice must also include all the same data linked to this lot.)
3. any future CAN for the same procedure may include new information for any other lots (i.e. for lots which have never had a value of "The winner is announced in this notice.")

**Comment by tinne** [comment]
Sounds consistent, and the proceeding of 3 (parens) should better be abandoned for the new The winner was announced in a previous notice" code.

Should there also be a "The non-award was announced in a previous notice" for any lot that had  announced "No winner was chosen and the competition is closed" in a previous notice?

**Comment by JachymHercher** [comment]
Good point about "non-award in previous notice". It raises the point of _why_ to explicitly declare that something was done in a previous notice. We see two reasons:
1) If CANs are not cumulative, to understand why there is no data even though a winner was announced.
2) To make it easier to identify when the result were announced for the first time (e.g. to check that legal obligations on transparency were respected). 

These two use cases are not too strong (esp. if cumulative CANs, at sender side or publisher side, are used). Perhaps it would be better to only have the following codes:
- The winner was chosen. 
- The winner was not yet chosen, but the competition is still ongoing.
- No winner was chosen and the competition is closed.
