### ISSUE TITLE
BT-712 (Review Requests); Business Group; Relevance outside award decisions

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#271]
BT-712 (Review Requests) ("Number of tenderers that requested the buyer to review the award decision.") is currently specific to the review of positive award decisions.

However, reviews can be requested and complaints can be made in other scenarios outside positive award decisions. For example, complaints can lead to no award being made – in which case there would be no BG-320 (Winning Tender) on which to record the number of complaints.

If the intention is to collect statistics on all review requests/complaint submissions, then this BT might be more appropriate under BG-710 (Additional Information).

**Comment by UlrikaSjoholm** [comment]
I agree; are applications concerning other decisions than the award decision meant to be excluded (for instance a selection decision in a multiple stage procedure)? There could be different interpretations of what kind of information that is requested in this field. We also question the choice of the term tenderer, as excluding other economic operators, and that the tenderer requests the buyer to review the award decision. Are applications for review made to a court or another external body meant to be excluded?

**Comment by JachymHercher** [comment]
Good points. We will change the description to “Number of economic operators that requested the buyer to review any of its decisions (e.g. the technical specifications, award decision).” and move the BT to BG-710 (Additional Information). 

This will also allow simplifying BR-233 and BR-22, because BG-320 will no longer have to be included even if no Winning Tender was present. 

@UlrikaSjoholm Concerning the reviews, yes, the scope is intended to cover only review requests to the buyer (i.e. those described in Art. 1(5) of 89/665/EEC), not courts and other review bodies. The reason is that the data on courts and review bodies should be collected and published by them, there is no reason to duplicate it in eForms. (Please note the Commission is supporting such schemes, e.g. via funding through the Connecting Europe Facility program and promotion within the Commission's review body framework.)

**Comment by JachymHercher** [comment]
In light of comments posted at https://ec.europa.eu/info/law/better-regulation/initiatives/ares-2019-797630_en, which requested further clarification on this BT, we suggest to include the legal references in the definition.

> Number of economic operators that requested the buyer to review any of its decisions (e.g. the technical specifications, award decision)_, as set out in Art. 1(5) of Directive 89/665/EEC and Directive 92/13/EEC._
