### ISSUE TITLE
BG-77 (Modification) and BG-09 (Change); M/CM/O columns

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#272]
The columns for M/CM/O are blank for the BTs under BG-77 and BG-09. Shouldn't these be provided?

**Comment by JachymHercher** [comment]
For BG-77, we have made them M. 

For BG-09, this is described Table 1 of the Annex of the Implementing Regulation, which says that when using the Change standard form, the notice shall contain the fields listed in "any other standard form and the Notice and Change sections from Table 2". There is no M/CM/O for BG-09, because there is no column for the Change form.
