### ISSUE TITLE
BT-1501 (Modification Previous Contract Identifier); N/A; Reference to other BGs

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#275]
BT-1501 (Modification Previous Contract Identifier) is used to refer to a BT-150 (Contract Identifier), which is part of a BG that also has BT-3202 (Contract Winning Tender Identifier).

BT-720 (Winning Tender Value) is in BG-320 (Winning Tender), not BG-310 (Contract), so if a notice announces a modification of the value of the contract, I assume that a data user would have to follow the references from modification to contract to winning tender, to be able to lookup the original value.

This seems okay. However, I am not sure if any other BGs are relevant to modification notices but are not able to be directly or indirectly referenced from BG-77 (Modification).

**Comment by JachymHercher** [comment]
There is indeed a problem. In particular, BT-1501 refers to BT-150 (which identifies BG-310), but BG-310 can refer to _multiple_ BG-320s. Consequently, if there was a change, for example, in two BT-720s and a user wanted to submit different reasons for modifying each, he would not be able to do so. 

As a solution, we suggest renaming BT-1501 to "Modification Previous ~Contract~Identifier" and updating the description to: 

> Identifier of one or more ~lots~_sections_ within the changed notice. The information in the change cancellation section refers to this ~lot~_section_ or these ~lots~_sections_.

In the technical specification, this will then need to be specified into all the types of identifiers needed to uniquely identify any piece of data in a notice (@yvesjo).

**Comment by jpmckinney** [comment]
Does BT-1501 need to refer to anything besides the Winning Tender and Contract? "Modification" has a fairly narrow scope in the legislation (unlike "Change").

**Comment by JachymHercher** [comment]
Yes, it could be broader - essentially anything in Annex V Part G of Directive 2014/24/EU (The modification can mean that the CPV changes, the place of performance could change, the duration could change, the procurement could become green/social/innovative...) 

You are right that what can change should be carefully controlled. If the BTs application to the modification notice are listed in the spreadsheet, as suggested in https://github.com/eForms/eForms/issues/306#issuecomment-473923149, then this would be clear explicitly, otherwise it would require business rules.

**Comment by JachymHercher** [comment]
For clarity and consistency reasons, we suggest renaming BT-1501 to "Modification Previous _Notice Section_ Identifier".
