### ISSUE TITLE
BT-754 (Accessibility); ANY; Merging BT-754 with BT-06

### ISSUE THREAD

**Issue by UlrikaSjoholm** [eForms/eForms#277]
To rationalize the number of fields, we suggest that BT-754 is included in the codelist for BT-06.

**Comment by JachymHercher** [comment]
We agree that the fields are thematically linked (even more so with field BT-775, see https://github.com/eForms/eForms/issues/259#issuecomment-481315769). 

However, the problem is that the codes of BT-754 has a different level of "generality". That is the values below are at a different level than, for example, "Fulfilment of social objectives" used in BT-06 as well as "Accessibility for all", proposed in the new BT-775. 

- Accessibility criteria for   persons with disabilities are included
- Accessibility criteria for persons with disabilities are not   included because the procurement is not intended for use by natural persons
- Accessibility criteria for persons with disabilities are not   included with the following justification
