### ISSUE TITLE
BT-147 (Received Tenders EU), BT-723 (Received Tenders Non-EU); Name; EEA instead of EU

### ISSUE THREAD

**Issue by UlrikaSjoholm** [eForms/eForms#282]
There is a discrepancy between the Field name (EU) and the description (EEA). According to our understanding it should be EEA in the Field name as well.

**Comment by tinne** [comment]
Same with “Received Tenders Non EU” resp. the code list resulting from #227.

**Comment by JachymHercher** [comment]
There is indeed a slight discrepancy between the name and the description, but it was intentional. While the description is correct (i.e. the field is about the EEA), we thought the "EU" acronym would be more useful as a name, because "EEA" is not a widely known acronym and thus would be understood only by very few people/implementers. In other words, it is slightly incorrect, but perhaps more helpful. We would be glad for your views.

**Comment by jpmckinney** [comment]
Are the semantics EEA or European Single Market (which would add Switzerland)?

**Comment by jpmckinney** [comment]
The standard forms have "Number of tenders received from tenderers from other EU Member States", so I definitely read "EU" here as "European Union", not "Europe", "EEA" or "European Single Market". We should use the appropriate term, to avoid confusion.

**Comment by tinne** [comment]
When "only" code list names, a longer version could be preferable. Also, if talking of states instead of territory, please take case of Suriname, Jersey, etc.

**Comment by JachymHercher** [comment]
@jpmckinney EEA. This line was drawn because the procurement directives formally are a "text with EEA relevance". 

Given https://github.com/eForms/eForms/issues/227, this question is a bit moot. For the relevant codelist (not the label) to be eventually prepared by OP, let's keep in mind that it should refer to what is in the description (which is no surprise for @muricna).
