### ISSUE TITLE
BT-745 (Submission Nonelectronic Description); Level; Need for additional information

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#285]
In ePO it was discussed that for non-electronic-submissions it would be convenient to have a structured "ContactPoint" making possible to specify to whom the tender should be addressed (e.g. department, role, etc.), where (e.g. physical location, like a postal address), and other communication means (e.g. telephone, fax, etc.), thus facilitating the economic operator the submission of its tenders.

BTW, In OCDS they also have a Contact JSON structure for these purposes, as in UBL, ePO, other.

We understand the free broad "Description" text as the one eForms has now (BT-745) may contain all those details. But then what is the value of eForms if you cannot map these data towards syntaxes like the ones mentioned above?

KR

**Comment by jpmckinney** [comment]
The present standard forms have "Tenders or requests to participate must be submitted … to the following address:", whose value is a structure with address, contact details, etc. similar to BG-703 (Organisation).

The new eForms could consider adding a BT to BG-102 (Submission Terms) to identify the BG-703 (Organisation) to which to submit non-electronically for the particular lot(s).

**Comment by tinne** [comment]
This is indeed what the additional roles in #85 are about (roles 1 and 2 in https://github.com/eForms/eForms/issues/85#issuecomment-427319710).

Deriving from national below-threshold notices, I added to my request two further roles relating to BT-615 / BT-520 / BT-13 and BG-310, respectively.

**Comment by jpmckinney** [comment]
@tinne If different lots have different submission addresses/organizations, I'm not sure that BT-08 (Organisation role) would be sufficient. I think it'd be necessary for BG-102 (Submission Terms) to identify which organization receives submissions for which lots, like in my above comment.

**Comment by tinne** [comment]
jpmckinney  Thanks for intervening, my cross reference was more on the necessary than on the sufficient side.

Of course, if explicit BTs were to mention the submission/offer addressees, the Organisation Role of the target organisations could be more general.

**Comment by paulakeen** [comment]
This is how we have it in ePO:

![image](https://user-images.githubusercontent.com/16134316/54374208-f151bc00-467e-11e9-843e-68454ef3219b.png)

**Comment by JachymHercher** [comment]
Indeed, https://github.com/eForms/eForms/issues/285#issuecomment-472442950 sounds like a good approach. We already take the same approach for "Procurement service provider that serves as a contact point", which is pointed to from BT-520 (Additional Information Reference) (see https://github.com/eForms/eForms/issues/125#issuecomment-424040269) and is similar to BT-713 (Contract Buyer Identifier).  

The question remains whether, with references, we would even need values in BT-08 (Organisation Role) - or even BT-08 at all. Currently, everything in the BT-08 codelist could in some hypothetical way be different per lot/contract* (except "Procurement service provider (TED eSender)" which means that roles can implicitly be derived from the references. 

The main reason for having BT-08 was simplifying the re-use of data, because it would be easier to find organisations with particular roles if these are explicitly declared (that's also the approach in the OCDS). 

At the end of the day, I see three options:  
1. BT-08 is removed, there are only BTs with references. No duplicated information, but less understandable.
2. BT-08 & BTs with references to BT-8. In this scenario, BT-08 exists only to simplify re-use (and does not need to go to the detail discussed in #85). More understandable, but duplicated information. 
3. In BG-703 (Organisation), BT-08 is accompanied with a lot identifier and a contract identifier (the type of identifier depends on the role). More understandable, no duplicated information. Under this scenario, we need BT-08 to go to the detail of #85. 

I find 3. as the best approach. Very grateful for comments. 

_______

&ast; We assumed that review/remedy bodies are always the same for the whole procedure. These were the only cases where a value in BT-08 was never referred to. However, this is wrong. In fact, if we imagine a procedure where each lot covers a different country (or even just a region in a country where regional courts are responsible for procurement remedies), then even the review/remedy body can be different per lot. To be solved depending on the approach taken above.

**Comment by tinne** [comment]
Scenario 3 sounds great. Would need winning tender and contract references as well though.

**Comment by jpmckinney** [comment]
In scenario 3, would the BTs that point to an organization be removed?

A common use case is: I'm an economic operator. I'm interested in Lot 1. I want to know where to submit my tender for Lot 1. I also need to know the other submission terms.

If there's a pointer to the organization to which I need to submit my tender in the submission terms, then my job is easy.

If, instead, I need to iterate through all the organizations, and all their roles, to find out which one has the right role for Lot 1 – my job is harder.

So, I'm in favor of preserving the BTs that point to the organization.

**Comment by JachymHercher** [comment]
@jpmckinney Isn't your comment influenced too heavily by thinking about what will be the display on the website? The data structure can of course influence the way the developers think and, as far as it doesn't raise other issues, it may make sense to have data stored similarly as to how it is displayed. However, in this case, isn't there a higher benefit from not having duplicated data and reducing the number of BTs / links?

**Comment by jpmckinney** [comment]
My earlier comment refers to how data is used; not how data is displayed. At the display level, you can overcome any difficulties in how the data is organized, by re-organizing it visually.

OCDS has both a field on the organization for its roles, and references to organizations from other parts of the schema. This is partly because some roles have no corresponding references and can therefore only be expressed in a field on the organization. It's also to preserve backwards compatibility with version 1.0, in which organization data was repeated instead of referenced.

Returning to the three options:

(1) Option 3 seems to make less sense semantically. If I'm looking at data about a winning tender, a common use case is to know the supplier. It therefore makes sense for the tender to point to the supplier. It seems unusual to have to pull up a separate segment of the data file and filter through multiple lists to find matching identifiers. Same with my earlier example about submission terms.

In short, it makes more sense semantically for various objects (tenders, submission terms, etc.) to point to the organization, rather than for the organization to point to various objects.

(2) The reverse relationship (organizations points to others) makes some use cases easier (e.g. how many lots did a given supplier win), but after thinking through the various use cases and their relative importance and frequency, I think the reverse relationship is a worse approach.

In other words, if I compare the increase in usability from having BT-08 to the decrease in usability from removing the references, then the loss is greater than the gain, and therefore I favor retaining the references.

(3) If we're agreed on the conclusion to (2), then the only argument in favor of BT-08 is a reduction in duplication. But, if the references are indeed more useful like in (2), then we can simply go with option 1, and remove BT-08.

Alternately, if we think BT-08 is useful enough to preserve, then TED can simply calculate it based on the references, i.e. it doesn't have to be a business term that eSenders use.

**Comment by JachymHercher** [comment]
Thank you for the analysis. The main reason for having references seem to be that references are semantically in the "right" place, i.e. directly next to related BTs. (For example, reference to where to submit tenders is in the Submission Terms; reference to the tenderer in the Winning Tender, etc.)

The reasons against references, given above, was that they:
- Make the data less concise (each type of reference requires its own BT, as compared to "only" having a lot identifier, winning tender identifier and a contract identifier in BG-703 Buyer). 
- Either imply duplication (scenario 2) or not using BT-08 (scenario 1). We like BT-08, because we consider it user friendly. (Ex-post addition of BT-08 is possible, but also not always ideal, as eForms are used also at national level without TED.) 

I would like to propose a new reason in favor of putting identifiers in BT-08 instead of references. After some reflection, I think it is actually a very intuitive and usual place to put it - because that's where we put the identifiers in case of all other BGs. 

Above, we mentioned the use case "looking at data about a winning tender, want to know the supplier". Similar use cases could be "looking at data about a winning tender, want to know what is being bought" / "...want to know which technique was used" / "... want to know more about XYZ". In all cases except the first one, the user needs to look for the relevant BG in the data and the corresponding lot identifier. Isn't it simplest to answer also the first use case in an as similar way as possible, i.e. look for the relevant BG in the data and the corresponding lot identifier, _then filter by role_? There is indeed one step extra, but isn't that still more intuitive then having a whole new reference mechanism? 

(BTW 1: Referring from BG to BG, or referring from BG to some central concepts, in this case lot (contract, winning tender) could be seen as two general approaches. For example, winning tender could have a direct references to a particular instance of purpose, technique, etc. Consistently using just one of these general approaches may be more intuitive.)

(BTW 2: The semantic problem of organisations could be seen as inherent to the BG itself, because it's the only BG which is not based on some kind of a procurement function, but rather on the type of information collected - information about organisations of any types. This seems to be a conscious trade-off between semantics and a simpler data structure, avoiding duplication, etc.)

**Comment by jpmckinney** [comment]
Let's do an accounting comparing options 1 and 3:

In one scenario, there is a codelist with some number of codes and a BT (BT-08), whose values are BGs with three BTs each (role, lot identifier, contract identifier). In another scenario, there are some number of referential BTs whose values are organization identifiers; right now, there's BT-1701 (Winner Organisation Identifier), BT-713 (Contract Buyer Identifier) and BT-520 (Additional Information Identifier), and this issue considers adding another BT to identify the organization to which to submit non-electronically for particular lots. Other referential BTs *might* be added, but in this issue, it's 4 referencial BTs, compared to 1 BT + 1 BG + 3 BTs + at least 1 code for each referential BT from the other scenario.

So, the schema/model appears to be both more concise (fewer BTs, BGs, codelists) and less complex (less hierarchy, no codelist) using organization references.

As for the data, it is more concise in option 3. Whenever I publish an organization reference, I assign a value to a BT (two units of information). Whenever I publish a role, I add a BG, assign a code to the role BT, and assign a value to another BT (lot identifier or contract identifier) (three units). This is true regardless of how many organization references are added in the future.

So, the first point doesn't seem to hold.

----

Regarding the second point, both approaches improve user-friendliness. Eliminating either approach to avoid duplication will reduce user-friendliness. So, I don't see this, on its own, as a reason to favor either approach.

In my earlier comment, I considered which of the two contributed more to user-friendliness. I gave some sample questions that users would want to answer, and showed that they are easier to answer using organization references. I can give many more.

----

In terms of intuitiveness, let's take an example: A user wants to know information about a winning tender, including its value, CPV, and suppliers.

1. They find the relevant BG-320 (Winning Tender) within the data.
1. They see BT-720 (Winning Tender Value) in the BG and record its value.
1. They see no BT for CPV in the BG, but they do see BT-13714 (Winning Lot Identifier). They refer to the schema, and see how to make the direct link to the relevant BG-02 (Purpose).
1. They see no BT for supplier in the BG, but they do see BT-1701 (Winner Organisation Identifier). They don't need to refer to the schema as the BT clearly indicates that it directly refers to the winner organizations, so they simply make the direct link.

Alternately:

* They see no BT for supplier in the BG. The only other reference is BT-13714 (Winning Lot Identifier), which they assume they must use. They know they are looking for an organization, so they look at the schema for BG-703 (Organisation) for clues. They find a lot identifier **under** a BG **under** BT-08 (Organisation Role). They realize they can make a link to an organization, but don't yet know which role is relevant. They look at the codelist and find the **two** roles to check for. They now know that they must iterate over each BG under each BT-08 to find the suppliers.

In the second scenario, there are many more steps, and thus many more opportunities to go wrong. How long before they find the lot identifier deep within BG-703 (Organisation)? Will they fail to notice that there are two roles that indicate a winner?

This exploration of a practical example demonstrates that, if option 3 is taken, then the approach for looking up the CPV will be very different from looking up the suppliers. In other words, with respect to the two BTW, there will not be a uniform approach – and so those are not arguments in favor of option 3. There will be two approaches, and the approach for looking up organizations is far simpler with option 1.

----

I hope the above makes it clear that relying solely on BT-08 is a worse choice in terms of simplicity, conciseness and user-friendliness.

**Comment by JachymHercher** [comment]
Thank you for the impressive and rigorous accounting, @jpmckinney. 

My comments:
1. The number of codes/references is higher than you considered. Besides the 8 mentioned in your comment, a subcontractor, a mediation organisation, a review organisation as well as the "organisation providing more information on the time limits for review procedures" could, in principle, be different per lot. In cases of joint procurement of CPBs, we might need even the CPBs per lot. This gets us to 14+. 
2. As you say, "the two options trade BTs for codes". As far as I've understood, codes are preferable to BTs, because they are more flexible. For example, they allow new additions without changes to the schema - which is useful, given the "ever growing" use cases mentioned in the previous point. (This flexibility can make an even bigger different if EU countries decide not to include the codes in the Implementing Regulation.)
3. In my opinion, BT-08 is user-friendly. For example, because it allows understanding roles only on the basis of the information in BG-703 (Organisation), without needing to go through the whole notice to see what reference points where. This makes scenario 2 better than scenario 1, but the accounting for scenario 2 above, is (somewhat) different than the one for scenario 1. 
4. When talking about conciseness, rather than the "number of BGs/BTs/values", I was thinking of number of additional BTs that will need to exist in the standard (i.e. 3 vs. 14+) (my use of "conciseness" might have been wrong, sorry). 
5. I would defend the option of allowing - in what I would consider rather atypical corner cases - multiple BG-703 per single organisation. This avoids the added BG (and thus avoids the complexity you mention above), slightly changes the accounting, and also has implications for user-friendliness (because the lot identifier is in the same place in every BG in the notice). The inelegant multiple 703 per single organisation would be used when the same organisation has a different role in different lots (which may happen e.g. in some types of joint procurement, depending on how responsibilities are split) or to model different addresses of an organisation per different lot (which we don't consider a high priority, as discussed in #61). 

Given the above, I'm still in favor of 3, rather than 1 or 2. I agree both approaches are workable though. 

(It would be great to also have some more views on this - for example @paulakeen, @tinne.)

**Comment by jpmckinney** [comment]
I'm tending toward option 3 if we avoid the new BG as in your latest point 5, though I think there will still need to be some guidance to users, as it is not obvious how to determine the winner of a lot without some effort (even without the new BG).

**Comment by tinne** [comment]
Regarding user-friendlyness and evaluability, I would like to ask whether your conceptual models are that way that both views can be derived from each other - given the points of 1, can you give all the id BTs in 3, and vice versa? In this case a “data duplication” scenario like 2 would be bad as the model is not minimal and inconsistent instances can exist (an organisation can accidentally been included with the role winner but to winning tender pointing to it as something had been redecided in the last minute). This is clearly undesirable. It could, however, lead to an evaluation variant of a minimal eForms “storage” representation which can be computed by everyone doing that kind of intelligence reports on this data.

Classic entity-relationship modelling has pointers on the many side of a 1:n relationship and link tables (special in-betweens telling which entity belongs to each other) in case of n:m relationships. I would strongly recommend to stick to this principle with eForms data as well.

Take the following variant of 3, which accounts for item 5 in https://github.com/eForms/eForms/issues/285#issuecomment-474505141: Add a BG Organisation Roles to BG-703 (Repeatable), move BT-08 there and add the identifier links for (one or many) lots, a contract, etc. Does this solve the issue?

**Comment by jpmckinney** [comment]
Yes, options 1 and 3 can be derived from the other.

Regarding the relations, it's important to point out that, in both options, a single real-world organization might have multiple BG-703 (Organisation) if the organization's details depend on its role (e.g. a different address for receiving enquiries than for receiving tenders). In the case of option 3, there might be multiple BG-704 for the same organization, if it has different roles for different lots/contracts (e.g. in some types of joint procurement).

So, the relation between lots/contracts and *real-world* organizations is n:m (many-to-many), but in both options 1 and 3, the relation in 1:n.

The variant of 3 you suggest was already considered in my comments, and created more issues than it solved.

**Comment by paulakeen** [comment]
Indeed this discussion has become very extensive and complicated. But I think that a nice summary is what @jpmckinney says in the last (previous to this) comment which is:

"Organisations should be always unaware (agnostic) of how they're used" (this is my sincere opinion), this implies that:

1- BG-703 (Organisation) cannot add BTs that do not define the Organisation (like identifiers of Lots or Identifiers)
2- Organisations participate frequently in n-ary relationships. To reflect an n-ary relationship in the current eForms spread-sheet is possible, and it would be similar to what it is done in a UML or an E/R relationship: just add a class (a BG) that has links (in eForms Identifiers) to all the rest of BGs. For example, Submission Terms can be seen as a n-ary relationship class that links the terms to specific Lots to specific Organisations. This is what eForms does in other places, btw, and it creates n:m:z (n-ary relations). The problem is that the current eForms is very XML-oriented and this makes difficult to detect where this happens (unless you have a graphic representation of it, which can/should be done, by the way for the eForms);
3- Roles should always be implemented via a reference to an Organisation. The fact that the reference participates jointly with other references from on n-ary class is sufficient to infer the rest of information needed. 

(Beware that this last consideration is the result of an early "design" decision which consisted in reducing to the maximum the number of BGs).

**Comment by JachymHercher** [comment]
Thanks once more to everyone for the contributions (esp. @jpmckinney). As far as I've understood (https://github.com/eForms/eForms/issues/285#issuecomment-474511950, https://github.com/eForms/eForms/issues/285#issuecomment-473251061), option 3 seems to be acceptable, so we will suggest that. Concretely, this means:
- Adding BT-13720 "Organisation Notice Section Identifier" with a description of "An identifier of one or more sections within this notice. The information in the organisation section refers to this section or these sections." 

    Which identifiers can be given here can be specified at the technical stage later on, similarly to #275 and #276. We would expect "winning tender identifiers", "contract identifiers" and "lot identifiers".
- Removing BT-520 (Additional Information Identifier), BT-1701 (Winning Organisation Identifier), BT-713 (Contract Buyer Identifier). 

___

For information, this is how the Organisation Role (BT-08) and Organisation Subrole (BT-770) described in https://github.com/eForms/eForms/issues/85#issuecomment-475609662 would apply to different parts of the procedure/notice:

BT-08 (Organisation Role)
- Buyer (per lot and/or contract) 
- Procurement service provider (per lot and/or contract) 
- Central purchasing body acquiring supplies and/or services intended for other buyers (per lot and/or contract) 
- Central purchasing body awarding public contracts or concluding framework agreements for works supplies or services intended for other buyers (per lot and/or contract) 
- Winner (per winning tender)
- Subcontractor (per winning tender and, in case of consortia, per winner organisation identifier) 
- Mediation organization (per lot, very theoretically per contract)
- Review organization (per lot, very theoretically per contract)
- TED eSender (per notice) 
- Organisation providing information concerning the general  regulatory framework for taxes applicable in the place where the contract is to be performed.
- Organisation providing information concerning the general regulatory framework for environmental protection applicable in the place where the contract is to be performed.
- Organisation providing information concerning the general regulatory framework for employment protection and working conditions applicable in the place where the contract is to be performed.

BT-770 (Organisation sub-role) - new
1. Group leader (per winning tender for winners, per procedure others, perhaps very theoretically even per lot)
2. Organisation providing additional information about the procurement procedure ... 8. Organisation processing tender (per lot) 

    9, Organisation signing the contract (per contract)
    10. Organisation whose budget is used to pay for the contract (per lot and/or per contract) 
    11. Organisation executing the payment (per lot and/or per contract)

**Comment by JachymHercher** [comment]
@YvesJo observed that when multiple BG-703 are used in line with the corner-case described in point 5 of https://github.com/eForms/eForms/issues/285#issuecomment-474505141, the multiple instances of BG-703 need to be differentiated somehow, because they will have the same BT-501 (Organisation Identifier). 

How this is done probably doesn't need to be reflected in the eForms spreadsheet (e.g. there could be an additional instance of BT-501 which would differentiate the two; there can be some other identifiers of the BG instance).
