### ISSUE TITLE
BT-132 (Opening Date); Data type; poor datatype

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#286]
Shouldn't this be a DateTime? BTW, the current "Description" would also be wrong, as it reads only "time" not "date and time".

**Comment by JachymHercher** [comment]
In the Implementing Regulation, we do not distinguish Date and DateTime. (See also https://github.com/eForms/eForms/issues/250#issuecomment-469291918.) 

Indeed, the description would be better as "The _date and_ time for the opening of tenders.", e.g. because it's more consistent with other similar BTs ((BT-05 (Notice Dispatch Date) and BT-719 (Change Procurement Documents Date))).
