### ISSUE TITLE
BT-744 (Submission Electronic Signature); Any; Additional BTs needed

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#288]
Technical details/Requirements on the electronic signature may be needed. E.g. If it has to be qualified or not necessarily, enveloped/enveloping/dettached, only certain nodes but not all the notice, etc....

As this can become very complex an alternative could be to point at a publicly and freely available "policy" where all these details are stated.

**Comment by tinne** [comment]
My original proposal had a third option based on current German below-threshold notices, cf. https://github.com/eForms/eForms/issues/80#issuecomment-424782486.

**Comment by SellittoGiampaolo** [comment]
the proposed alternative to point at a publicly and freely available "policy" where all the details are stated seems an interesting one

**Comment by JachymHercher** [comment]
We're wondering whether it is really necessary/useful to have such a link in the notice, as compared to just the procurement documents. The advantage of the indicator is that it can give statistical information and that it can be, in some cases, used to search for notices (e.g. by a company that does not have and does not want an electronic signature). Would it really be that beneficial to include the link to the "very complex" policy already in the notice? 

(When considering this, we might want to keep in mind in line Art. 22(6c) of Directive 2014/24/EU, contracting authorities are obliged to accept electronic signature and that the eIDAS regulation sets (since September 2018) that public bodies must accept all electronic signatures coming from [EU Trusted Lists](https://ec.europa.eu/digital-single-market/en/eu-trusted-lists-trust-service-providers). This might mean that things will get a bit clearer in the future; or that perhaps there is some structured data to refer to.)
