### ISSUE TITLE
BT-732 (Security clearance); Any; Separation of the types of clearance and addresses

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#294]
In ePO we discussed about the eForms BT-732 Security clearance. After discussion it was decided that it was better to separate the difference types of clearance (clearance for documents and clearance for sites) as well as separating the different addressees of the security clearance (tenderer, contractor).

**Comment by SellittoGiampaolo** [comment]
The proposed solution makes sense, as the two different types of clearance impose different measures and certifications and involve different subjects.

**Comment by tinne** [comment]
A third relevant dimension (only partially discussed in #116) is on time: clearance for participation and bid or clearance which fulfilling the contract.

**Comment by JachymHercher** [comment]
The requirements about clearance stem from Art. 42(j), third subparagraph, of Directive 2009/81/EC, on the basis of which we have BT-78 (Security Clearance Deadline). This fields exist in the current forms and has been used ~500 times. 

BT-732 (Security Clearance Description) has been added based on the discussion in #116. 

We are not quite sure on the benefits of splitting a text field into further smaller text field on "what", "who", "level", "when", etc. (splitting into structured data seems currently impossible). All the BTs would be about clearance and would very likely be inter-related (e.g. you would like to structure the text as "Person A must have clearance X; Person B must have clearance Y"). In this situation, having separate field for Person and Clearance Type could bring more administrative burden and problems than benefits.

(It is also a point that could be made essentially about any text - you can always split it into thematic chapters and sections. However, same as above, enforcing people to use a predefined structure for free-text may frustrate them rather than help them.)

Consequently, keeping the above in mind, we're not really sure about the benefits this will bring. We would suggest to leave things the way they are, unless requested otherwise by EU countries.
