### ISSUE TITLE
BT-136 (Direct Award Justification Code); DataType; Proposal of codelist "direct-award-justification"

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#295]
We propose that eForms uses the code list, prepared by OP, "Notice-corrigendum-justification", which values are the ones contained in this spread-sheet:

[direct-award-justification.xlsx](https://github.com/eForms/eForms/files/2962352/direct-award-justification.xlsx)

**Comment by JachymHercher** [comment]
We agree with the content of the codelist, this is already the case.

(We assume the codelist is called "direct-award-justification", as given in the spreadsheet and the title of this issue, not "notice-corrigendum-justification" as in the description.) 

(The first column of the spreadsheet is called "authority-code" - is that correct?)

Concerning the actual codes (e.g. "no-suit-resp"), this is a technical matter which we would suggest to discuss later. However, just off the bat, couldn't it be made more human-readable? This simplify understanding the data for implementers and re-users. 

For example:
- "no-tenders" instead of "no-suit-resp"
- "no-tenders-previously" instead of "no-reg-resp" 
(please note that the key difference between this code and the previous code is not "suitable" and "regular", but that this code is about not having received any tenders in the previous procedure)
- "research" instead of "res-exp-stu-dev"
- "no-competition-technical" instead of "abs-comp"
- "urgency" instead of "inc-urg-res" 
- etc.

**Comment by paulakeen** [comment]
Two more comments, please:

1. The labels are very long, they are like definitions, they should be shortended
2. The term "no regular tenders" is not undersood.

**Comment by JachymHercher** [comment]
1. We agree these are not super user friendly, but they are politically and legally sensitive (using a direct award is always very tricky), so we would rather not change them. This wording comes from the previous forms and follows very closely the wording of the Directives. 
2. "Irregular tenders" are defined in Art. 35(5) of Directive 2014/24/EU. 

> In particular, tenders which do not comply with the procurement documents, which were received late, where there is evidence of collusion or corruption, or which have been found by the contracting authority to be abnormally low, shall be considered as being irregular.

**Comment by paulakeen** [comment]
2. In that case, why not calling them "irregular-tenders", as stated in the Directive?

**Comment by JachymHercher** [comment]
The directives mention "no suitable tenders", but only "irregular tenders" tenders. Irregular was switched to "no regular" to allow the same phrasing of the first and second code in the list.
