### ISSUE TITLE
BT-71 (Reserved Procurement); Any; Proposal of the codelist "participation criteria"

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#296]
Following discussions in ePO the fact that certain procurement are reserved for sheltered workshops etc. requires that the procurement criterion take into consider these criterion that can not be considered as exclusion, selection or award criterion, hence the need for "participation criteria". Please consider these values for the code list in eForms:

1. The contract is reserved to sheltered workshops and economic operators aiming at the social and professional integration of disabled or disadvantaged persons.
2. The execution of the contract is restricted to the framework of sheltered employment programmes.
3. Participation in the procedure is reserved to organisations pursuing a public service mission and fulfilling other relevant conditions in the legislation.
4. The contract is not reserved
5. Not yet known

**Comment by JachymHercher** [comment]
We agree with the content of the codelist, this is already the case.

**Comment by SellittoGiampaolo** [comment]
The use of the term "participation criteria" could not be suited here, as Directive 24 in Article 58 states that "Contracting authorities may only impose criteria referred to in paragraphs 2, 3 and 4 on economic operators as requirements for participation." 
Lawyers and courts usually leverage this point to debate whether or not the call for tender respects the principia and if the tender is open for competition.

The criteria for participation and selection are only those explicitly listed in the directive and this fact has also an impact on the ESPD.

If we read with attention the articles regarding reserved contracts, it is the contract (at execution time) that is reserved - essentially, any restriction posed at execution time does not hamper competition at the time of tendering.
I'd call the codelist "Reserved Procurement" in order to avoid debates

**Comment by JachymHercher** [comment]
Taking in account the comment by @SellittoGiampaolo, the feedback at the procurement ontology meeting, and further reading of the directives, this codelist indeed needs changes. 

1. Currently, the codelist seems to be making a distinction between "reserving the contract", "restricting the execution of the contract" and "reserving the participation in the procedure". This is based on the current forms, which were based on the Annexes of the Directive (e.g. Annex V Part C Point 11 of Directive 2014/24/EU). 

    However, looking more closely at Art. 20 (Reserved Procurement) and Art. 77 (Reserved contracts for certain services), the difference between "reserving the contract" and "reserving the participation in the procedure" does not seem to exist. In particular, Art. 20 says that:

    > _Member States may reserve the right to participate in public procurement procedures to sheltered workshops and economic operators whose main aim is the social and professional integration of disabled or disadvantaged persons_ or may provide for such contracts to be performed in the context of sheltered employment programmes. 

    Consequently, values 1. and 3. of the codelist should be harmonized and simplified:

    >1  _Participation_  ~The contract~ is reserved to sheltered workshops and economic operators aiming at the social and professional integration of disabled or disadvantaged persons.
    >3 Participation ~in the procedure~ is reserved to organisations pursuing a public service mission and fulfilling other relevant conditions in the legislation.

2. On the other hand, "restricting the execution of the contract" is something else and as @SellittoGiampaolo correctly mentions, relates to a different moment of the procedure - participation vs. contract execution. 

    Consequently, this code should become a BT, which would go into BG-711 (Contract Terms). It should be data type code and have a codelist of "yes", "no", "not yet known". 

    (The disadvantage of this step is that a company now must look in two places to know, at the end of the day, whether it's worth applying for the procurement procedure. However, this split is more precise from the timing point of view.)

**Comment by JachymHercher** [comment]
Building on the above, we have: 
- Renamed BT-71 from "Reserved Procurement" to "Reserved Participation"
- Added BT-736 (Reserved Execution) to BG-711 (Contract Terms), with the definition of "Whether the execution of the contract must be performed in the framework of sheltered employment programmes." (The definition closely follows the wording of Art. 20 of Directive 2014/24/EU.)

**Comment by ColinMaudry** [comment]
When I read the article, I see two possibilities that are distinguished in the current forms (section III 1.5) but merged in a single boolean field in eForms (as described above).

Article 20 (again)

> Member States may reserve the right to participate in public procurement procedures to sheltered workshops and economic operators whose main aim is the social and professional integration of disabled or disadvantaged persons **_or_** may provide for such contracts to be performed in the context of sheltered employment programmes [...]

- **Case 1**: contract is reserved for sheltered workshops and economic operators whose main aim is the social and professional integration of disabled or disadvantaged persons
- **Case 2**: the contract is provided to be performed in the context of sheltered employment programmes

I'm not familiar with these programmes, workshops, etc. but I feel the two cases could be be split in codes instead of being merged as a boolean field. Or are they so close that can be melted in a single term?

**Comment by ColinMaudry** [comment]
Oh, reading again the comments above, I understand Case 1 is covered by BT-71 and Case 2 by BT-736. All good :)
