### ISSUE TITLE
BT-553 (Subcontracting Value), BT-555 (Subcontracting Percentage); Description; Why both; [RULE]

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#304]
Business rules BR-285 and BR-388 state that
> If Subcontracting Known (BT-730) value is equal to "Yes", then Subcontracting Value (BT-553) is mandatory.
> If Subcontracting Known (BT-730) value is equal to "Yes", then Subcontracting Proportion (BT-555) is mandatory.

This would mean that in CAN general and DAP both relative and absolute subcontracting amount values must be given, which might be seem as information duplication. Was the intention to make at least one of the two BTs mandatory?

This might be an example of an XOR rule discussed in #203,
> If Subcontracting Known (BT-730) value is equal to "Yes" and Subcontraction Proportion (BT-555) is not given, then Subcontracting Value (BT-553) is mandatory,

and, vice versa,
> If Subcontracting Proportion (BT-730) value is equal to "Yes" and Subcontraction Value (BT-553) is not given, then Subcontracting Proportion (BT-555) is mandatory,

**Comment by JachymHercher** [comment]
Yes, BT-553 and BT-555 are totally equivalent. I understand your approach, but it was decided to propose both, because that is the formulation in Directive 2014/24/EU Annex V Part D Point 14 - "Where appropriate, for each award, value **and** proportion of contract likely to be subcontracted to third parties."

On the user side, we assume that one field will be automatically prefilled on the basis of the other field.

**Comment by SellittoGiampaolo** [comment]
Subcontracting can be used to perform a (usually small) fraction of the main contract or to perform some very specific part of the contract that requires equipments or skills that the awarded OE does not have. 
Can this situation lead to a difference between the subcontracting rule and the subcontracting percentage, e.g. where the subcontracting percentage only refers to the main contract while the subcontracting value also includes those parts of the contract that must be subcontracted anyway since the main contractor does not have the skills or equipments to perform them or does not have the qualification to perform them?

**Comment by JachymHercher** [comment]
The subcontracting percentage and subcontracting value are estimated at the same time and refer to the same subcontracting, so we would think that they should be identical.

**Comment by JachymHercher** [comment]
(This discussion is linked to https://github.com/eForms/eForms/issues/305#issuecomment-474519459, paragraph two and below.)
