### ISSUE TITLE
BT-202 (Modification Description); Description; too much irrelevant information

### ISSUE THREAD

**Issue by Rakwaak-FilipSvoboda** [eForms/eForms#306]
Is it really necessary that a contract modification notice (CMN) "_must inform about the nature and extent of **all the changes - both the earlier small ones and the later larger one**_"?

In BT-202 (Modification Description) should be only a description of that particular modification which is the reason of a publication of the CMN. Why should it contain information about previous modifications including the "_small ones_", too?

Moreover, such an extended description is apparently not a mandatory information set out in Annex V part G of the Directive 2014/24/EU.

**Comment by JachymHercher** [comment]
The wording was based on point 4 of Annex V Part G of Directive 2014/24/EU ("Description of the procurement before and after the modification"), where "description before the modification" was understood as following any other, "smaller" modifications. ("Smaller" would be more precisely called "modifications not requiring a publication of a notice", i.e. those in line with Directive 2014/24/EU Art. 72(1a), Art. 71 (1d-1e), Art. 71(2)). 

It's worth noting that such "smaller" modifications may, in some cases, also be necessary to understand the main modification. For example, if a small modification adds a small tower on top of an originally planned building; but then the tower causes structural problems that require a major modification of the contract, the latter may be hard to understand without the former.

Still, looking again at Art. 72(1) and keeping in mind that Part G of Annex V explicitly refers only to Article 72(1) (i.e. Art. 72(2) is not included), we agree that from a legal point of view, your reading is probably better. 

Consequently, we should at least:
- Change the description of BT-202 to "Summary of the contract modification(s)."
- Change the description of BT-720 Winning Tender Value to "Value of the winning tender or another result _(e.g. in case case of a modification notice, the change in the value)_; including options and renewals.

However, this small change in data may actually reflect a major conceptual change. In particular, a modification notice could be seen as not really an "updated version of a contract award notice", but rather a self-standing document, because the value of a modification does not need to be equal to the difference in the value of the contract between the moments when the contract award notice is published the modification notice is published (because there might have been other, unpublished, modifications in the meantime as well). This also highlights some older anomalies with the re-publication approach for modifications, such as BT-145 (Contract Conclusion Date) not "replacing" the BT-145 of the previous notice, but rather being a new piece of information about a new document. 

If we take modification notice as a self-standing notice, then we need to add a column to the spreadsheet (and corresponding legal texts) to include the modification, add M/O, clarify the definition on descriptions and also add a reference to a previous notice. (Happy for your views: @yvesjo, @muricna, @jpmckinney, @tinne, @paulakeen.)

**Comment by tinne** [comment]
I am not sure I understand the need for a reference to a prior notice except for the (important) case of “migration”: publishing an eForms modification to an R2.0.8.S04+ / R2.0.9.S3+ notice.

> Change the description of BT-720 Winning Tender Value to "Value of the winning tender or another result _(e.g. in case case of a modification notice, the change in the value);_ including options and renewals.

Does this mean that in some case BT-720 does not refer to the new total but a delta between the old and new total?

By the way, the current form F20 always imply a *raise* in price, as section VII.2.3) named “Increase in price” is mandatory. Understanding that this is quite usual, could it not be that the price is lowered/unchanged by means of reducing scope?

**Comment by JachymHercher** [comment]
The reference to a previous notice is important for example in case of framework agreements, where a modification notice could modify one of several contract award notices within a procedure.

Yes, in case of modification notices, BT-720 would refer to to the delta. 

Yes, it could be. Consequently, we use "change" in the description.

**Comment by jpmckinney** [comment]
I don't think the semantics of BT-720 should change so substantially (absolute value versus delta/difference) depending on the type of notice. Those semantics are so different that a new BT would make more sense – assuming it is relevant to know the difference and not simply the absolute value.

**Comment by JachymHercher** [comment]
To clarify/correct https://github.com/eForms/eForms/issues/306#issuecomment-473985905: BT-720 for the modification _sometimes_ happens to be equal to the delta between the old contract value and the new contract value (in cases that there weren't any _unpublished_ modifications). 

I'd say that a more useful view is that BT-720 for the modification is simply the value of the modification. The "modification", as discussed in https://github.com/eForms/eForms/issues/306#issuecomment-473923149 and somewhat counterinutively to the name, is better seen as a self-standing document (/contract), rather than a change to a previous document. In that case, maybe we don't have the semantic problem mentioned by @jpmckinney?

**Comment by tinne** [comment]
Sorry, but I am totally with @jpmckinney in this case. As far as I understand, a change and a modification announce a new situation, and then explain why things have changed. In case there is a new contract, I would have expected BT-720 to declare the total of the replacement contract, which would be old plus delta. In case a second contract has been concluded, maybe there are even two BG-310 referring to the same (contract, buyer, winning tender) if it is in public interest to publish so. The old notice would not be unpublished, so people can always calculate the deltas themselves. I thought this was the whole point of abandoning the F14 difference calculation concept.

**Comment by JachymHercher** [comment]
@tinne I understand what you are saying, but regrettably that is not the way the obligations are written in the Directives. What you write works for corrigenda, but not for modifications. This is because all corrigenda must be published, but not all modifications.

For example, in reality, you can have the following sequence:

> contract, small modification, big mod., small mod.,

According to the Directives, the notices published will be the following:

>contract, big mod.,

Consequently, 
> old value of the contract + value of the big mod. &ne; new value of the contract.  

The value of the modification... is simply that, a value of the modification.

**Comment by tinne** [comment]
Given D24 App. V Part G, does not tell me no 4 to give the old and new total value “nature and **extend** of the works, nature and **quantity** of supplies, nature and **extend*** of service”? The no 5 data “increase in price” is special additional modification only information which could be a new BT in BG-77.

**Comment by JachymHercher** [comment]
Not really, it would have been mentioned explicitly. Also, note that it's "nature and _extent_", which is the same wording used in the descriptions of the all other forms. (I.e. it is not linked to "extending".)

It could be a new BT in BG-77, but since it is "value of X", I'm wondering whether it's not semantically close enough to BT-720. The description could be changed, for example, just like this:

> Value of the winning tender or another result _(for example, in case of modification notices, the value of the modification)_; including options and renewals.

**Comment by jpmckinney** [comment]
I'd rather have two BTs, because as far as I'm aware it's not possible to determine, by looking at the data of a modification notice, whether BT-720 is the delta or the absolute value. If the contract was originally for $1M and BT-720 is $1.5M on a modification notice, how do I know whether the new value is $1.5M or $2.5M?

**Comment by JachymHercher** [comment]
The question is not really whether it's $1.5M or $2.5M; but rather whether it's $2.5M or _anything less or anything more_. There could be non-published modifications, which can move the contract value in any direction. (The modification notice, however, should never have the total value of the contract.)

In other words, the only thing we know is that BT-720 in a modification is always the absolute value of the modification. (Sometimes it happens to also be the delta of a contract value, but from the data alone, you will _never_ know whether this is the case, so it's a bit of a moot point.)

**Comment by jpmckinney** [comment]
I see… I still think it'd be better to have a BT under BG-77 for the Modification Value, to avoid making BT-720 more complicated than necessary.

**Comment by JachymHercher** [comment]
From another perspective: The modification notice essentially has fields which could be called "change of place of performance", "change of duration", "change of the description/cpv" as well as "change of value" (in all cases "of the original contract"). We should be consistent, so we shouldn't have a new BT just for "change in value". On the other hand, from a standardisation point of view, would it really make sense to have a new BT for the majority of the data elements in a modification?

**Comment by jpmckinney** [comment]
None of the others are deltas: The new place of performance will, presumably, not be a delta (e.g. 1'5" North of original place). This is, I think, also why the original standard forms treated price differently than all other modifications, with "VII.2.3) Increase in price".

**Comment by JachymHercher** [comment]
Assuming that "delta" is just another word for "difference" (or a "difference that is only about more/less"), the fields mentioned previous _can_ (and often will) all be deltas. "The works cover one additional location"; "The service must be provided for an additional two years"; "The cars must have an extra antenna on top" are all "deltas", no? 

(In the modification notices for the examples given above, I would expect them to inform about the new location (not all contract locations); the duration of the modification (not the whole duration of the contract); the CPV of an antenna (not of a car). I think this is in line with the approach in the Annex, that listing elements that are about the _modification_, not the whole contract.)

**Comment by jpmckinney** [comment]
I see; I didn't know that was how F20 was used in practice. I do note that F20 has an entirely separate section VII for all such modifications (i.e. new fields for change in place of performance, CPV, etc.).

I think having that separate section makes sense; rather than changing the meaning of all relevant BTs to mean "real value OR delta from earlier value".

So, although it would increase the number of BTs, it seems appropriate to instead expand BG-77 with many more BTs.

**Comment by tinne** [comment]
>> By the way, the current form F20 always imply a raise in price, as section VII.2.3) named “Increase in price” is mandatory. Understanding that this is quite usual, could it not be that the price is lowered/unchanged by means of reducing scope?

> Yes, it could be. Consequently, we use "change" in the description.

Regarding this discussion [above,](https://github.com/eForms/eForms/issues/306#issuecomment-473985905) kindly note that this has effect on the data type Value, which in the current forms has a positive monetary and can now be signed (i.e., negative, zero or positive) for the first time.

**Comment by paulakeen** [comment]
Regarding the re-publication of modifications, my opinion is that every modification should be published every time, even if small. Rationale:

1. If one main objective of the eNotification is transparency, then the re-publication of the modifications is more than welcome from the transparency perspective.
2. As @JachymHercher explains in his comments, small modifications may lead to major modifications. If one needs to study the result of a big modification (that has been published) then one may need the complete history of modifications to understand it and act consequently (may be suing someone).
3. From the Re-using of the Public Information perspective, any data may be relevant. No one may know the value of the data if it is not available and reusers can play with them.

**Comment by paulakeen** [comment]
About the need for adding BTs to BG-77, I totally agree: What is the problem with having data in the forms? the more data the better. And these BTs would not add complexity at all, just exhaustivity.

**Comment by jpmckinney** [comment]
Given the several clarifications regarding the modification notice (which I'll abbreviate as MN below), I am coming around to @JachymHercher's proposal.

If I want to know the current value of a BT for a procedure, I would presently need to (1) collect the CANs and MNs for the procedure, (2) put them in chronological order, and (3) look up the values of the BT. This might look like:

* CAN: The works cover all fire stations in arrondissements 1-4 of Paris
* MN: The works additionally cover all fire stations in arrondissement 5-11 of Paris
* MN: The works additionally cover all fire stations in arrondissement 12-20 of Paris

If we add a BT for each BT that a MN can modify, then the first two steps are the same, and then (3) determine the corresponding BT in the MN, (4) look up the values of the BT in the CANs, and (5) look up the values of the corresponding BT in the MNs. So, it's at least an extra step.

Regarding changes to BT descriptions, the original proposal (copied below) introduced ambiguity as to how to interpret the value of the BT, which was one reason I disagreed with the proposal:

> Value of the winning tender or another result (e.g. in case case of a modification notice, the change in the value); including options and renewals.

The current description is "Value of the winning tender or another result; including options and renewals." I would propose, for each BT that can be included in an MN, that the description stay the same, except for a second clause added to the end. For example:

> Value of the winning tender or another result; including options and renewals. If this is a modification notice, this should instead be the change in the value.

As such, the interpretation remains the same in all notices, but it (may) change in the modification notice. (My understanding of the modification notice is that, according to legislation, it can either state the change or the new value, though the change is preferred.)

This seems to be a good balance between having a comprehensible schema (larger schema with repeated, similar concepts are generally harder to understand) and having context-independent semantics for all BTs.

As it is, the BTs are already context-dependent (depending on whether a lot is identified or not, on whether the notice is for a procurement or a concession, etc.) and this additional dependency of whether the notice is a modification notice or not doesn't seem like a dramatic difference.

**Comment by JachymHercher** [comment]
Based on the discussion above, we have proposed the modification notice in the following format: 
- As mandatory fields: BG-1 (Notice) and BG-703 (Organisation), as well as BT-24 (Description), BT-720 (Winning Tender Value), BT-145 (Contract Conclusion Date) and BG-77 (Modifications). 
- As optional field: any field which covers information which could (at least theoretically) be changed by contract modification. (We have also considered whether all of these fields should not be considered as conditionally mandatory, because typically at least one of them would always change. However, there could probably be a situation when, for example, only BT-720 would change and nothing else.) 

This is based on the following considerations: 
- Modification notice is treated as a self-standing document, not an updated version of a contract award notice. This is because, legally, not all modifications are published and so `old value of the contract + value of a published modificiation ≠ new value of the contract` . 
- Looking at the relevant Annex, most points refers only to the modification (e.g. CPV, date of decision). The only exception is point 4, "Description of the procurement before and after the modification". Because of this difference, BT-24 (Description) is a mandatory field. (If the Annexes ever get changed, we would probably suggest rephrasing this point to a simple "Description of the modification".) 
- To give some examples, a modification notice would inform about, for example, a new place of performance (not all places of performance); the duration of the modification (not the whole duration of the contract); the CPV of a new, for example, antenna (not of a whole car). 

In line with https://github.com/eForms/eForms/issues/306#issuecomment-475759602, modifications use the same fields as any other notice; but in the descriptions, modification-specific information has generally been put at the end. 

Compared to the current modification notice, the main changes are:
- Essentially classifying all information under "VII.2.1) Description of the modifications" 
- Minimizing "VII.1) Description of the procurement after the modifications", essentially to BT-24. 
- No longer asking about the value before and after, but only about the value of the modification.

**Comment by JachymHercher** [comment]
> All points except points 4, 5 and 6 can be read as being about either the contract or the modification; there is no indication one way or another what each is about.

We agree it's 100% clear. Our approach was that the default should be that if not specified otherwise, then the information should be about what is mentioned in the headline of the relevant Annex; which is "Information to be included in notices of modifications of a contract during its term", where the main point is the modification.  

The new modification form is definitely a major break from the approach taken in the F20. Please note that F20 can be taken as an "inspiration" for the eForms modification form, but is not in any way binding or a legal basis - it's simply a different interpretation of the Annex. We have informed Member States about this major change of approach and requested their special attention to the topic in the official advisory procedure. They have not suggested any changes to the proposal. 

We have analyzed existing modification notices, the data largely conforms to the descriptions of the fields (i.e. it repeats information published in previous notices). 

Interesting point about point 7, "Date of contract award decision". A literal reading, e.g. taking "contract" as not meaning a "modification" (which is the word used elsewhere in the Annex), would indeed mean that the date should be given about the contract. This would have two rather counter-intuitive implications: no information about when the modification was made would be given; _new_ information about the original contract would be shared, because the requirement in point 10 of Part D of the same Annex is about the "date of the conclusion" of the contract, which is something distinctly different than the "Decision date" (cf. BT-1451 and BT-145).
