### ISSUE TITLE
BT-13* / BT-55[67] (* Lot Identifier); Level; Override general with specific information

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#307]
There was some discussion on the semantics of lot (group) specific information with our requirements team today which I would like to share:

Given I have some Submission Terms (BG-102) valid for almost every lot, is it a valid way to communicate this by giving general information in a Submission Terms group without Submission Lot Identifier (not lot specific) and adding special information on some lots by one or the other Submission Terms group identifying those lots which have a different setup, e.g., a separate submission deadline?

Else (and semantically identical, but maybe not that concise) one could state the rule that there are many groups where lot identifier sets must not overlap. This way, the set of ”all the other“ lots would be given in the first Submission Terms group.

**Comment by jpmckinney** [comment]
Would the interpretation be that the specific lot 'inherits' submission terms from the general group, unless its specific group overrides those terms?

**Comment by tinne** [comment]
@jpmckinney My suggestion was <Info on whole procedure> is default for <Info for lot or lot group>. One might well add <Info on lot group> is default for <Info on lot subgroup or single lot>, but I am not sure whether this makes things easier. One might end up digging through whole lot set subset hierarchies.

**Comment by paulakeen** [comment]
@jpmckinney , @tinne could one Lot "inherit" characteristics from multiple "parent" groups? e.g. Award Criteria common to several Lots and Framework Maximum Value, other?

**Comment by paulakeen** [comment]
In fact, this issue is similar to a discussion we have had in ePO when mapping the ontology to the eForms...we tried to identified where "groups" of lots are mentioned in the eForms and discovered that it was difficult to identify them. This is because in eForms the "groups" of lots are really very business-particular-need related (e.g. common Award Criteria and for the calculation of values in framework agreements). But there are other situations where the concept of grouping lots based on other needs could be necessary (e.g. DPS categories?). 

So the conclusion in ePO-eForms mapping was that: Group of Lots should be "agnostic of how they are used", as we have in ePO (which would need a clear definition). Otherwise the concept "Group of Lots" is diluted into different many specific BTs that do not convey clearly the idea of what is a group of lots (e.g. Group Award, Framework Maximum Value).

**Comment by tinne** [comment]
Resembles me of the discussion in #138 whether there should be “named” lot groups (which I originally had interpreted the sense of BG-330 to be).

The suggested interpretation was, like, for every BG having but not giving a lot identifier, the information included is valid for every lot not mentioned by any other data set in the same BG, independently of other BGs that may or may not issue lot specific information.

Thus, one lot could only have its own or the general information set, and never more than two possible sources, for every bit of information.

**Comment by jpmckinney** [comment]
Regarding hierarchies of defaults:
* if a lot needs to "undo" a value for the procedure, is this possible for all relevant BTs?
* If a lot negates an indicator that was set for the procedure (e.g. changes BT-578 (Security Clearance) from "Yes" to "No"), does it also need to change the dependent BTs (e.g. BT-78 (Security Clearance Deadline) and BT-732 (Security Clearance Description)) to empty/null values?
* If the procedure sets a BT whose data type is Date, Number or Code, how would a lot set this to empty/null, e.g. if that BT has no value for that lot?
