### ISSUE TITLE
BT-709 (Framework Maximum Value); Description; Lot-related clarification needed

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#308]
Could the description of the BT make clear that this maximum value is of the Lot, not of the Framework Agreement? the current definition seems a copy-and-paste of other similar definitions in other BGs.

**Comment by SellittoGiampaolo** [comment]
Yes it is not clear whether the maximum value refers to just one lot (and this should be the case, since we are in the context of BG 137) or to the sum of the values spent, which represents the Maximum value which can be spent within the framework agreement over its whole duration, including options and renewals.
I think it is a mix of the two... we are considering a lot in the framework agreement and defining a maximum value that can be spent in the context of that lot - it is useful from the point of view of management, since once this value is reached, buyers can't use that FA anymore

**Comment by JachymHercher** [comment]
This is a question of the terminology and consistency in the description. The current wording ("The maximum value which can be spent within a framework agreement...") reflects two main points: 
- In eForms, as a "wording principle", we usually do not specify in BT descriptions whether something can be repeated per lot or not. (For example, BT-759 is defined as "Number of tenders or requests to participate received.", with the same ambiguity.) The reason is to avoid repeating the explanations of "If the procedure is split into lots then per lot, if it is not, then per procedure." as well as avoiding the ambiguity of whether a procedure "not split into lots" should be understood as a procedure with a single lot or multiple lots. Instead of explaining this in the BT descriptions, the relevant BG description (e.g. BG-137 Procedure Lot Result) has a general statement of "This information differs per lot." and is marked as repeatable. 
- If a procedure contains multiple lots with framework agreements, we believe that in some countries (or cases) this will be taken as multiple lots of a single framework agreement; while in others as multiple framework agreements (each within the same procedure; with a single lot). This also influences how the description can be phrased. 

Consequently, we would prefer to leave things the way they are. We agree it requires a bit of digging, but it seems as the best way of how we can balance different perspectives. In specific systems, this can be then explained to end-users more simply (and in line with how it is understood in national practice).
