### ISSUE TITLE
BG-100: Communication (and all below this heading): mandatory eSubmission 

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#31]
In CN exceeding EU thresholds eSubmission is mandatory By 18.10.2018. Why are these fields marked as CM for CN in the Excel?

**Comment by JachymHercher** [comment]
Just to be sure: this question is about BT-17 (Submission Nonelectronic), BT-18 (Submission URL), BT-19 (Submission Nonelectronic Justification) and BT-97 (Submission Language), correct?

BT-18 and BT-19 and marked as CM because even if eSubmission is mandatory, there can be (justified) exceptions form using it (for more information, please see 2014/24/EU Art 22(1) second subparagraph). Thus, BT-18 or BT-19 are mandatory conditionally on what is chosen in BT-17. 

However, you are right, there is a mistake there: BT-17 and BT-97 should be M, not CM. It always needs to be indicated whether an exception to electronic submission is used and in which languages the tender should be submitted (regardless of whether it is electronic or not). We will correct this.

**Comment by JachymHercher** [comment]
In fact, we seem to have made an error when generating the spreadsheet - in BG-100 (Communication), all "M" seem to have been changed to "CM". This is not correct. The following CMs should actually be Ms. We will change them back: 

- BT-724 (Access Tool)
- BT-708 (Documents Legal Languages)
- BT-14 (Documents Restricted)
- BT-520 (Additional Information Contact)
- BT-17 (Submission Nonelectronic)
- BT-97 (Submission Language)
- BT-127 (Future Notice)
- BT-630 (Deadline Receipt Expressions)
- BT-131 (Deadline Receipt Tenders)
- BT-99 (Review Deadline Description)

**Comment by tinne** [comment]
Regarding BT-13, this would contradict #124.

**Comment by JachymHercher** [comment]
The contradiction has hopefully been clarified in #124.
