### ISSUE TITLE
BT-27 (Estimated Value). Description. Optional field

### ISSUE THREAD

**Issue by jadelanava** [eForms/eForms#313]
Estimated value, as defined under Article 5.1 Directive 2014/24/UE, Article 16.1 Directive 25/2014/UE, Article 8.2 Directive 201/23/ is a data collected in the field, BT-27 (Estimated Value) , and, as indicated in the spreadsheet "4_eForms_ACPC_Annex_Table2_spreadsheet.xlsx", is an "O - Optional" field
Nowstanding the above, in order to comply with the information obligations of the triannual monitoring report of Article 83.3 of Directive 2014/24/EU, taking TED as the source of information,  it would be advisable that this field will be stated as "M - Mandatory" to determine, among other cases:
•	Number of contracts subject to harmonized regulation.
•	Information of the estimated value of public procurement.
•	Histogram about the values of the procedures.
•	Participation of SMEs in tenders above threshold.
•	Percentage of public procurement corresponding to procedures that include GPP criteria.
In many other Member States a subtantial part of publications in TED are refered  to contracts below EU thresholds.
Therefore, information in TED referes both to contracts above and below EU thresholds.Additionally contracting authorities often don´t include the estimated value of the contracts.
As a result data refering to above and below EU thresholds contracts cannot always be distinguised.
It can be concluded that estímated value should be a “M – Mandatory” field

**Comment by JachymHercher** [comment]
Concerning the role of estimated value for determining the legal basis, please note that in eForms this is not necessary. Instead of deriving it from the estimated value (which differs based on the Directive, the legal regimes, etc.) it is declared explicitly in BG-01 (Procedure Legal Basis) and BT-02 (Notice Type), from which it is clear whether the notice concerns, for example, social and other specific services. In case of below-threshold procurement, BT-01 (Procedure Legal Basis) would have the value "Other". 

Concerning the monitoring report template, the values requested there are generally sums of the award values rather than the estimated values. 

Given the above, the very different approach in EU countries to using or not using estimated value, the negotiations of the Directives where estimated value was explicitly excluded from the list of mandatory fields, and the lack of empirical evidence on whether publishing estimated value has a positive or negative impact on value for money, we are inclined to leave the field as optional in eForms. That way, each implementer can decide whether the field should be mandatory or optional.
