### ISSUE TITLE
BT-06 (Strategic Procurement); BT-774 (Green Procurement); BT - 775 (Social Procurement); BT-776 (Innovative Procurement). Description: Fields M and CM

### ISSUE THREAD

**Issue by jadelanava** [eForms/eForms#314]
We would like to understand better how this group of Business Terms works. 
The options that the BT-06 (Strategic Procurement) allows as indicated in the spreadsheet "5_eForms_ACPC_codelists_draft" are the following:
•	Reduction of environmental loss
•	Fulfilment of social objectives
•	Innovative purchase
•	None
 What would happen if a contracting authority manages a procedure in which two of the above options are met? Would you mark both? 
We propose that by indicating one of the options, for example "Reduction of enviromental," the BT-774 (Green Procurement) will be activated, and we suggest the same if the options "Fulfilment of social objectives" or "Innovative purchase" are marked.
In the event that the "None" option is marked, none of BT-774 (Green Procurement); BT - 775 (Social Procurement); BT-776 (Innovative Procurement) would be activated.
This would mean moving to "M - Mandatory" field BT-06 (Strategic Procurement )and move to "CM - Under certain conditions (specified by the Publications Office of the EU) to notice must contain this information to be published on TED." fields  BT-774 ( Green Procurement), BT - 775 (Social Procurement) and BT-776 (Innovative Procurement).

**Comment by JachymHercher** [comment]
> What would happen if a contracting authority manages a procedure in which two of the above options are met? Would you mark both?

Yes, both would be marked. 

> We propose that by indicating one of the options, for example "Reduction of enviromental," the BT-774 (Green Procurement) will be activated, and we suggest the same if the options "Fulfilment of social objectives" or "Innovative purchase" are marked.
> In the event that the "None" option is marked, none of BT-774 (Green Procurement); BT - 775 (Social Procurement); BT-776 (Innovative Procurement) would be activated.

This indeed seems as the most reasonable approach. This is probably the way it will be implemented in eNotices, the Publications Office-run system (@Annalisavacca). Concerning national/regional systems, we would suggest taking the same approach, but this decision falls to those managing the national/regional level systems.

The approach above works regardless of whether the fields are marked as O or M/CM at the EU level, because Member States can change them to M/CM at the national level. Concerning making them mandatory at EU level, we will further consider it, but given that quite a few Member States are against it - and other can make it mandatory without an EU-level obligation - we are rather inclined to leave this decision at the national level.
