### ISSUE TITLE
BT – 67: Exclusion Grounds. Description: Optional field in CN under Directive 2014/24/UE.

### ISSUE THREAD

**Issue by jadelanava** [eForms/eForms#315]
We have checked that BT 67 (Exclusion Grounds) appears as "M - Mandatory" for the CN General under Directive 2014/24/UE in the document “4_eForms_ACPC_Annex_Table2_spreadsheet”and for the other types of notices it appears as "O - Optional". We would like to know if this is an erratum, being the field BT 6 7(Exclusion Grounds)"O -ptional" as in the rest of notices.
If not, we propose that this field in the CN General under Directive 2014/24/UE will be moved  to "O - Optional", since the “Exclusion Grounds” would not make sense according to our legal system.

**Comment by JachymHercher** [comment]
The field is included as mandatory because it is requested in Directive 2014/24/EU Annex V Part C Point 11: 

> Conditions for participation, including:
a list and brief description of criteria regarding the personal situation of economic operators that may lead to their **exclusion** and of selection criteria; minimum level(s) of standards possibly required; indication of required information (self-declarations, documentation).

There is no such requiement for the other notices, which is why the field is left optional in such cases.
