### ISSUE TITLE
BT-756 (PIN Competition Termination); Any: Is this BT really needed?

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#316]
Could you please clarify why -in which situation(s)- BT-756 is actually needed?

If the PIN is used as call for competition then wouldn't BT-142- Awarded:Indicator and BT-144 Not Awarded Reason:Code be sufficient to determine that no further contracts will be awarded?

Tks.

**Comment by JachymHercher** [comment]
The codelist for BT-142 (Winner Chosen) currently is:
- The winner was chosen.
- The winner was not yet chosen, but the competition is still ongoing.
- No winner was chosen and the competition is closed.

The way it is, the codelist for BT-142 could not be used to replace BT-756 (PIN Competition Termination), because if "The winner was chosen" it is not clear whether "further contracts will be awarded". However, if "The winner was chosen." was replaced by the following two codes: 

- The winner was chosen and no further winner will be chosen. 
- The winner was chosen, but further winners may still be chosen.

Then indeed BT-142 could be used instead of BT-756, which could be removed. Since, as mentioned in https://github.com/eForms/eForms/issues/251#issuecomment-471165788, BT-766 (Dynamic Purchasing System Termination) exists as a separate indicator mainly to have a design similar to BT-756, then if BT-756 is removed, then BT-766 could be removed as well. (Furthermore, for slightly more transparency, the detailed codes could also be used in the context of framework agreements to inform about cases when a framework agreement was no longer used.)

(BT-144 (Not Awarded Reason) would only be used if BT-142 is equal to "No winner was chosen and the competition is closed", so should not be relevant for this case.)

**Comment by JachymHercher** [comment]
Upon further reflection, the semantics of the codelist BT-142 can become quite heavy if it tries to play the role described above. First of all, regardless of the discussion above, rather than "The winner was chosen", it needs to be "At least one winner was chosen". Furthermore, the "no further winner will be chosen" is ambiguous, because it mixes the information about "further contracts being awarded to existing winners (= parties to the DPS/FA)" and "new contracts being awarded to new winners (=new parties to the DPS). 

We've thought about it for quite a bit, but in the end we did not find a solution which would be simpler than the current one.
