### ISSUE TITLE
BT-01 Procedure Legal Basis

### ISSUE THREAD

**Issue by jseguraf** [eForms/eForms#317]
The BT01 - Procedure Legal Basis should be renamed as Legal Basis as not all the PIN notices are Call for Competitions: those that are PIN at planning time may not be aware yet of what call for competitions/procedures will be launched: how can then such a PIN refer to a procedure?. For example, there are notices that still know the procedure of PIN procedure. In addition, the definition should be also changed to remove the mention to the procedure.

**Comment by JachymHercher** [comment]
You are correct that in a simple PIN, it doesn't have to be clear how many procedures there will be. However, we're not sure how this causes a problem with the legal basis. Since the PIN needs to be published under a certain directive, all the procedures resulting from this PIN also need to be published under a certain directive. So, regardless of their number, they should have the same legal basis. 

To be 100% accurate, you are right that a small change of wording would be in order.

> The legal basis (e.g. a European Directive or Regulation, national law) under which the procurement procedure takes place _or, in case of prior information notices, under which the procurement procedure(s) will take place_.
