### ISSUE TITLE
BT-13710 (Award Criteria Lot Identifier); Missing

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#320]
https://ec.europa.eu/transparency/regcomitology/index.cfm?do=search.documentdetail&Dos_ID=17796&DS_ID=62369&Version=1

BG-707 (Award Criteria) is "This information may differ per lot." but there is no longer a BT-13710 (Award Criteria Lot Identifier) to identify the lot.

**Comment by JachymHercher** [comment]
Thank you for the comment. In fact, almost all "XYZ Lot Identifier" BTs have been removed from the spreadsheet. Instead, if information in a section can be repeated per lot, this is mentioned in the description with the sentence "This information may differ per lot." 

There were several reasons for doing so: 1) from a technical point of view, the identifiers may end up being solved differently (e.g. in the ESPD, lot identifiers are attributes of each element). @yvesjo is working on this; 2) to reduce the complexity of the proposal; 3) because it is an unnecessarily technical detail for an implementing regulation.

**Comment by jpmckinney** [comment]
Aha, makes sense. I will pay closer attention to the sentences "This information may differ per lot."
