### ISSUE TITLE
Where are bargain purchases?

### ISSUE THREAD

**Issue by ColinMaudry** [eForms/eForms#324]
Hi!

In the current forms, the buyers can specify that part of the awarded contract is a bargain purchase (section V.2.6)).

Won't this concept be supported by eForms?

See also https://github.com/open-contracting-extensions/european-union/issues/45

**Comment by JachymHercher** [comment]
Bargain purchases are purchases made in line with Art. 50(h) of Directive 2014/25/EU. They don't need to be modeled separately, because you can inform about their value the same way as about any other value; and you can highlight that it was a bargain purchase by selecting the code "Bargain purchase taking advantage of a particularly advantageous opportunity available for a very short time at a price considerably lower than market prices" in the BT-136 (Direct Award Justification Code). (See the latest version of the codelists or https://github.com/eForms/eForms/issues/295#issue-420596709).
