### ISSUE TITLE
BG-705 (Other requirements) What happened to "Information about a particular profession"? (III.2.1)

### ISSUE THREAD

**Issue by ColinMaudry** [eForms/eForms#326]
Hello there,

I wonder what happened to section III.2.1 "Information about a particular profession" from the current forms.

It seems to be a requirement, but I don't see a matching BT in BG-705 "Other requirements". What would be the corresponding BT in eForms?

Thanks!

**Comment by jpmckinney** [comment]
@JachymHercher We are looking for clarification on the correspondence in eForms of the following elements from the current forms:

III.2.1 Information about a particular profession (only for service contracts)
* Execution of the service is reserved to a particular profession
* Reference to the relevant law, regulation or administrative provision

#296 introduced BT-736 (Reserved Execution), which works for III.1.5 The execution of the contract is restricted to the framework of sheltered employment programmes. However, it is possible for the execution of a contract to be reserved to both sheltered employment *and* particular professions, for example, https://ted.europa.eu/udl?uri=TED:NOTICE:1668-2018:TEXT:EN:HTML, where the profession seems to be architectural/engineering ("ABK 09").

**Comment by JachymHercher** [comment]
We did not keep explicit fields for "Execution of the service is reserved to a particular profession" and "Reference to the relevant law, regulation or administrative provision", because they can be included in the description of the selection criteria on "Suitability to pursue the professional activity" (i.e. via BG-702 where BT-747 is equal to "Suitability to pursue the professional activity"). Separate fields might have made sense if there was some structured data on the type of professions etc., but that is not the case - they were just (rarely used) free text fields. 

In principle, I guess these restrictions could be combined (e.g. if you need a team containing two types of actors for which it is possible to reserve a contract.)

**Comment by jpmckinney** [comment]
With respect to the legal distinction made between restrictions on participation (selection criteria) and restrictions on execution in https://github.com/eForms/eForms/issues/296#issuecomment-472861002, I had thought that "Execution of the service is reserved to a particular profession" was a restriction on execution. Is it actually a restriction on participation (as you describe)?

**Comment by SellittoGiampaolo** [comment]
In principle, restrictions on participation hamper competition, therefore the Contracting Authorities shall not pose further conditions on participation other than those listed in the directives.
Restrictions on execution do not necessarily hamper competition, since the economic operator can fulfill them _after_ the award of the contract , when he is sure that he will have a return on the investment.
One example: in a tender for some cooking services the Contracting authority cannot impose that the EO is located next to the point of execution of the service, but the CA can extabilish that the winner has two months to find a location within five minutes from the point of delivery, as this is not a limitation that hampers competition (CA is not fixing a rule based on the current participants' characteristics) but a rule that acts after the competition has taken place and has its own reason, in relation to the service itself (CA needs freshly cooked food, not food delivered from a far point of service). 
This kind of conditions are likely to find more space when the carbon footprint will enter in the sustainability balance for public expenditure.

**Comment by JachymHercher** [comment]
@jpmckinney Probably yes. Looking at what the Directives say in the context of particular professions (below), the difference between "participation" and "execution" is not too clear. I'm not sure whether we can say that "restrictions on participation" are totally the same thing as selection criteria. For example, I guess I could have a selection criterion "You are listed as a qualified mason or you can give proof that you will be listed as a qualified mason before the estimated time of contract execution". In any case, I think here we are getting more into interpreting the law than we want to... 

1) Annexes (just looking at 2014/24/EU)
- In most annexes, under the heading "conditions for participation" there is "where appropriate, indication whether the provision of the service is reserved by law, regulation or administrative provision to a particular profession," Understanding "provision" as pretty much "execution", this seems to merge "participation" and "execution" quite a bit. 
- In case of the design contest notice, it says specifically that "Where appropriate, indication that the participation is restricted to a specified profession." This makes sense, because in design contests, there is no execution. 

2) Art. 58(1) (Selection criteria)
"They shall limit any requirements to those that are appropriate to ensure that a candidate or tenderer has the legal and financial capacities and the technical and professional abilities to *perform the contract* to be awarded." So again, the condition to participate is linked to conditions to execute. 

I'm also not sure whether this means something for the approach taken in #296.

**Comment by jpmckinney** [comment]
Okay, so coming back to the first question, these elements from the current forms would correspond to BG-702 (Selection Criteria)?

We are preparing extensions for OCDS and are attempting to support both eForms and current forms. It seems these elements don't belong in BG-711 (Contract Terms) since they are not clearly or exclusively about execution (like in the case of a design contest). I suppose they might better fit in BG-705 (Other Requirements) since they are also not clearly selection criteria, and more specifically they might be something like 'Reserved Participation Other', to complement BT-71	    (Reserved Participation).

**Comment by JachymHercher** [comment]
Yes, they fall within BG-702 (Selection Criteria). 

Putting them in BG-702 or BG-705 sounds totally fine.
