### ISSUE TITLE
BT-660 Framework Estimated Value 

### ISSUE THREAD

**Issue by jseguraf** [eForms/eForms#329]
This BT only occurs in the result. However, there is already a Framework Maximum Value in the result (BT-709). There is also an Estimated Value that refers to Framework Agreements in planning, competition and result (BT-27). It is therefore unclear what this BT-660 refers to. Is it not a repetition of the BT-27?

**Comment by JachymHercher** [comment]
In eForms, the word "estimated" is used in two different senses. As written in BT-27, "Estimated refers to estimation at the time of launching the call for competition". By contrast, as... not written(*)... in BT-660, estimated refers to estimation at the time of concluding the framework agreement. In other words, BT-27 is about estimating what price the market will offer, while BT-660 is about estimating how much I will actually buy (because, in framework agreements, that's not known). 

BT-660 is essentially a complement of BT-709, introduced because in some countries, when concluding framework agremeents, only the maximum value is known (and this may be legally binding), while in other countries only a very rough estimate is made of how much will be spent. (Again: note that the BT-27 estimate is made _before_ knowing the market's offer, BT-660 is essentially a "re-estimate" taking in account the market's offer and, possibly, updated needs.) These numbers will definitely be very rough - and that's ok (for a discussion of this subject, see e.g. https://github.com/eForms/eForms/issues/154). 

*We do agree that the terminology for BT-660 could have been clearer. In a future version of eForms, it may be worth adding a sentence along the lines of “Estimated refers to estimation at the time of concluding the framework agreement."
