### ISSUE TITLE
BT-147 (Received Tenders EU); Description; Value calculation

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#34]
How is this to be calculated? By the postal address or the bidder? Does BT-706 have to be taken into account?

**Comment by JachymHercher** [comment]
It should be the country in which the bidder is registered. We will clarify this in the description of BT-147  as well as all other "received tenders ..." BTs (BT-152, BT-146, BT-148, BT-723). For example, "Number of tenders received from other European Economic Area countries than the country of the buyer" should be changed to "Number of tenders received from _tenderers registered in_ other European Economic Area countries."

BT-706 should not be taken into account, that refers to the parent company. 

Do you find the change above sufficiently clear?

**Comment by ognyami** [comment]
For both BT-147 and BT-723 (Received Tenders EU and Received Tenders Non EU), even after the clarification that the country of registration of the bidder is taken into account , there will be many difficulties to make the right choice how to fill in the respective field in a number of cases, for example:
- tender submitted by a branch registered in country A of a company registered in country B. From which country is the tender received?
- tender for a framework agreement, submitted by a group of tenderers using subcontractors, all of which (group members and subcontractors) registered in different countries both inside and outside of the EEA. How the "majority of the works" will be calculated?
- in case of joint procurement, if the contracting authorities are seated in different members states,  - which tenders will be counted as submitted by "other country than the country of the buyer."?

What is the purpose of requesting the information in BT-147 and BT-723 and isn't there an easier way to collect it, without requesting the contracting authory to fill in extra fields in the CANs with a high probability of mistakes and misinterpretations?

**Could you please re-open this issue?**

**Comment by JachymHercher** [comment]
BT-147 and BT-723 are requested by the directives (See e.g. 2014/24/EU Annex V Part D Point 11(B). The data is crucial when negotiating the directives (because the single market is the main aim of the directives and knowing the number of foreign bidders and contractors is necessary to understand how the single market is doing and why) and also when negotiating in the WTO's General Procurement Agreement (essentially the same logic as above, just between EU and USA, Japan, etc.) 

In the cases you mention:
- Country A. (We ask only about registered country.) 
- It will be a very inaccurate estimate. 
- This is a matter of definition, we suggest including the companies only when they are foreign to all the buyers. This means that in the description of BT-147 "country of the buyer" should be replaced with "country of the buyer (or all countries of all the buyers"). Would you agree?

As a general comment, we agree that some of this information will necessarily be imprecise. Nevertheless, the legislator seems to have chosen that imprecise is better than nothing. (Which, personally, I would agree - as long as it is only "imprecise" and not "totally wrong". In this case, I would guess it is just imprecise.)

**Comment by ognyami** [comment]
What 2014/24/EU Annex V Part D Point 11(B) requires is that the PIN should include information on the **number of tenders received from another Member State or from a third country**.
It doesn't require information on the countries where the legal person submitting the bid is registered and if the purpose of the legislator was to collect credible information on cross-border bids and bids from third countries - providing this information will not help.
It would serve better the purpose of the law if we provide information on the actual country of origin of the tender - for example in the first case mentioned above, it would be Country B. The branch has no legal personality itself, but even if it would be a wholly owned subsidiary with separate legal personality, this wouldn't change the substance - the real/actual country  of the tender is Country B and this is what would matter to understand how the single market works or to negotiate trade agreements.
If the actual country from which the bid originates is not explored we open the door to easily circumvent the rules for access to market - a company from a country without access to the EU market can easily register a branch/subsidiary for the sole purpose to submit a bid, the new branch/company would rely on the capacity of the mother company to satisfy selection criteria and thus a bid from a country without access to EU market can win the call for tenders.
It would better serve the purpose of the law if we collect and publish information on the number of bids received taking into account the place where the ultimate parent company/the beneficial owner(s) are registered/residents (see the discussion on BT-706 - #13). Instead of collecting this information only for the winner, we can collect it for all tenderers and subcontractors mentioned in the bid through the ESPD. This would give a much clearer and more meaningful picture of where the bid actually comes from. 
In cases of joint procurement with contracting authorities seated in different members states - if a tenderer is from only one of those member states, this would still mean having a cross-border element that we need to capture. In this respect it would be more precise to add in the description of BT-147) a sentence of the type "If buyers are from different countries - number of tenders from European Economic Area countries that involve cross-border delivery"

**Comment by tinne** [comment]
From the discussion it seems to be advisable turning the Country of Origin into a business term in its own right which can it most cases easily be proposed by procurement management software and altered in the rare cases above.

**Comment by JachymHercher** [comment]
@ognyami You are right that the directives give just a general obligation. The role of the implementing regulation is to come up with a more specific definition that gives as relevant data as possible, while not being impossibly complex to implement. 

Since we are essentially talking about cross-border bids, we should keep in mind how cross-border happens (see research by [GROW](https://publications.europa.eu/en/publication-detail/-/publication/5c148423-39e2-11e7-a08e-01aa75ed71a1), people from [DG TRADE](https://www.ceps.eu/system/files/PB339TTIPandPublicProcurement.pdf), closely linked to the concept of [country of origin](https://en.wikipedia.org/wiki/Country_of_origin)): 
- "Direct cross-border procurement" = company based in country A submits a tender in country B
- "Commercial presence procurement" = company based in country A has a subsidiary in country B, the subsidiary submits a tender in country B
- "Value added indirect international procurement" = company in country X subcontracts to a company in country A which submits a tender in country A (This can go as far as global value chains, i.e. how do we count the value of a car made in country A, with screws from country C, made from resources extracted in country D, made from...) 

There are two main takeaways from this classification. First, any measurement will be just an approximation (especially since the last of the modalities can and does occur with the previous ones). Second, different types of cross-border don't have the same measurement difficulty. The first one is reasonably easy (just check your company documents); the second one is tricky but can be possible, also depending on how your systems are interconnected and how precise you want to be (that's what we're aiming for with BT-706 (Winner Parent Country) (see #13); the third one is partially difficult with the notices that we use in the procurement directives (e.g. subcontractors don't need to be known when the CAN is published) and partially impossible (the screws etc. story). 

Concerning your proposal:
- Since we have at least two viable mechanisms to get this information without an absurd administrative burden (ESPD & anti-money laundering directive registers), this is not an impossible idea. Still, at least some EU countries will not have these mechanisms in place and for those it would be impossible to implement. Thus, we will suggest it as an extension. (Assuming we find a reasonable definition of ultimate ownership, see #13). 
- This field should be an _addition_, not a _replacement_ of BTs on direct cross-border. This is because the proportion of direct cross-border itself is quite important: you could argue that the whole point of the procurement directives and the GPA is to facilitate direct cross-border bidding, for everything else it's enough to have the freedom of establishment. (You could also argue the opposite of course, that the benefit is about legal harmonization, which then lowers costs for foreign companies to navigate the new foreign procurement system...)

> If the actual country from which the bid originates is not explored we open the door to easily circumvent the rules for access to market - a company from a country without access to the EU market can easily register a branch/subsidiary for the sole purpose to submit a bid, the new branch/company would rely on the capacity of the mother company to satisfy selection criteria and thus a bid from a country without access to EU market can win the call for tenders.

That's not really a circumvention, that's often how it works... and it's fine. The goal of procurement legislation is just to make that process easier (by not _requiring_ the re-establishment).
