### ISSUE TITLE
BT-3201: Winning Identifier: missing DPS

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#36]
Just a note:
DPS missing from the description field

**Comment by JachymHercher** [comment]
This is intentional. We make a distinction between several similar but not fully identical cases:

- Winning _projects_ (the directive's terminology used for "tenders" in design contests)
- Tenders which do not yet necessarily lead to a single _winner_ (e.g. framework agreements with cascades; innovation partnerships)
- Winning tenders (most of procurement, in our opinion also including contracts in DPS)

Since DPS is not different than other winning tenders, we do not explicitly mention it.

Does this distinction work in the Finnish context?
