### ISSUE TITLE
BG-8: Not Published: which field would this be applicable?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#43]
It is not clear to me which fields the CA could refrain from publishing. The text refers to  Winning Tender and Procedure Lot Results but there are several fields under these BGs.

**Comment by JachymHercher** [comment]
Any BTs under the BG-320 (Winning Tender) and BG-137 (Procedure Lot Result) business groups can be unpublished. However, there must be a clear justification to not publish them and this justification must be given in the notice (both textual and using a code, see #44).

**Comment by MBucek88** [comment]
We think, that BG-8 Not Published should be applicable only for D25 and D81, please can you clarify this? 

According to D24 contracting authority (buyer) can´t mark parts of information in forms as "not published"?

**Comment by JachymHercher** [comment]
The BG is based on 2014/24/EU Art. 50(4). (You are right that in D25 and D81, non-publication is also mentioned in other places, which is not the case for D24 and D23.)

Please note that the national implementation of this provision, and BG-8 itself, may vary quite a bit, in particular depending on the interpretation of "public interest", "legitimate interests", etc.

**Comment by MBucek88** [comment]
Hi, we have one more question about BG-8. The group is named as "Not Immediately Published", whereas our question points on the word **Immediately** ?

There are some cases, where some information are not intended for publication ever. Not just for a limited time. Since BG-8 is the only group in the eForms about this kind of information, how it is possible to restrict the publication of some fields forever with proper justification, not just for a limited time. Because this group contains BT-198 Unpublished Accessibility Date (data type Date). This BG-8 does not contain any BT about restriction "is not intended for publication (ever)".

E.g. 2014/24/EU Art. 50(4) recognizes the possibility for some information to stay unpublished. But BG-8 is about "Not Immediately Published" so it counts with later publishing (BT-198 Unpublished Accessibility Date). 

Thank you in advance for your answer with the clarification. 

Michal

**Comment by JachymHercher** [comment]
@MBucek88 I responded in https://github.com/eForms/eForms/issues/335#issuecomment-955693880.
