### ISSUE TITLE
BT-200 (Modifications Reason Code); Data type; what would the codes be?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#46]
What would be the codes from where the CA can choose what is the reason for the modification?

**Comment by muricna** [comment]
The codes should represent: 

•	Need for additional works, services or supplies by the original contractor. 
•	Need for modifications because of circumstances which a diligent buyer could not predict. 
•	Other 

See discussion on buyer and procuring entity:  https://github.com/eprocurementontology/eprocurementontology/issues/95
