### ISSUE TITLE
BT-140 (Change Reasons); Data type; What are the codes?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#47]
What would the codes be from where the CA could choose the reasons?

**Comment by muricna** [comment]
The codes could include:

•	Correction of one or more mistakes 
•	Updated or additional information 
•	Correction of a publication error 
•	The original notice is cancelled
•	The buyer intends to cancel the original notice*
•	Publication of information which was originally postponed for reasons of law enforcement, commercial interests of an economic operator, fair competition or other public interest

**Comment by tinne** [comment]
What does the asterisk mean - a missing footnote?

Would the codes including cancellation be allowed for D81 only like today?

**Comment by JachymHercher** [comment]
@tinne Yes, it was removed. 

Could you elaborate a bit on the D81 question, please? (A priori, I would expect that D81 would be treated the same as other directives as far as cancellations go. The current treatment is only a result of the defence forms still being in the 2.0.8 format. Modifications, on the other hand, will be treated differently, because there are no/different provisions on modifications in the defence directives.)

**Comment by tinne** [comment]
It turns out I did not understand that there are two separate cancellation mechanisms foreseen for eForms notices, where the one involving BT-140 / a BG-9 section includes all notices with no competition (like PINs) and before the initial competition deadline, and the other involving BT-144 / a BG-137 section where the competition was run but the results were in a way that no contract would be signed.

To facilitate a premature cancellation regarding some lots only, BG-9 will become repeatable and get a lot reference, it also will be renamed accordingly.

**Comment by JachymHercher** [comment]
@muricna We should take into account that a cancellation could also just be about a lot. At the same time, it would probably be more informative if this was under the "cancelled" category than under the "updated information" category. What about changing:
- "The original notice is cancelled" to "The original notice or its lot is cancelled".  
- "The buyer intends to cancel the original notice" to "The buyer intends to cancel the original notice or its lot"

(The change BG will also allow giving reasons per lot, see https://github.com/eForms/eForms/issues/72#issuecomment-431840567.)

**Comment by eprocurementontology** [comment]
If we follow this logic then maybe cancellations of procedures should be taken into consideration.  If a Contract notice is cancelled it does not mean a corresponding PIN is cancelled.

**Comment by JachymHercher** [comment]
Yeah, the additions above essentially mean that we distinguish between a procedure and a procedure's lots and a notice and a notice's lots. BT-140 is used to explain the reasons for cancelling a notice or a notice's lot. 

Essentially, procedures (nor their lots) are never cancelled (or at least not directly). Directly, you cancel, for example, a call for competition notice in a procedure.
