### ISSUE TITLE
BT-04 (Procedure Identifier); Data type; Process for assigning the identifier

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#5]
There are two separate lines for procedure indetifier: one for PIN only and one for all the rest. I hope this is the same identifier. 

My second comment on the identifier concerns the stage the identifier is assigned to the procedure. The identifier should be assigned to the procedure at the stage and platform where the procudure is started. Assigning the identifier in TED is too late. This is not only an IT issue as we would need to agree on the form and syntax of this identifier. Ideally the identifier should identify the country, the eSender and even the platform that has initiated the procedure. 

**A solution:** 

**1. the Commission defines the syntax and assigns the following:**
- country code (two letter country code identifying the country e.g. FI)
- eSender (one letter, one number e.g. B2... if these were just numbers we might run out in the future)

If the notice is inputted directly in TED, TED could have it's own identifiers (e.g. still FI but for TED e.g. A1 = FIA1)

**These ones are for the countries to assign:**
- (if used, platform where the procedure was started (one letter, one number e.g. G9).
- unique number indentifying the procedure (six numbers and letters e.g. A356B3

If the notice is inputted directly in TED, TED could assign it's own identifiers.

Hence, in my example the number would be FIB2G9A356B3

Alternatively, if there is a syntax in the OCDS why not use that? However, the number should identify also the platform that has intiated the notice - sometimes it could be useful to know where the notice came from - particularly in troubleshooting cases.

**Comment by JachymHercher** [comment]
[1] BT-04 (Procedure Identifier) being on two rows is intentional. This is because for simple PINs, the BT can be repeatable (one identifier per each procedure), while for other types of notices it cannot.  

[2] There are essentially two basic approaches to constructing an identifier: semantic and asemantic. We are slightly inclined to use an asemantic procedure identifier, but the topic is still under analysis and we are happy for further exachanges. Please see below.
#
In a semantic identifier (for example the one you describe in your post), (some) parts of the identifier have a meaning. An asemantic identifier (for example the [universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)) serves no other purpose than identification. 

An advantage of a semantic identifier can be human readability. For example, a semantic identifier could be FI-HILMA-G9A356B3. Theoretically, it could even be FI-HILMA-_platformX_-_mainbuyerY_-_procedureZ_. On the contrary, an asemantic identifier is more likely to look like 123e4567-e89b-12d3-a456-426655440000. 

However, an important problem of semantic identifiers is how they deal with changes in their components. The procedure identifier must be, by definition, the same for the whole procedure. However, between the publication of the contract notice and contract award notice, the eSender/platform may change (e.g. because the buyer decides to change the eSender/platform; the eSender/platform goes bust). Theoretically, even a country may change (e.g. split into two); a buyer can change (merge/split/be renamed), etc. 

This problem can be mitigated by sticking to the information valid at the moment of publishing of the first notice. However, this reduces the usefulness of the "meaning" of the identifier. It also brings other challenges: e.g. validating that a notice about a given procedure truly comes from the given eSender. 

An advantage of asemantic identifiers is their simplicity: there is no need to keep and validate lists of components; there are no problems with changes of meaning in time. An ID is generated and used, that's it. This is currently the main reason why we are slightly inclined towards an asemantic identifier. 

Concerning approaches elsewhere: [OCDS uses a semantic identifier](http://standard.open-contracting.org/latest/en/schema/identifiers/); Prozorro (the Ukrainian award-winning OCDS-based system) seems to be using both a [TED-like ID and a UUID](https://prozorro.gov.ua/en/tender/UA-2018-06-22-002259-a). Would @timgdavies or @jpmckinney have any insights on this topic? 

#
[3] In your message, you also implicitly ask the question of what information about the process of publishing we should be collecting. This is a good question - regardless of whether we then decide to use this information also for identification. 

- Currently, TED already collects data on which eSender sent the notice. This is not public. Should it be?
- TED does not collect nor publish additional information about what happens before publication on TED (e.g. about "plaforms"; time of receipt of a notice by the eSenders). Should it?

(Clarifying question: when you mention platform, you mean "eSenders of eSenders", correct?)

**Comment by JachymHercher** [comment]
Thanks Tim, sorry for my mistake. So the OCDS prefix is asemantic; the rest of the contracting process identifier could be either.

If I'm not mistaken, currently, an OCDS prefix can be given to anyone who publishes data - regardless of whether it's a publisher on behalf of other buyers (e.g. Contracts Finder, Digiwhist) or an individual publisher who is also a buyer (e.g. Norfolk Country Council, Ministry of XYZ). How would OCDS deal with a situation when a buyer wants to publish part of the data on a contracting process through one publisher and later on with another publisher? 

Also, out of curiosity: if you have a register of prefixes, why did you keep them asemantic? I always saw the main advantage random characters as a way to be able to generate IDs without a register. If you have a register anyway, wouldn't it be better to make it more readable by letting publishers choose under which prefix they want to publish? If not, what were the reasons to avoid that - the danger of changes mentioned above?

**Comment by timgdavies** [comment]
> How would OCDS deal with a situation when a buyer wants to publish part of the data on a contracting process through one publisher and later on with another publisher?

AFAIK, we don't have a solid agreed mechanism here right now. We encourage *re-*publishers of data to use any `ocid` provided by the most 'official' source where this is available, but in cases where there are multiple 'official' sources (e.g. the procurement dept publishing tender and award info, and a finance dept publishing implementation spend data) we encourage those publishers to co-ordinate about the `ocid` prefix (and the internal identifier suffixed to it) to use. 

> If not, what were the reasons to avoid that - the danger of changes, as mentioned above?

Yes. Both the risk of changes, and the risk of semantics being read into the identifier that are not really there.

**Comment by tinne** [comment]
There is a point already missing in this discussion central to assigning procedure identifier which is important regardless of whether the IDs assigned have any semantics or are purely artificial.

As you already pointed out, the whole objective is to have globally unique values. Therefore, there must be a way to either decentrally generate those values where people can be sure that they never collide or have a central source which distributes them. 

The UUID numbering schema is an example of a randomly generated number which is expected to collide very seldomly. This is typically checked by the very simple Monte Carlo strategy: pick a UUID until there is none such already in the central database. Without an easily accessible central database, late collisions could occur.

Alternatively, you could create identifier groups (in semantic IDs, these would be ”prefixes“ in the sense of ID set sub-spaces) which can then by used (in principle, even offline) by distributed tenderers.

- What ID generation strategy do you plan?
- What technical infrastructure do you introduce to support this?
- Do you envision them to be used for use in national tenders, too?

**Comment by eprocurementontology** [comment]
This topic has been largely discussed in different fora (e.g. OP, DG JUST, DG GROW, DIGIT, etc.) and for different business cases. 

In the end, many of these discusions ended admitting that:

1) It is also very convenient that the ID contains the identifier originally issued by the Procuring Entity (the Buyer) for its procedure. This way it is easily recognisable/searchable by everyone involved in the procedure. In UBL this is what they call the ContractFolderID.

2) The concatenation of the ID of the Procuring Entity (Buyer ID), plus optionally its Country Code, to that internal procuring procedure ID cast a unique EPPI (European Procurement Procedure ID).

This method is based on practices such as the IBAN (banking domain) and BRITE (European Business Registers basis for the identification of companies, inspiration for the BRIS, the Business Registers Interconnection System).

The advantages are the ones you point at in your comment above:

1- No need for centralised systems to create and manage the IDS
2- The "owner" of the ID feels comfortable while building the ID and has to do no effort to think of strange syntaxes nor rules;
3- YOU ACTUALLY DON'T REALLY NEED AN ID FOR A UNIQUE PROCUREMENT PROCEDURE AT  ALL, but only the internal buyer id. The rest is about concatenating values that are already available in the documents or in the databases, such as the buyer ID, the Buyer's country code, and its conctract folder (file) id.

We're eager to discuss this further. At the OP we have thought of at least another solution. But for me this is the best method. 

KR

**Comment by paulakeen** [comment]
At the OP they have an alternative proposal for the EPPI (European Public Procurement Identifier). Please ask OP for it.

**Comment by paulakeen** [comment]
Just one personal consideration:

If a legal instrument/solution is not provided to enforce that the organisations IDs are compulsorily supplied, either for the Procuring Entity, the Economic Operarators AND the Service Providers, any attempt to achieve TRUE transparency is bound to fail.

Otherwise we will have to think of alternative tricky and expensive strategems to come up with aproximative possible identitifications of these organisations....(which is a kind euphemism for not to write down that instead of transparency we'll get b*s*t).

But this is, of course, my frank opinion, which i think is largely shared by the Public Procurement Information Reusers.

**Comment by UHMYND** [comment]
Would an EU-wide procedure identifier be compatible with a national procedure identifier? Any potential issues here?

**Comment by JachymHercher** [comment]
@UHMYND They would be compatible in the sense that a procedure could have both a national identifier and an EU-wide identifier. From a purely technical point of view, having only an EU-wide identifier would be optimal. However, I would expect that some EU countries might want to keep an existing national identifier as well. For these cases, you have a good point - there should possibly be an additional optional BT to publish this "national procedure identifier" on TED, if it exists.

**Comment by paulakeen** [comment]
After many thoughts and reflections, **our** conclusion (stemming from several team brainstormings) is that unless a legal or organisational instrument is put in place to make compulsory that:

1. Each buyer identifies itself, and
2. Each document refers to one procurement procedure identifier (Internal Reference Number)

this will not be solved.

**Comment by YvesJo** [comment]
The current orientation for the EU-wide Procedure Identifier goes in the direction of UUIDs whose generation could be delegated to contracting authorities. This would offer some flexibility, eliminate impact other element could have when changed and has a clear and easy to handle format. The Procedure Identifier could also be generated anytime, given its value is specified at the time the notice is submitted and is unique (i.e. may only be reused for notices of a same procedure).
