### ISSUE TITLE
BT-510 (Organisation Street Name) / BT-511 (Organisation Street Number) / BT-512 (Organisation Postal Code) / BT-513 (Organisation Locality) /BT-514 (Organisation Country); Description; Consider alignment with EN 16931 BG-8 POSTAL ADDRESS group

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#50]

**Comment by JachymHercher** [comment]
There are two main areas where these are not aligned:

#### Structure ####
In eInvoicing, Buyer address line 1-3 serves the same function as eForms' BT-510 (Organisation Street Name) and BT-511 (Organisation Street Number). The eForms' approach has more structured data, which we think it is beneficial (e.g. it enables cross-checking cities with streets) and outweights possible (small) costs of implementation, which possibly existed for eInvoicing. So unless this approach poses problems for others, we would suggest keeping it. 

#### Terminology ####
In general, eForms use the word "Organisations" while eInvoicing "Buyer". This makes sense, because the BTs are used more generally in eForms compared to eInvoicing. 

Specifically, there are these individual differences:

eForms | eInvoicing
------------- | -------------
Locality  | City
Postal Code | Post Code
NUTS Code | Country Subdivision
Country | Country Code

I don't see a problem with aligning them. However, the only other question is whether the eForms wording has not been taken from another standard and what is the approach in the ontology. Do @muricna and/or @paulakeen have an opinion?

**Comment by RolfKewitz** [comment]
What's about the ISO-Standard **ISO/IEC 19773:2011** for structuring international addresses?

**Comment by paulakeen** [comment]
@RolfKewitz: sorry but i cannot afford spending CHF198  right now. If you're allowed to share the structure data then I'll peek into it.

@Jáchym: the eInvocing proposal makes more sense to me, e.g. the NUTS code is "just one" type of code, defined by the EU Eurostat Agency. Whilsth the term "Country Subdivision" is more reusable at the international level.

Kindly
paula
