### ISSUE TITLE
BT04 (Procedure Identifier); Repeatable; consider dropping multiple procedures in PINs

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#55]
There is a special notion of PIN only notices that they may contain several objects. In the current forms, this results in a repeatable section II, in the eForms structures under considerations in a repeatable procedure identifier and the complications discussed in #14.

In order to facilitate ”simplifying the forms by removing unnecessary differences and confusing concepts“ - is there any legally binding reason not to drop this notion? Any member state currently using these PIN notices can easily split any such notice by tendering object causing only minimal data overhead. An identical BT-22 Internal Reference Number could be used by any system attached to join them in subsequent processing steps.

**Comment by JachymHercher** [comment]
Very good proposal. Frankly, even though we considered this option, we assumed that it was a legal no-go and so we discarded it too early. After more careful analysis, however, we don't see a problem with proposing PINs only to be about only one procedure. Here are the reasons: 
- Reading carefully the directives, it does not seem that PINs must be applicable to multiple procedures. Furthermore, there is legal value in having the same approach for PIN, PIN time limits, and PIN CFC concerning the number procedures. Different basic structure of these notices is hard to defend. (PIN time limits and PIN CFC being only about a single procedure also suggests that this is a legally valid alternative also for PIN only.)
- Technically, this would significantly simplify the structure of these notices (see overview below). The technical or user cost, on the other hand, is practically non-existent. The only extra information to publish in case multiple PINs are used instead of a PIN about multipe procedures is BG-703 (Organisation) - typically just the buyer and review body. This information can be easily prefilled on the basis of pre-saved user data or other notices. 
- PINs with multiple procedures are actually not being used that frequently. Looking at the proportion of PINs which had more than one procedure, as a percentage of all PINs (roughly 13-17 thousand per year), we can see that that their use has undergone a steep decline from 16% in 2008 to less than 2.5% in recent years.  

Year | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 | 2015 | 2016 | 2017
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PINs with multiple procedures / all PINs| 16.0% | 13.9% | 14.3% | 5.3% | 4.1% | 3.2% | 3.3% | 4.3% | 2.3% | 2.4%

Specifically, aligning PINs only with other notices so that they refer to only one procedure would simplify the spreadsheet (and the resulting technical files) in the following ways:
- Instead of having a procedure identifier and procedure references, there could be just a single procedure reference per notice. This means removing all the BTs mentioned in #14 except BT-04.
- BTs and BGs which are currently repeatable for PINs only, but not repeatable otherwise, can be merged in one (non-repeatable) row each. This concerns BT-4 (Procedure Identifier), BG-36 (Duration), BG-61 (EU Funds), BG-702 (Selection Criteria), BG-705 (Other Terms Requirements), and BG-100 (Communication).  
- Potentially, this can also help simplify the structure of the notice identifier (see #6).

**Comment by JachymHercher** [comment]
Correction of the message above: removing multiple procedures for "PINs only" will not have an impact on the rows concerning BT-36, BG-61, BG-702 and BG-705, because those are repeated because of lots, not procedures. (Specifically, qualification systems do not have repeatable lots, while the rest does.) The rest stays as it is.

**Comment by JachymHercher** [comment]
https://github.com/eForms/eForms/issues/55#issuecomment-406038912 (above) is not quite correct. In particular, it mixes up "PINs with multiple objects of contract" and "PINs about multiple procedures" (i.e. PINs referred to from multiple contract notices). The latter is significantly more common: 

Year | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 | 2015 | 2016 | 2017
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PINs about multiple procedures / all PINs | 25% | 25% | 24% | 23% | 22% | 17% | 18% | 15% | 13*% | 13*%

(* proportions for more recent years might be slightly biased because the CN has not been published _yet_)

This shows that while PINs are rarely being split into multiple "object of of the contract", they do often lead to multiple procedures. For the purposes of eForms, we suggest that:
- Explicit modelling of multiple procedures in a PIN is not necessary (in line with what is stated above).
- PINs can be referred to from multiple CNs. This is a use case for BT-125 (Previous Notice Identifier). (see #7). 
- Together, the two points above mean that a having a procedure identifier in a PIN would be confusing (relevant for #5). Consequently, we suggest that PINs do not have a procedure identifier and instead a procedure identifier is allocated only when publishing a call for competition. (This is probably also a better modelling of reality, because considering a PIN as a start of the "planning phase" of a procurement procedure is not that intuitive.) 
- This also implies that there sometimes needs to be a notice identifier separate from a procedure identifier (relevant for #6). 

We note that PINs can be split into "lots". However, since there isn't yet even a "procedure", then these "lots" can perhaps be better understood as simple "parts" of this notice, which may become procedure in the future (or lots of a procedure, or nothing at all).
