### ISSUE TITLE
BT-510 (Organisation Street Name); Repeatable; two or more addresses

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#61]
In Germany, it is often necessary to give two addresses to be fully compliant to general legal and communications transmission: one to address letters (in larger organisations, mostly numbered postbox addresses or special zip codes) and one to address freight and actually meet employees (also, more importantly, used to summon entities).

We suggest extending the organisational data to allow to provide for at least another address.

**Comment by JachymHercher** [comment]
Thank you, this is important and interesting. We've discussed it quite a bit and then agreed, for simplicity's sake, to propose to stick to the current standard forms solution, which are non-repeatable addresses. Since currently there is only one organisational address and we have not received complaints about it, are you sure multiple are necessary? 

(E.g. in procurement, isn't the postal/communication address the one relevant? Other addresses can be exchanged elsewhere than in the forms; some other purposes are also covered by BT-133 (Open Conditions Place) and BG-708 (Place of Performance)?)

**Comment by tinne** [comment]
In electronic communications, the postal address seems to be increasingly irrelevant. We would thus agree to stay with one address per organisation only.
