### ISSUE TITLE
BT-512 (Organisational Postal Code); G-AP; conditionally mandatory rule?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#62]
The organisational postal code currently is optional for all roles and organisation could take. In which cases do you plan it to become mandatory?

**Comment by JachymHercher** [comment]
Since this information is fairly typical, necessary for postal communication, and can easily be prefilled automatically from user profiles; but cannot be reliably added to the data ex-post (see #9) we propose for it to be mandatory everywhere that a postal code exists. The exceptions to this would be buyers in countries which [do not have a postal code ](https://gist.github.com/kennwilson/3902548)(this is relevant mainly for embassies). Do you find this reasonable?

**Comment by tinne** [comment]
We do.
