### ISSUE TITLE
BT-506 (Organisation Contact Email); Description; GDPD based requirement

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#63]
Why does the description require: ”Unless necessary (in the sense of the General Data Protection Directive), the email must not allow the identification of a physical person?“

As every tenderer must obey to GDPD in their own right, it should suffice that the tenderer can provide consent or any other reason. Does the tenderer have to hand in proof of consent with the notice? Why is the Organisation Contact Telephone treated different?

The MUST-requirement of an non personal email address could imply a barrier for a small enterprise like a sole trader and should be dropped.

**Comment by JachymHercher** [comment]
The goal is to avoid unnecessary processing of personal data. Among other concerns, this will simplify (reduce) the need to later-on remove personal data information from notices on request (which raises various questions, because notices are a legal reference that, it can be argued, should be immutable by anyone except the buyer etc.) 

We've considering the following update of the definitions:

BT-502 (Organisation Contact Point) 

> The name of the department or other contact point for communicating with the organisation. To avoid unnecessary processing of personal data, the contact point may allow the identification of a physical person only when necessary (in the sense of the General Data Protection Directive).

BT-506 (Organisation Contact Email)? 
>The email for contacting the organisation. To avoid unnecessary processing of personal data, the email may allow the identification of a physical person only when necessary (in the sense of the General Data Protection Directive).

We've can also add a similar disclaimer to BT-503 (Organisation Contact Telephone)
>The telephone for contacting the organisation. To avoid unnecessary processing of personal data, the telephone may allow the identification of a physical person only when necessary (in the sense of the General Data Protection Directive).

Would this work better in your opinion?

**Comment by tinne** [comment]
It would, thank you.
