### ISSUE TITLE
BT-125 (Previous Notice Identifier); Data type; Is this needed when there is procedure identifier

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#7]
Is this needed at all of there is already a procedure identifier? I mean whith this procedure identifier one could find all previous notices concering the procedure, an I correct? 

Are there cases where a notice would not carry a precedure identifier?

**Comment by JachymHercher** [comment]
This is a very interesting idea. It sounds good, we don't see a problem with it. We will consider implementing it. More opinions would definitely be welcome though, as it's a fairly major change and it's important that we do not overlook some of its implications. 

When reflecting on it, we identififed two _potential_ problems, both of which can be resolved, however:

- Occasionally, a buyer wants to publish a CAN on TED even though he did not publish a CN on TED (but he published it elsewhere). This happens, for example, when an estimated value was below threshold (and thus the whole procedure is below threshold), but then the final value is significantly above the threshold... and thus the buyer decides to publish the CAN anyway, for transparency's sake. Overall, this happens very rarely and is legally questionable, so it probably shouldn't block your proposed solution.
- The definition of BT-125 (Previous Notice Identifier) mentions "Identifier of a previous notice within the same procedure or _otherwise relevant to this notice_." The second part refers to the case when a contract is directly awarded because a previous procedure didn't succeed in finding a contractor (see 2014/24/EU Art. 32 (2a)). In such a case, we suggest that the reference to the previous procedure should still be given. However, this does not require having "previous notice"  for all relevant notices. Instead, a "previous procedure" can be requested only in this specific case (where there was a previous, unsuccessful, procedure).

**Comment by manevmi** [comment]
Maybe this can be extended also to the Lot identifier in case of mult-lot procedures? In this case only the notices relevant to the lot will be shown.

In principle we are in favour - the more automation, the better (less risk of human error).

**Comment by JachymHercher** [comment]
I'm not sure I understand what you mean by the extending this to the lot identifiers. Could you elaborate a bit please?

**Comment by paulakeen** [comment]
@manevmi: me neither I do not understand the relationship between Lots and this issue. Can you elaborate, please?

By the way see also this [issue in ESPD](https://github.com/ESPD/ESPD-EDM/issues/140) about the multi-identifier of multi-lots.

KR

**Comment by JachymHercher** [comment]
@paulakeen, thank you for the comments. After some consideration, we would suggest that BT-125 (Previous Notice Identifier) is split into four separate "related" notice BTs (essentially for clarity, in line with e.g. #101 and #173). The four BTs would cover the following use cases: 
- Referring to a related PIN(s). 
- Publishing a "corrigenda" of a previous notice (in particular a CAN within a DPS or a framework agreement). 
- Publishing a "modification" of a previous notice (in particular a CAN within a DPS or a framework agreement).
- Referring to a failed previous procedure as a justification for a direct award (see above). 

No other cases seem to be necessary, because in all other cases the "sequenced family" is evident: one notice after another, no branches. This approach should also be in line with the four points you made in your message. 

@manevmi Yes, this should be possible by searching by a procedure identifier and a lot identifier (which will be unique within the procedure).

**Comment by tinne** [comment]
Do you expect buyers to link contract notices to a corresponding buyer profile entry? This would be one to many, too, wouldn't it?

**Comment by JachymHercher** [comment]
@tinne No, we don't. The buyer's profile is only given as a general website linked to the organisation. (Concerning one to many, I would guess all options are possible.)

**Comment by tinne** [comment]
Did you already work this out in spreadsheet form? I'd suggest the modelling attached in
[Previous Notice Adjustments.xlsx](https://github.com/eForms/eForms/files/2464158/Previous.Notice.Adjustments.xlsx), where the CMs depend on whether a Modification (BG-77) or Change (BG-9) section is given, respectively.
