### ISSUE TITLE
BT-717 (Modification Date); Description; effective or change; version

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#71]
When a modification to a running contract is made, I understand, a section BG-77 Modification is added to a new CAN notice. Am I right to expect this to replace the publication of a F20 notice in the current approach?

Does BT-717 denote the date the modification is decided upon or the date when the change becomes effective? Is there any reason to believe that maybe both dates would be useful to publish?

**Comment by JachymHercher** [comment]
Yes. 

We intended it as an analogy to BT-145 (Contract Conclusion Date), i.e. it should be the date of the signature of the modification. We assume that's enough, but we're happy to see some examples to the contrary. 

We will clarify the definition. Would e.g. "Date when the last contractual party signed the modification" work?

**Comment by tinne** [comment]
Regarding the definition, this will do, thank you.

As the whole alteration date discussion can be led in #72, I close this issue.

**Comment by JachymHercher** [comment]
Based on further discussions with @tinne, we will suggest to remove BT-717, because it is not necessary. The date of the contract modification will correspond to an updated value of BT-145 (Contract Conclusion Date). 

We have also added a contract identifier in BG-77 (Modifications), so that reasons can be given per lot (analogically to changes in https://github.com/eForms/eForms/issues/72#issuecomment-431840567).
