### ISSUE TITLE
BT-ALL; G-AP; Conditional Mandatory rules

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#74]
We would like you to generally include the rules when a CM business term or CM business group is mandatory (and when it is not) in the consultation at least in cases when this differs from the current situation (see, e.g., #62).

This could be done informally as part of the description.

**Comment by JachymHercher** [comment]
This is a similar case to that of codelists. We would propose to approach it similarly:

- Please request the rules explicitly on GitHub for selected BTs where you are very much interested. We will respond. 
- We will prepare a more comprehensive overview, which we will make available at the latest for the negotiation of the actual implementing regulation. However, we will present it separately from the consultation spreadsheet.

The reasoning for the above-mentioned approach is that contrary to the first round of the consultation (which was marked as too complicated), we have not included rules and codelists, because we are trying to keep the size of the consultation as small as possible. (Second, on the practical side of things, we are also still working on having these rules all written down in a readable, standardised etc. format.)
