### ISSUE TITLE
BT-08 (Organisation role); Data type; Code list

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#85]
Can you give the codelist of this business term?

**Comment by tinne** [comment]
As this list is relevant for defining the organisations for which you require organisational id systems #8, this would be important to know on short terms notice especially when roles are introduced that do not exist in the current forms.

**Comment by muricna** [comment]
My suggestion would be to have further business terms under organization.  This way we could clearly indicate what should be used where.

I think by putting these terms in a code list the clarity of the regulation will be reduced.  If a code list was used anybody consulting the regulation would not know which organization was to be represented in which case. 

The business terms that could be represented are:

•	Buyer
•	Procurement service provider
o	Procurement service provider - eSender
•	Contact point 
•	Central purchasing body
•	Winner 
o	Winner - Group leader
o	Winner - Group member
•	Review organization
•	Mediation organization

**Comment by JachymHercher** [comment]
@muricna thank you for the (possible) codelist. Concerning the proposal to split BT-08 (Organisation Role) this into multiple indicator BTs, here are my thoughts:
- As a general design principle in eForms, we have followed the approach of "whatever can be reasonably modelled as a codelist, is modelled as a codelist". The main advantage of this approach is brevity and flexibility (see also the discussion in https://github.com/open-contracting/standard/issues/572) 
- However, you are right that BT-08 is unique in a certain sense: it is the only BT where some values of a code are mandatory in every procedure (e.g. buyer), while others are mandatory only in some procedures (e.g. CPB) and still others are voluntary (e.g. mediation organisation). We establish clear obligations by listing them in the description of the field ("A notice must contain all organisations of the procedure which have the role of a buyer, a winner, a review body, a central purchasing body, or a consortium leader.") but it's an approach that is not used anywhere else in eForms.  

This approach also raises questions concerning another design principle in eForms - explicit declarations (for mandatory information) of something _not being_ the case (see e.g. #183). For example, in a joint procurement procedure with two buyers, one buyer could publish the notice without explicitly declaring that "no other buyer was involved in the procedure". We were planning to resolve this by adding, to the list of values above, something like "No other buyer, winner, review body, central purchasing body or consortium leader should have been included in this notice". However, this is not 100% elegant and may require re-wording at national level (e.g. if in some countries include procurement service providers as mandatory). On the other hand, splitting BT-08 into individual fields wouldn't probably make the situation much better.

I'd be grateful for more opinions on the topic.

**Comment by jpmckinney** [comment]
A form can have a list of yes-no elements, such that users are required to actively select a value, e.g.:

* Buyer: Yes / No
* Contact point: Yes / No
* etc.

However, the data format doesn't need to represent each of these as, e.g., two empty elements (like `BUYER` and `NOT_BUYER`) nested within an `option` tag in an XSD schema, or a boolean field in a JSON Schema. Software can take that input and store it as a list of items, each matching a code. In other words, the form's presentation doesn't need to match its serialization.

There are occasionally advantages to having direct alignment between presentation and serialization, but the expectation here is that users are not hand-crafting the serialized data. eForms should include guidance on how to present the form, to encourage correct and accurate data entry. It can also include business rules, like raising an error `if not any('buyer' in party['roles'] for party in parties)`.

**Comment by tinne** [comment]
As discussed in https://github.com/eForms/eForms/issues/80#issuecomment-405292337, we would like to document the need for the following code values (at least to support all possible organisations mentionable in below-threshold procedures):
- a body (possibly different from the buyer) which accepts and processes participation requests
- a body (possibly different from the buyer) which accepts and processes offers
- a body which provides access to the procurement documents (in case they are not exclusively available in electronic form)
- the body which will award the contract (if different from the buyer)

**Comment by JachymHercher** [comment]
@tinne, we've discussed the values you suggest a bit more and would like to ask additional questions. Generally speaking, the bodies 1-3 would fall under the Procurement Service Provider (or Buyer) roles mentioned above. Our main doubt is whether we need to specify these roles to such detail, or whether we can just leave it as general as Procurement Service Provider. 
1.  Why would such a body need to be specified concretely? For practical purposes, aren't BT-17 (Submission Electronic) and BT-745 (Submission Nonelectronic Description) enough?
2. Same as above. Additionally, in case of two-stage procedures, why would this information need to be given already in the notice (and not only later to the selected tenderers)? 
3. Why would such a body need to be specified concretely? For practical purposes, aren't BT-15 (Documents URL) and BT-615 (Documents Restricted URL) enough? 
4. Defining buyer as "Contracting authority, contracting entity, a defence contractor, an international organisation, or an organisation awarding a contract subsidized by a contracting authority", we're not sure if the last mentioned body can exist (i.e. if it "awards" a contract, it would be the contracting authority). Would you have an example? Wouldn't this be covered by CPBs? Or is this case rather about evaluation? (In which case we are again not sure how necessary it is.)

**Comment by ermeio** [comment]
"organisation awarding a contract subsidized by a contracting authority", we're not sure if the last mentioned body can exist (i.e. if it "awards" a contract, it would be the contracting authority). Would you have an example? Wouldn't this be covered by CPBs? Or is this case rather about evaluation? (In which case we are again not sure how necessary it is.)
I think that this is a case different both from the CPB and the evaluation:
an example is the case where private contractors or a group of private citizens realizes the roads, the 
sewage network and the lighting on behalf of the municipality in an  area destined for urban expansion and the total amount of these works is detracted from the soil concession fee.  The private contractor or the group of citizens is not a CPB and the case is not regarding evaluation... it is a case where a public contract is subsidized by a contracting authority (the municipality) but it is awarded by a private organization organization (the group of the citizens that have bought the soil or the provate contractor that will build the housings on that area)
We call them "opere a scomputo" in italy and , at least partially, they shall follow the Public Procurement regulation.

**Comment by JachymHercher** [comment]
@ermeio I apologize, my last comment was not clear. Point 4. was referring to point 4 of tinne's comment, i.e. we are not sure whether an organisation "the body which will award the contract (if different from the buyer)" can exist. 

Concerning "organisation awarding a contract subsidized by a contracting authority", this corresponds to the cases described in Art. 13 of Directive 2014/24/EU. 

Concerning the example you give, do I understand it correctly that those actors are an "organisation awarding a contract subsidiszed by a contracting authority"? (Alternatively, they could also be the concessioner or the subcontractors of the concessioner, depending on the exact legal set-up.)

**Comment by tinne** [comment]
Regarding roles 1, 2, and 4 as proposed, the main clue is to make one entity distinguishable from the others, e.g., in a joint buyer's effort to say one entity was responsible for the publication of the notice and the procurement documents, while another will be dealing with seller selection.
Regarding role 2, this is mainly important in single-stage procedures and follows our approach to give distinct names to different roles (one could role 1 and 2 into “body (possibly different from the buyer) which accepts and processes the participation requests or offers, whichever is requested”. A body implementing role 4 could be an executing entity which is assigned a certain seller from a holding which is responsible for procurement matters.
Regarding role 3, this is mainly important when focussing on procurement documents which are not freely or fully available in electronic form, which mostly matters for large construction procedures especially below the thresholds.

**Comment by tinne** [comment]
I wonder: why are the roles discussed in this ticket not part of the code list draft?

**Comment by tinne** [comment]
Is the organisation role mentioned in #125 now called “Procurement service provider that serves as a contact point”? This seems to be equivalent to role 3 of https://github.com/eForms/eForms/issues/85#issuecomment-427319710.

Regarding roles 1 and 2 as proposed, they are also kind of Procurement service providers, so I suggest to add the following codes:

1. Procurement service provider that processes participation requests
2. Procurement service provider that processes offers

Organisation role 4 as proposed corresponds to a scenario where a procurement service provider serves as main fronting body in processing the procurement and the buyer will ultimately contract the winner the service provider has selected for it.

**Comment by JachymHercher** [comment]
(On terminology, reusing "procurement service provider" instead of "body" would be fine.) 

Concerning 1., "Procurement service provider that serves as a contact point" doesn't seem to be the same as "a body (/psp) which provides access to the procurement documents (in case they are not exclusively available in electronic form)?" The former is broader, it can e.g. be the contact point for answering questions about the procurement documents. 

Concerning 4., would such a "main fronting body" take care of various steps in the procurement procedure? If yes, then perhaps it's easiest to just call it psp, without further specifications?  

Concerning 2. & 3., our main hesitation is that we don't fully understand why to give further details on 
these particular steps of the procurement procedure. There could be many others: responding to questions; responsible for the technical specifications; responsible for running the FA; responsible for the payments; etc. As mentioned in https://github.com/eForms/eForms/issues/85#issuecomment-447754653, there are BTs which make sure that the "practical" needs are met (knowing where to download the proc. docs; who to ask questions; where to submit). In https://github.com/eForms/eForms/issues/85#issuecomment-448229397, you mention it is important to know which body is responsible for what. But why, and why just these? As long as the practical needs are met, isn't that rather an internal question of the relevant contracting authorities? 

In Germany, this is currently collected in some notices?

**Comment by tinne** [comment]
The information is collected in practically all German below-threshold notices, with open procedures, "Address, where to the offers must be sent (main buyer or specify)", with restricted and negotiated procedures, "Address, where to the participation requests must be sent (main buyer or specify".

Also, regarding requests for tendering documents, a  different body may be given and all such forms (where the newest forms restrict this to non-electronic documents).

The main non-construction (UVgO) notices also differentiate the buyer addresses qualifying the main address "body inviting to tender" and an optional second "body awarding a contract".

I'll check about the other contact points you mention whether or not they are of any importance to our buyers.

**Comment by UlrikaSjoholm** [comment]
We find the option PSP confusing. If it is a PSP, that is not a CPB, that fills in the notice; should the information about the organisation (BT-500 etc.) be the PSP and not the contracting authority/entity? We question the importance to know if the buyer has used a PSP (in any part of the procedure). At least there is a need for a help text that explains what a PSP is.

**Comment by tinne** [comment]
Regarding https://github.com/eForms/eForms/issues/85#issuecomment-471532759 and the roles defined in https://github.com/eForms/eForms/issues/85#issuecomment-427319710, I checked with a multi stakeholder tutor / agent and found the following situations:

- An architect or construction engineer (company) works the technical details of a public procurement. They provide additional information on the tender (role 3) and/or create the selection criteria (role 1) and/or award criteria (role 2). In national / below-threshold contexts, they sometimes directly collect, open and value the participation requests (role 1) and offers (role 2) in care of the buyer.
- A central government agency consults a buyer with regard to a tender. The agency creates the contract notices and procurement documents and takes care of the whole process. In some situations, the actual body in need of the procured goods or services will have transferred funds to the agency, in which the agency acts as a CPB and the actual buyer would not necessarily be mentioned, or the actual buyer will ultimately be the buyer, in which case they assume role 4.

Both situations are such that all the other special responsibilities mentioned (responding to questions; responsible for the technical specifications; responsible for running the FA; responsible for the payments; etc.) are defined, but can for a usual seller be derived from the roles mentioned above, or must be found somewhere else in the procurement documents, at least in current practice.

**Comment by JachymHercher** [comment]
Reading the above, we understand the need for the following "roles". (Their technical implementation as roles, sub-roles, references etc. depends on the discussion in #285). 
1. Body receiving requests to participate (based on the above & #285)
2. Body receiving tenders (based on the above & #285)
3. Body providing offline access to the procurement documents (based on the above)
4. Body for asking questions (based on https://github.com/eForms/eForms/issues/125#issuecomment-424040269) 

We are not sure about the following:

a) Including "the body which will award the contract (if different from the buyer)". This is mainly because "award the contract" is too general. One option would be to keep it under the general labels of CPB and PSP. Alternatively, we could offer significantly more options and details, e.g. "Body signing the framework agreement", "Body signing the contract (other than a framework agreement)", "Body funding the procurement", "Body executing the payment". (This partially follows http://standard.open-contracting.org/latest/en/schema/codelists/#party-role.) 

b) the need to differentiate 1. & 2. above depending on whether they "receive and process" or only "receive". "Receiving" seems to be the main concern for companies and others.

**Comment by JachymHercher** [comment]
@UlrikaSjoholm A procurement procedure needs to have a contracting authority,  so just a PSP is not enough. The contracting authority could be a CPB though. (Buyer is defined as "Contracting authority, contracting entity, a defence contractor, an international organisation, or an organisation awarding a contract subsidized by a contracting authority.")

Concerning the importance of having information about the PSP, please see https://github.com/eForms/eForms/issues/42#issuecomment-401860118. Concerning the help texts in user interfaces, we agree (the definitions come from the directives).

**Comment by tinne** [comment]
@JachymHercher Your questions seem to be tangent to the level of details mostly.

b) In second stage procedures much communication happens outside of notices in the later talks between buyers and candidate tenderers, and the question is what information you wish to be in the notice regarding stage no 2. If it is sufficient to give information about the first tangible competition (be it on participation or actual offers), not differentiating might be enough, roles could be merged. If you see any chance (as the amount of information regarding Selection and Award Criteria suggests) to enhance information about stage no 2, keep them separate.

a) Is not body signing a framework or non-framework contract information duplication with regard to Techniques (or its successor BTs)? Else, further differentiation is OK with me as long as the necessary information can be published as well.

**Comment by JachymHercher** [comment]
Based on the above, it seems that there is demand for several new organisation roles. These specify "roles" which can be done by buyers, procurement service providers, and central purchasing bodies. Since these new "roles" can be shared by several types of organisations, it seems best modeled as a separate "sub-role" BT instead. (The alternative would be a classification with repeating values, but we should try to avoid duplication.) Thus, we would suggest the following: 

**BT-08 (Organisation Role)**
- Buyer
- Procurement service provider
- ~Procurement service provider that serves as a contact point~
- Central purchasing body acquiring supplies and/or services intended for other buyers
- Central purchasing body awarding public contracts or concluding framework agreements for works supplies or services intended for other buyers
- Winner
- Subcontractor
- Mediation organization
- Review organization
- ~Organisation providing more information on the time limits for review procedures~
- _TED eSender_
- _Organisation providing information concerning the general  regulatory framework for taxes applicable in the place where the contract is to be performed_.
- _Organisation providing information concerning the general regulatory framework for environmental protection applicable in the place where the contract is to be performed_.
- _Organisation providing information concerning the general regulatory framework for employment protection and working conditions applicable in the place where the contract is to be performed._
(The last three codes are based on Directive 2009/81/EC Annex IV PIN Point I and replace BT-80, BT-82, and BT-84).

**BT-770 (Organisation sub-role)**, a repeatable code with a description of "The sub-role of the organisation in the procurement procedure (e.g. group leader, organisation providing additional information about the procurement procedure)."
1. Group leader
2. _Organisation providing additional information about the procurement procedure_ (based on the requirements from point I of the different parts in Annex V)
3. Organisation providing offline access to the procurement documents
4. _Organisation providing more information on the time limits for review procedures_
5. Organisation receiving requests to participate
6. Organisation processing requests to participate
7. Organisation receiving tenders
8. Organisation processing tenders
9. Organisation signing the contract 
10. Organisation whose budget is used to pay for the contract
11. Organisation executing the payment 


This should be accompanied by business rules establishing that:
- "Group leader" must be a "winner" or a "buyer", "procurement service provider" or "central purchasing body" for winning tenders / lots with winners, buyers, etc. linked with them. 
- All the other codes in BT-770 must have BT-08 equal to "buyer", "central purchasing body...", "procurement service provider". 

Also, it seems that BT-08 can be changed to non-repeatable.
