### ISSUE TITLE
BT-513: Organisation Locality: make it easy also in TED

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#9]
We would not be filling the TED eForms in TED but fill these in eTendering platform that first sends the notice to national eSender and then to TED. However fro those that use TED there should be postal code / locality checker (just like in webshops) that allows only certain types of postal code and locality combinations.

**Comment by JachymHercher** [comment]
We agree. Please note this applies to various parts of the address (e.g. country from NUTS; NUTS from postal code; postal code from locality, locality from street). To some extent, we are considering to cross-check this information with a business rule for TED. 

These relationships can also be used to reduce manual entry in any interfaces (e.g. prefilling postal code on the basis of the locality).

Technical implementation at EU level might take some time however, because [postal codes are not publicly available for all countries](http://ec.europa.eu/eurostat/web/nuts/correspondence-tables/postcodes-and-nuts); maintaining a 100% accurate street-locality matching is not trivial; etc. Systems at national level in countries where such information is of good quality might have an easier time implementing such rules/prefilling tools.
