### ISSUE TITLE
BT-98: Tender validity deadline, data type

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#90]
Wouldn't it be more interesting to express this business term as a date, because the expression in number of days can be confusing for the economical operator (working days/calendar days).

**Comment by JachymHercher** [comment]
We think the number of days is preferable, because it can stay the same even if the tender submission deadline gets postponed (which happens fairly regularly). Otherwise, it can easily happen that people change the tender submission deadline, but forget about moving also the tender validity.

In line with #83, the definition should be changed to: 

> "The number of _calendar_ days from the tender submission deadline for which tenders must remain valid."

**Comment by tinne** [comment]
Could have data type Duration as discussed in #83, too.
