### ISSUE TITLE
BT-06 (Strategic procurement); Data type; Code list

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#93]
Can you give the codelist of this business term?

**Comment by muricna** [comment]
The codes should represent:

•	Reduction of environmental impacts
•	Fulfilment of social objectives
•	Innovative purchase

**Comment by JachymHercher** [comment]
@muricna, based on #156, since this field is mandatory, we need one value indicating that no other values apply. These types of codes should probably be phrased similarly for all similar fields. Here are two ideas for the code (keeping in mind its definiton): 
- "No technical specifications, award criteria and contract performance condition aim to reduce the environmental impacts of the procurement, fulfill social objectives and/or buy an innovative work, supply or service."
- "No."

**Comment by StHoh** [comment]
Would this following model, based on your wording, be feasible? 

(1)
> technical specifications, award criteria and contract performance condition aim to reduce the environmental impacts of the procurement, fulfill social objectives and/or buy an innovative work, supply or service

[Y/N], if Y -->

(2) Specification of respective sustainability and innovation criteria (Indicator)?
Answer Options: 
- social criteria (Y/ N) AND
- ecological criteria (Y/ N) AND
- innovation criteria (Y/ N) 

if any Y --> 

(3) 
Which stage of the tendering procedure do/does sustainability criterion/criteria refer to (Identifier)? 
Answer options : 
- technical specification (Y/ N) AND
- selection criteria (Y/ N) AND
- award criterion (Y/ N) AND
- contract performance condition (Y/ N) 

If any Y -->

(4) Means of proof or certificate requested for ensuring sustainability criteria (Identifier)?
Answer options: 
- Label(s) (Y/ N) OR
- Declaration by tenderer (Y/ N) OR
- Others (Y/N)

If Y and if technically feasible -->

Description of criterion? Further specifications? 

[additional free-text field]

**Comment by JachymHercher** [comment]
@StHoh thank you for the proposal. A few comments:

- Technically, it seems feasible.
- Practically, we find it unlikely that buyers would be willing to fill in such detailed information. Consequently, we find it unlikely that EU countries would be willing to include all this information as mandatory, possibly even optional. Nevertheless, we are open to have the discussion - please coordinate with the German representative in the expert group adopting the act to bring up the topic. 
- Otherwise, it can still be included as an optional extension (which can then be made mandatory by implementers at their discretion). Extensions will be discussed in more detail after the adoption of the act.

**Comment by UHMYND** [comment]
Is there any available information on the proposed code-list? Do I understand correctly that the strategic priorities (environment, social, innovation) will be separated and allow for multiple choice?

**Comment by JachymHercher** [comment]
@UHMYND  Please see the top of this thread - https://github.com/eForms/eForms/issues/93#issuecomment-420237480 and https://github.com/eForms/eForms/issues/93#issuecomment-421142588. 

Yes, they will be separated and allow multiple choice.
