### ISSUE TITLE
BG-708 (Place of Performance); Description; from under- to over-specification?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#94]
In the current forms, the place of performance of a contract is denoted by a text and a non-empty list of NUTS codes. You are not the only ones who have thought that this might be a bit imprecise.

There are other usages, however, that are currently possible but hardly seem to fit into the new data model:
- The place of delivery or performance might be within one or the other contracting body.
- The performance might happen within the properties of the supplier.
- There might be special restrictions as ”any place in the common economic area,“ like, for server hosting.
- There might not be imposed any constraints.

This may be an indicator that a special ”location code identifier“ may come in handy, as we also today see some late procurement publications rejections for being supposed to operate in See-above-town.

**Comment by JachymHercher** [comment]
Good point, thanks. I'd like to better understand the options that don't fit in. Looking at the examples above:
1. Do I understand it correctly that the "or" is part of what needs to be submitted? If yes, couldn't it be covered by two BG-708 (potentially with some additional textual information)? Could you give a practical example when this happens? 
2. Couldn't this be covered by "No constraints"? I'm wondering whether this is important for the buyer. 
3. No question.
4. No question.

The needs above could be covered by adding the optional text description of the place of performance and making the fields optional. To support a bit more structure data approach, an indicator BT could be added with the meaning along the lines of "There are no constraints on the place of delivery beyond what is stated in the place of delivery text field". The other structured place of delivery BTs would then be optional only if this indicator was selected. What do you think?

Sidenote: would you agree that the cases above are relevant only for CN, but not for CANs, because the place should already be known?

**Comment by tinne** [comment]
1. Here I tried to summarize supplies (delivery) and services (performance) in one sentence, so eXclusive OR.
2. This is important for a buyer in the example of our industry (IT services) because the buyer decides between more control (work is done on her own premises) and less infrastructure (work is done with the seller and the buyer need not provide offices, computer hardware and facilities).

Regarding the CN data modeling; I'm fine with it.

Regarding the sidenote, I am not yet sure how this would fit with the server hosting example ”Computing and storage will be done with a data center within the EU with a network link capacity of at least...“

**Comment by JachymHercher** [comment]
In principle we could: there could be an "Other" code and any further specifications would be given in the text field described above. However, as discussed in #57,  we try to have "Other" only in cases where we absolutely need to. Looking at the examples you gave:
- "in buyer district, with any buyer, addresses given" - can be submitted using the other fields. 

(Note: in a user interface, if needed, there can still be a clickable button "same as in the buyer section", which copies the address from the buyer section into the place of performance.)
- "the area of buyer's activity" - known in advance, so can be specified using the other fields, no?
- "a pointer to a dedicated map" - should fall into the other categories, the map in the procurement documents can then provide more details 

Concerning the structured text you mention, we'd be rather inclined to think that this level of detail is not useful for companies nor other stakeholders? (Or at least not to the extent that it needs to be structured?)

**Comment by tinne** [comment]
Yes, it seems appropriate to not further detail the level. Also, the Place Contact Point seems to be a mismatch of information that could be given otherwise.

**Comment by JachymHercher** [comment]
Based on the discussion above, we suggest the following changes:
1. Adding an optional text field into BG-708 (Place of Performance): BT-728 (Place Additional Information) with a definition of "Additional information about the place of performance."
2. Adding a CM BT code in the same BG: BT-727 (Place Services Other) with a definition of "There are other restrictions on the place of performance (e.g. "anywhere in the European Economic Area", "anywhere in the given country")." @tinne, would you agree that these cases apply only for services? 
3. "Place Country" changed from M to CM. (Because a country will not be given if "Anywhere" is selected.)

The codelist for BT-727 could be the following (FYI @muricna):
- "anywhere": useful e.g. for certain types of services that can be provided remotely 
- "anywhere in the European Economic Area": useful e.g. for server hosting because of data protection
- "anywhere in the given country": useful e.g. for national security (country would be given in BT-5141).

**Comment by tinne** [comment]
Regarding the question whether a place of performance would apply to service contracts only:
- In case neither the Main Nature (BT-23) nor some Additional Nature (BT-531) of the contract is services this seems highly unlikely.
- Most such contracts would perhaps be D24 or D81, where D25 seems more probable than D23, but I am not sure.

**Comment by JachymHercher** [comment]
Thanks, my impression is the same as in your first bullet. Would you have any examples for the second? Or would you find the restriction to services reasonable?

**Comment by guascce** [comment]
I wonder whether the codelist for place of performance you have thought of is and can be sufficient. It reflects your understanding of the possible cases and I meant by political changes events such as BREXIT that may require to create a new code.
 My other question is the need for such a code. Which value does it bring to create codes for such information?

**Comment by JachymHercher** [comment]
If you have proposals for more/less codes, we are happy to consider them. "Anywhere" and "Anywhere in the given country" seem to be quite stable. You are correct that the meaning of "Anywhere in the EEA" could change in time (e.g. because of Brexit), but we are not sure this would pose a particular problem. (It just means a reader/reuser must take into account when the notice was published.)

The reason for establishing the codes is to express as much information as possible as structured data. This increases the usefulness of the data and has been requested by various stakeholders. Furthermore, in this specific case, having the information structured would allow using it to filter business opportunities. The examples of when these codes can be useful are given in the last section of https://github.com/eForms/eForms/issues/94#issuecomment-414375525.

**Comment by guascce** [comment]
"It just means a reader/reuser must take into account when the notice was published." How will you deal with a case where the CN is published with one meaning and the CAN with another meaning?
In statics it is also usually quite important that code list keep a stable meaning.

**Comment by JachymHercher** [comment]
That's context specific, the solution will depend on the problem and the user. Nevertheless, Brexit-problems seem to be quite an edge case. We're open to any proposals on how to it better, but I'm not sure it's worth investing too much time in catering for this scenario... (One could just as well consider the dangers of border changes or renaming of countries/regions/cities, etc.)

**Comment by tinne** [comment]
The only valid dates giving semantics would be the publication date of the CN with regard to legal regulation of the public body and the contract date with regard to its any implications on the fulfilment practice, would they not?

In doubt, I would thus suggest to base any validity implications on the state of the world (and not only regarding BT-727) at that date.
